enonic/xp

modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindow.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindowController.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/InspectionsPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/page/contextwindow/inspections-panel.less

- renamed button and added padding around
- used action instead of onSaveRequested callback in context window
- fixed multiple context menus in live edit

CMS-4749 Live Edit - Add save button to context window settings

---

modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/SecurityWizardStepForm.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/SettingsWizardStepForm.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/_module.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts

- also made Element.addChild/removeChild chainable

CMS-4743 Add New step to content wizard "Settings"

---

modules/wem-admin-ui/src/main/resources/web/admin/common/js/app/bar/AppBar.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar.less
modules/wem-admin-ui/src/main/resources/web/admin/common/styles/variables/transitions.less

Refactored `AppBar`.
Removed the home button icon js implementation with css.
Simplified the `HomeButton` code.

CMS-4724 App Header - New Tab design

---

modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/region/ComponentInspectionPanel.ts

CMS-4777 Live Edit - Fix component context window

---

modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemViewPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemViewToolbar.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/PrincipalWizardPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/PrincipalWizardToolbar.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserStoreWizardToolbar.ts
modules/wem-admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserstoreWizardPanel.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/js/app/bar/AppBarTabMenu.ts
modules/wem-admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar-tab-menu.less

CMS-4855 App Header - New Tab design - Browser-like tab design

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/grid/Grid.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/combobox/combobox.less

Made some related changes to the Grid and ContentTreeGrid, improving the
resize performance.
Fixed the styling of the `.combobox` class, applying similar to
`.tree-grid` sizing model .

CMS-4946 Live Edit - Performance problems caused by TreeGrid.postLoad

---

modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/login/LoginForm.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less

Updated the home page styling.

CMS-4947 Launcher visual improvements

---

modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/applauncher/AppLauncher.ts
modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/home/HomeMainContainer.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less

Added background image to the application panel in each places.
Added transparency to the header panel background.
Updated some font sizes in the header panel.

CMS-4997 App Header - Fix styling of app name

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/inputtype/image/image-selector.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/input/input-view.less

Fixed the highlight.
Fixed the problem with the upload button transparency.

CMS-4985 Fix highlighting of automatically set input

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/UserAppPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/GroupRoleWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/PrincipalWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserItemWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserstoreWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/AppPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/bar/AppBarTabMenuItem.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/ElementHelper.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/geo/GeoPoint.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabItem.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePicker.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/time/LocalTime.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar-tab-menu.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-header.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/z-index.less

Updated the TabItem's label setter and setting logic.
Updated the styles for the wizard header.

CMS-4983 Unnamed - Fix presentation of "unnamed" content in wizard

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-header.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/combobox/combobox.less

Added display name and name color change for generated values.
Added `trim()` call on generated strings to exclude excess whitespaces
from names.

CMS-4993 Unnamed - Adjustments to colors for generated fields

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/UserAppPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardValidityManager.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatusViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryViewer.ts

Renamed the `WizardStepsValidityManager` to `WizardValidityManager`.
Added validity check to the `WizardHeader` and it's child classes.

CMS-5071 Validation - Display name and name are required fields

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/SettingsWizardStepForm.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts

Update the implementation to skip the unnecessary focus.

CMS-5096 WizardPanel - Header loses its focus

---

modules/admin-impl/src/main/java/com/enonic/wem/admin/json/content/ContentSummaryJson.java
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/apply_content_permissions_success.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/create_content_success.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/duplicate_content_success.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/get_content_full.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/get_content_summary.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/get_content_with_page.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/get_content_with_site.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/list_content_full.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/list_content_full_byPath.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/list_content_summary.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/list_content_summary_byPath.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/page/update_page_success.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/update_content_nothing_updated.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/update_content_success.json
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummary.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ContentSummaryJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/ContentState.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/_module.ts
modules/core-api/src/main/java/com/enonic/wem/api/content/Content.java
modules/core-api/src/main/java/com/enonic/wem/api/content/ContentState.java
modules/core-impl/src/main/java/com/enonic/wem/core/content/ContentNodeTranslator.java

-New property added to Content domain object and to frontend json 
-Tests updated

CMS-5093 Populate property NodeState to Content-layer and to ContentJson

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/browse/UserTreeGridItemViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatusViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelectorDisplayValue.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelectorViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/security/Principal.ts
modules/admin-ui/src/main/resources/web/admin/common/js/security/acl/AccessControlEntry.ts
modules/admin-ui/src/main/resources/web/admin/common/js/security/acl/UserStoreAccessControlEntry.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/NamesAndIconViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/security/PrincipalViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/security/acl/AccessControlEntryViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/security/acl/UserStoreAccessControlEntryViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/util/StringHelper.ts

Fixed the tab label of the unnamed content.
Replaced <name> with unnamed.
Replaced <Display Name> with <Unnamed %item_type%>.

CMS-5058 Unnamed - Fix presentation of "Unnamed" in browse lists etc

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatusViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/ContentState.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/content-summary-and-compare-status-viewer.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/content-summary-viewer.less

Added a line through style to the content with `PENDING_DELETE` status.

CMS-5086 Browse - add strikethrough design for "Pending Delete" status

---

modules/admin-ui/src/main/resources/web/admin/common/js/app/bar/AppBarTabMenu.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabMenu.ts

CMS-5073 Browse - Open new tabs first, not last

---

modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/home/HeaderPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/MoveContentDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/SortContentDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindowToggler.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/ChangeUserPasswordDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/icons/icons.less
modules/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/move-content-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/sort-content-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/cycle-button.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/user/wizard/change-password-dialog.less

Changed text (Upload [somename] finished -> <contenttype> "somename" created successfully) and background (green -> blue) when uploading media

CMS-5131 Browse view - Fixup feedback message after uploading media

---

modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/home/HeaderPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/MoveContentDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/SortContentDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindowToggler.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/ChangeUserPasswordDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/icons/icons.less
modules/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/move-content-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/sort-content-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/cycle-button.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/user/wizard/change-password-dialog.less

Done: 
-Remove the "opacity" from the home screen app-bar (should not see the stripe)
-Add a dropdown menu when clicking user, according to design
-Enable clicking logout from this menu (according to design)
-Remove current logout text/link

CMS-5106 Modal windows - Adjustment to action buttons

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-tree-grid.less

Added green color to the status cell, when content is online.

CMS-5136 (Small task) Browse CM - Add green color to "online" status

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-header-with-display-name-and-name.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less
modules/admin-ui/src/main/resources/web/admin/common/styles/styles.less

Disabled the input for content with status different from `NEW`.

CMS-5128 Name field - prevent accidental renaming

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts

Disable the removing of the nodes with `PENDING_DELETE` status.

CMS-5057 New behavior for delete content

---

modules/admin-impl/src/main/java/com/enonic/wem/admin/rest/resource/content/ContentResource.java
modules/admin-impl/src/main/java/com/enonic/wem/admin/rest/resource/content/json/BatchContentJson.java
modules/admin-impl/src/test/java/com/enonic/wem/admin/rest/resource/content/ContentResourceTest.java
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/batch_content_params.json
modules/admin-impl/src/test/resources/com/enonic/wem/admin/rest/resource/content/batch_content_summary.json
modules/admin-ui/src/main/resources/web/admin/common/js/content/BatchContentRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/BatchContentResult.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts

Implemented batch REST handler for POST.
Updated tests.
Implemented Request and Response classes on the ui.

CMS-5168 Content GET batch REST handler

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemVersionsPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentVersionsTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/NamesAndIconView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentVersionViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/GetActiveContentVersionsRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ActiveContentVersionJson.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/content-item-versions-panel.less
modules/core-impl/src/main/java/com/enonic/wem/core/content/ContentVersionFactory.java

Update the versions detail view page with the following changes:
Make the "all versions" view default
Drop the iteration number column, making datetime the first column
Drop the user icon
Output the real name of the "version creator" as column 2 (after date)
Replace "Dummy content" text with "No comments"
A

CMS-5132 Browse CM - Fixup version info page

---

modules/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less

-Do icon lighter
-adjust size of user login input
-adjust positioning of inputs so they are in initial position(before login icon was added)

CMS-5135 Admin UI - Add login icon to start page

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/MoveContentDialog.ts

-Added giveFocus() call for show() method

XP-35 Move dialog - Automatically set focus in the input

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/DragAndDrop.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/region-view.less

- fixed js error when dragging in and out of iframe
- added 20px padding at the bottom and 10 px at the top
- no paddings added at sides
- removed highlighting when dragging

XP-81 Live Edit - Adjustments to LE placeholders

---

modules/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowsePanel.ts

Fixed the problem with preview panel updated wrong, after several items were deleted.

XP-48 Browse - Improvements to browse grid update based on server events

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryByDisplayNameComparator.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/ContentFormContext.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/ContentTypeComboBox.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/PageTemplateContentTypeLoader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/inputtype/ContentTypeFilter.ts
modules/core-api/src/main/java/com/enonic/xp/schema/content/ContentTypeForms.java

-created specific loader for page template that filters and then sorts ContentTypes before setting them to combobox
-'supports' field is made required

XP-16 Page Template form - Adjustments to "supports" field

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemPreviewPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemPanel.ts

- Applied timestamp based url usage as for other images
- Added updating of preview panel if appropriate item is selected in content list view

XP-41 Update image: Preview image is cached and does not update

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/create/NewContentDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/text/FileInput.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/uploader/Uploader.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less

-disabled possibilty to upload media in 'new content dialog' if parent content is template folder ('portal:template-folder')
-updated 'uploader.ts' to correctly handle enabling/disabling uploader
-updated 'FileInput.ts' to return uploader used

XP-47 Wizard - Possible to upload media in _templates folder

---

modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less

XP-4 Modal window - Modal window often positioned low on first load

---

modules/core-api/src/main/java/com/enonic/xp/form/inputtype/ContentSelectorConfig.java
modules/core-api/src/main/java/com/enonic/xp/form/inputtype/ContentSelectorConfigJsonSerializer.java
modules/core-api/src/main/java/com/enonic/xp/form/inputtype/ContentSelectorConfigXmlSerializer.java
modules/core-api/src/main/java/com/enonic/xp/schema/content/ContentTypeForms.java
modules/core-api/src/test/java/com/enonic/xp/form/inputtype/ContentSelectorConfigJsonSerializerTest.java
modules/core-api/src/test/java/com/enonic/xp/form/inputtype/ContentSelectorConfigXmlSerializerTest.java
modules/core-schema/src/main/java/com/enonic/xp/core/impl/schema/content/BuiltinContentTypeProvider.java

-added  mandatory input of type Content_Selector to Shortcut content type
-refactored ContentSelectorConfig.newRelationshipConfig() -> ContentSelectorConfig.create()

XP-77 Wizard - Shortcut content type fixups

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/geo/GeoPoint.ts

-changed input's dummy text
-changed input's title

XP-92 Geopoint inputType - Change dummy text

---

modules/core-itest/src/test/java/com/enonic/wem/core/content/ContentServiceImplTest_getNearestSite.java

-created test for ContentService.getNearestSite

XP-101 Create test for ContentService.getNearestSite

---

modules/core-itest/src/test/java/com/enonic/wem/core/content/AbstractContentServiceTest.java
modules/core-itest/src/test/java/com/enonic/wem/core/content/ContentServiceImplTest_getByPaths.java
modules/core-itest/src/test/java/com/enonic/wem/core/content/ContentServiceImplTest_getNearestSite.java

XP-103 Create itest for ContentService.getByPaths

---

modules/core-itest/src/test/java/com/enonic/wem/core/content/AbstractContentServiceTest.java
modules/core-itest/src/test/java/com/enonic/wem/core/content/ContentServiceImplTest_duplicate.java

XP-105 Create itest for ContentService.duplicate

---

modules/core-itest/src/test/java/com/enonic/wem/core/content/ContentServiceImplTest_findByParent.java

XP-104 Create itest for contentService.findByParent

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/SortContentTabMenu.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/SortContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/sort-content-dialog.less

-added arrow  for sorting dropdown in sorting modal dialog
-updated size of drag and drop icon in sorting modal dialog
-changed last column in sorting modal dialog content to be 'last modified'

XP-98 Browse - Sort dialogue fixups

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelectorSelectedOptionsView.ts

-Fixed checkboxes slelection behaviour
-Added auto check for newly uploaded images
-Edit button works as expected in both Chrome and FF
-Other issues were discovered with Image selector - refer to xp-109 youtrack comments

XP-109 ImageSelector - Misc fixups

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/DragAndDrop.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageUnlockedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/mask/Mask.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/drag-helper.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/mask.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/z-index.less
modules/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/shader.less

- fixed the ability to drop on the locked page
- fixed the drag helper z-index issues
- also fixed drag helper not shown when dragging from context window after resetting the page

XP-1 Live Edit - Problems with drag helper

---

modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentView.ts

- Added support for parsing components/regions nested on different levels inside page, layout and region views

XP-166 Live Edit - Layout issues

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts

- Applied same timepicker controls management as for Date and Datetime pickers

XP-142 Time picker boxes remain open after moving focus to another input

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar-tab-menu.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- Flag removed from thumbnail/form icon
- Red text fixed
- Moved and aligned flag on tab

XP-117 Validation flag - Move flag to tab, drop red text on tab

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts

Updated the child insert logic.

XP-99 Browse grid - Bug when creating new content before expanding tree

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/ContentWizardImageUploadedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts

- Created ImageUploadEvent for content wizard
- Added thumbnail icon handling on image upload event
- Added wizard/content metadata update on image upload event

XP-127 fixes to update image

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/region/Region.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/LiveEditPageInitializationErrorEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/_module.ts
modules/admin-ui/src/main/resources/web/admin/live-edit/js/LiveEditPage.ts

Improved error handling when regions rendered don't match with page model.

XP-195 Live Edit - Layout bug storing components in wrong regions.

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar-tab-menu.less

- Fixed name displaying and preserved same layout

XP-208 Wizard tab - Long display names break presentation of tab

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/tag/Tag.ts

- Added validation triggering on each event of adding/removing tag

XP-158 Tag input type: Impossible to publish a content , validation message still present , when 2 required tags added

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentIconResource.java
modules/core-api/src/main/java/com/enonic/xp/content/Media.java
modules/core-api/src/main/java/com/enonic/xp/content/attachment/image/ImageAttachmentScale.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ImageContentProcessor.java

-added logic to choose attachment for thumbnail based on 'size' parameter

XP-40 Use best fit image to generate thumbnail for media type Image

---

modules/admin-ui/package.json
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/create/NewContentDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/js/BrowserHelper.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/text/FileInput.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePickerPopup.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/actions/TreeGridActions.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/actions/TreeGridToolbarActions.ts

-upgrading to TypeScript 1.4.1 and solving appearing compilation issues

XP-233 Upgrade to latest TypeScript

---

modules/core-api/src/main/java/com/enonic/xp/name/Name.java
modules/core-api/src/main/java/com/enonic/xp/name/NameCharacterHelper.java
modules/core-api/src/main/java/com/enonic/xp/util/CamelCaseConverter.java

Done:
CRITICAL: "static final" arrays should be "private" - updated required files to have 'private' accessor for mentioned fields

XP-96 Fix up critical and blocker issues reported by Sonar

---

modules/core-api/src/test/java/com/enonic/xp/branch/BranchTest.java
modules/core-api/src/test/java/com/enonic/xp/branch/BranchesTest.java

Added test for the branch package.

XP-238 Add more unit tests for branch package in API

---

modules/admin-ui/grunt/ts.js
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentComboBox.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentIds.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentServerEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/ContentFormContext.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/region/ComponentPropertyChangedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/region/Region.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/region/Regions.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/site/ModuleConfig.ts
modules/admin-ui/src/main/resources/web/admin/common/js/data/Property.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/LiveEditModel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/mixin/MixinNames.ts
modules/admin-ui/src/main/resources/web/admin/common/js/security/CheckEmailAvailabilityRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/security/acl/PermissionSelector.ts

-fixed typescript errors when exporting type definitions

XP-254 Fix typescript errors when exporting type definitions

---

modules/core-api/src/test/java/com/enonic/xp/query/aggregation/AggregationQueriesTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/BucketAggregationQueryTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/DateHistogramAggregationQueryTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/DateRangeAggregationQueryTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/DateRangeTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/DistanceRangeTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/GeoDistanceAggregationQueryTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/HistogramAggregationQueryTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/NumericRangeAggregationQueryTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/NumericRangeTest.java
modules/core-api/src/test/java/com/enonic/xp/query/aggregation/TermsAggregationQueryTest.java
modules/core-api/src/test/java/com/enonic/xp/query/expr/DynamicOrderExprTest.java
modules/core-api/src/test/java/com/enonic/xp/query/expr/FieldOrderExprTest.java
modules/core-api/src/test/java/com/enonic/xp/query/expr/OrderExpressionsTest.java
modules/core-api/src/test/java/com/enonic/xp/query/expr/QueryExprTest.java
modules/core-api/src/test/java/com/enonic/xp/query/filter/BooleanFilterTest.java
modules/core-api/src/test/java/com/enonic/xp/query/filter/FiltersTest.java
modules/core-api/src/test/java/com/enonic/xp/query/filter/RangeFilterTest.java
modules/core-api/src/test/java/com/enonic/xp/query/filter/ValueFilterTest.java
modules/core-api/src/test/java/com/enonic/xp/query/parser/QueryParserTest.java

-added more unit tests for export package in com.enonic.xp.query

XP-243 Add more unit tests for query package in API

---

modules/core-api/src/main/java/com/enonic/xp/export/NodeImportResult.java
modules/core-api/src/test/java/com/enonic/xp/export/ExportNodesParamsTest.java
modules/core-api/src/test/java/com/enonic/xp/export/ImportNodesParamsTest.java
modules/core-api/src/test/java/com/enonic/xp/export/NodeExportResultTest.java
modules/core-api/src/test/java/com/enonic/xp/export/NodeImportResultTest.java

-added more unit tests for export package in com.enonic.xp.export

XP-241 Add more unit tests for export package in API

---

modules/core-api/src/test/java/com/enonic/xp/aggregation/AggregationTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/AggregationsTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/BucketAggregationTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/BucketTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/DateHistogramBucketTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/DateRangeBucketTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/GeoDistanceRangeBucketTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/NumericRangeBucketTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/SingleValueMetricAggregationTest.java
modules/core-api/src/test/java/com/enonic/xp/aggregation/StatsAggregationTest.java

Added test for the module package.

XP-239 Add more unit tests for aggregation package in API

---

modules/core-api/src/test/java/com/enonic/xp/content/site/SiteTest.java

- Added unit tests to cover >85% of lines of code

XP-249 Add more unit tests for content.site package in API

---

modules/core-api/src/test/java/com/enonic/xp/module/ModuleEventTypeTest.java
modules/core-api/src/test/java/com/enonic/xp/module/ModuleKeyTest.java
modules/core-api/src/test/java/com/enonic/xp/module/ModuleKeysTest.java
modules/core-api/src/test/java/com/enonic/xp/module/ModuleRelativeResolverTest.java
modules/core-api/src/test/java/com/enonic/xp/module/ModuleUpdatedTest.java
modules/core-api/src/test/java/com/enonic/xp/module/ModuleVersionTest.java
modules/core-api/src/test/java/com/enonic/xp/module/ModulesTest.java

Added test for the module package.

XP-242 Add more unit tests for module package in API

---

modules/core-api/src/test/java/com/enonic/xp/data/JavaTypeConvertersTest.java
modules/core-api/src/test/java/com/enonic/xp/data/PropertyIdTest.java
modules/core-api/src/test/java/com/enonic/xp/data/PropertySetTest.java
modules/core-api/src/test/java/com/enonic/xp/data/PropertyTest.java
modules/core-api/src/test/java/com/enonic/xp/data/PropertyTreeTest.java
modules/core-api/src/test/java/com/enonic/xp/data/ValueTest.java

-added more unit tests for data package 'com.enonic.xp.data' so we cover more than 85% line coverage.

XP-237 Add more unit tests for data package in API

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/FormItemOccurrence.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/support/InputOccurrenceView.ts

- Added additional check for remove button display of InputOccurenceView that takes in account minimum allowed value

XP-121 Set remove buttons in input elements according to occurrences

---

modules/core-api/src/main/java/com/enonic/xp/content/page/region/ImageComponent.java
modules/core-api/src/main/java/com/enonic/xp/content/page/region/LayoutComponent.java
modules/core-api/src/main/java/com/enonic/xp/content/page/region/TextComponent.java
modules/core-api/src/test/java/com/enonic/xp/content/page/DescriptorKeyTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/DescriptorsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/EditablePageTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/PageDescriptorsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/PageRegionsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/PageTemplateTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/PageTemplatesTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/PageTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/ComponentsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/ImageComponentTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/LayoutComponentTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/LayoutDescriptorsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/PartDescriptorsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/RegionDescriptorTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/RegionDescriptorsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/RegionPathTest.java
modules/core-api/src/test/java/com/enonic/xp/content/page/region/TextComponentText.java

-added more unit tests for data package 'com.enonic.xp.content.page' so we cover more than 85% line coverage.

XP-247 Add more unit tests for content.page package in API

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/ContentSummaryJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/CountItemsWithChildrenJson.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/remove/ContentDeleteDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/remove/ContentDeleteDialogAction.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/delete/DeleteDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/CountContentsWithDescendantsRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/browse/browse-selection-item.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/delete/delete-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/mask.less

-Enabled delete button also for items with children
-Updated Delete dialogue according to design (re-used bulk selection design from detail view)
-Dropped grey background for bulk items in detail view too (made these lists exactly the same)
-Added a totalcount of how many items will be deleted in the delete button of the modal window.
-Made delete button use red color
-BONUS: also found issue with mask spinner and resolved it

XP-210 Recursive Delete - Support recursive delete

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/moduleconfigurator/ModuleConfiguratorComboBox.ts
modules/admin-ui/src/main/resources/web/admin/common/js/module/ModuleLoader.ts
modules/admin-ui/src/main/resources/web/dev/test/common/index.html
modules/admin-ui/src/main/resources/web/dev/test/common/js/module/ModuleLoaderTest.js

Added an option to filter modules in the ModuleLoader + specs. Modules can now be filtered by any fields and values

Xp 191: Don´t show stopped modules in the new Site module

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/MoveContentResultJson.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/MoveContentDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/MoveContentRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/MoveContentResult.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/MoveContentResultJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core-repo/src/main/java/com/enonic/wem/repo/internal/entity/MoveNodeCommand.java
modules/core-repo/src/test/java/com/enonic/wem/repo/internal/entity/MoveNodeCommandTest.java

XP-252 "Status 500 Server Error" message appears when user tries to move a content to folder, which contains a content with the same name
-updated contentResourse and other related classes to handle moving multiple contents
-updated ui to handle successfull/failed moving

XP-299 Issues with moving multiple contents

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts

- Removed publish button enable/disable on validity changed events - now only users permissions are taken in account

XP-291 Content Wizard - Don't disable publish button if form is invalid

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/time/Time.ts
modules/admin-ui/src/main/resources/web/admin/common/js/util/DateHelper.ts
modules/admin-ui/src/main/resources/web/dev/test/common/js/util/DateHelperTest.js

- Made time value to not convert to UTC before value creation

XP-322 LocalTime converts to UTZ

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/singleselector/SingleSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/support/BaseInputTypeSingleOccurrence.ts

- Added validation listeners to BaseInputTypeSingleOccurence
- For Single Selector adjusted validation process to handle situations when required value is not selected.

XP-267 Remove button 'Add' from the Single Selector Form View Panel

---

modules/core-repo/src/test/java/com/enonic/wem/repo/internal/entity/FindNodesByQueryCommandTest_dateTime.java

- added tests for dateTime function

XP-174 Support new query-functions for date and time

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageContentComboBox.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts

Added new class ImageContentComboBox inheriting from RichComboBox. Refactored ImageSelector.

XP-56 Refactor ImageSelector to use lazy loading

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TinyMCE.ts

- [Fixed] - removed  autoresize_max_height parameter from init function

XP-362 TinyMCE - Make editor field grow unlimited

---

modules/portal-api/src/main/java/com/enonic/xp/portal/PortalResponse.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/controller/ControllerScriptImpl.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/parser/HtmlBlockParser.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/parser/HtmlBlocks.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/parser/StaticHtml.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/postprocess/PostProcessEvaluator.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/postprocess/injection/ContributionInjection.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/postprocess/PostProcessEvaluatorTest.java
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalResult1.html
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalResult2.html
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalResult3.html
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalResult4.html
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalSource1.html
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalSource2.html
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalSource3.html
modules/portal-impl/src/test/resources/com/enonic/xp/portal/impl/postprocess/postProcessEvalSource4.html

Changelog: 
- Added support for head and body contributions in controller.

XP-331 Implement head and body contributions

---

modules/core-api/src/main/java/com/enonic/xp/xml/parser/XmlContentTypeParser.java

XP-387 Make <allow-child-content> default to true in content-type.xml

---

modules/core-api/src/main/java/com/enonic/xp/i18n/LocaleService.java
modules/core-api/src/main/java/com/enonic/xp/i18n/MessageBundle.java

- [Added] . LocaleService  and MessageBundle  interfaces

XP-382 Implement LocaleService in API

---

modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/view/LocalizeFunction.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/view/LocalizeFunctionTest.java

- [Added] LocalizeFunction and appropriate test.

XP-384 Implement view function for localize

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tinymce.less

- [Changed]. Made tinymce toolbar to be hidden while text area not in focus. Adjusted thickness of border of edit area.

XP-321 TinyMCE editor - Enable floating ribbon

---

modules/core-repo/src/main/java/com/enonic/wem/repo/internal/NodeSettingsBuilderImpl.java

-set "cluster.routing.allocation.disk.threshold_enabled" to false

XP-405 Set default disk watermark threshold-settings to false

---

modules/admin-ui/src/main/resources/web/admin/apps/module-manager/js/app/view/ModuleItemStatisticsPanel.ts

-[Added] Added alphabetic asc sorting to items shown in  module detail view

XP-413 Module Detail View - Fix sorting of items in lists

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/_module.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentPublishPromptEvent.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/_module.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/action/PublishContentAction.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/_module.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/main.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/styles.less

- [Added] Publishing wizard dialog

XP-420 Publishing Wizard - Add Basic Modal window when clicking publish

---

modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/controller/ControllerResource.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/resource/render/ComponentResourceTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/resource/render/PageResourceTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/resource/service/ServiceResourceTest.java

-Updated ControllerResource to set URI when handling request

XP-434 The uri property of the request in controller.js is never set

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageContentComboBox.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/inputtype/image/image-selector.less

Moved the ImageUploader to the ImageSelector.
Removed the ImageUploadDialog from the ImageSelector.
Replaced upload button with the uploader.

XP-418 dnd on imageSelector - Make new dropzone support upload

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResolvePublishDependenciesJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResolvePublishDependenciesResultJson.java
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/main.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ResolvePublishDependenciesRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ResolvePublishDependenciesResult.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/core-api/src/main/java/com/enonic/xp/content/ContentService.java
modules/core-api/src/main/java/com/enonic/xp/content/PushContentRequests.java
modules/core-api/src/main/java/com/enonic/xp/content/ResolvePublishDependenciesParams.java
modules/core-api/src/main/java/com/enonic/xp/content/ResolvePublishDependenciesResult.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ResolvePublishDependenciesCommand.java

- [Added] new rest service, commands and appropriate classes to handle resolving publish dependencies at back-end
- [Added] ResolvePublishDependenciesRequest and appropriate classes to handle resolving publish dependencies at front-end
- [Modified] Publish dialog

XP-421 Publishing Wizard - Create Rest service for publishing wizard

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageUploadDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/inputtype/image/image-selector.less

Fixed the issue with saving content, after images uploaded.
Fixed the issue with unavailability of selected option removing, after image failed to load.

XP-456 Content is not updated with images from ImageSelector

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/inputtype/image/image-selector.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

Added dropdown styles like in NewContentDialog.
Some other css fixes.

XP-417 dnd on imageSelector - Make the input a "dropzone"

---

modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/browse/UserTreeGridActions.ts

-Updated 'Delete' button to be disabled for  Users and Groups folders

XP-431 Users App: impossible to delete "Users" and "Groups" folders

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentGridDragHandler.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/ImgEl.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/ImgElHelper.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/FocalEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/image-uploader.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/focal-editor.less
modules/admin-ui/src/main/resources/web/admin/common/styles/styles.less
modules/admin-ui/src/main/resources/web/dev/test/common/js/ui/image/focal-editor.html

- fixed Element.registerChildElement to support nodes
- refactored Element.fromString/fromHtmlElement/fromSelector methods to use each other
- created FocalEditor that works in FF, Chrome and IE
- integrated FocalEditor into ImageUploader and Image wizard
- also fixed missing var warning in PageView and LayoutComponentView

XP-408 Image Focal Point - Add focal point Editor

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/core-api/src/main/java/com/enonic/xp/content/PushContentParams.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java

- [Modified] Services to use additional parameter for resolving dependencies during push
- [Modified] publish dialog to pass to rest service only ids of contents to publish

XP-454 Refactor push content to not check whats to be published

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/security/SecurityResource.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/security/SecurityResourceTest.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/security/createUserParams.json
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/ChangeUserPasswordDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserWizardPanel.ts

-Added required password validation
-Small fixes

XP-465 Users App: missed validation for 'password' - required input

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/PageModel.ts

-Update handling of click on 'Apply' button
-On live edit unlock reseting inspection selection
-Small fix for setting default template

XP-450 Context Menu - Apply not working for inspect page

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanelFactory.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatusFetcher.ts

-Reduced number of calls to backend to fetch content by id from 3 to 1

XP-337 Same requests are sent multiple times when refreshing page

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/DragAndDrop.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/Shader.ts
modules/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/shader.less

* Removed the "locked screen" splash
* Clicking a locked page opens context menu with option "Customize" which unlocks the page
* When drag'n'dropping an item from "insert menu", locked mode automatically turns off

XP-446 Live Edit - Improvement of "locked" screen mode

---

modules/core-repo/src/test/java/com/enonic/wem/repo/internal/entity/ResolveSyncWorkCommandTest.java

- [Added] resolveDependenciesOfMovedNodes() test that checks resolve sync work command against the moved nodes

XP-504 Moved content behaves strange in ResolveSyncWorkCommand

---

modules/core-impl/src/main/java/com/enonic/xp/core/impl/i18n/MessageBundleImpl.java
modules/core-impl/src/test/java/com/enonic/xp/core/impl/i18n/MessageBundleImplTest.java

- [Modified] MessageBundleImpl to return preset value when key or value is missing
- [Modified] tests

XP-474 Handling of missing parameters / missing key in bundle

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/data/PropertySet.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/ImgEl.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/FocalEditor.ts
modules/core-api/src/main/java/com/enonic/xp/content/CreateMediaParams.java
modules/core-api/src/main/java/com/enonic/xp/content/UpdateMediaParams.java
modules/core-api/src/main/java/com/enonic/xp/form/inputtype/ImageUploader.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ImageFormDataBuilder.java

- ImageUploader now capable of parsing both string and set format of attachment, and convert them to the new set one
- fixed the PropertySet.removeProperty null pointer if property was missing

XP-410 Image Focal Point - Visualize existing focal point in UI

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-panel.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tinymce.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/color.less

-Updated TinyMCE toolbar border and shadow to be same as for step-navigation-panel when scrolling

XP-521 TinyMCE - More adjustments to floating toolbar

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/form-item-set-occurrence-view.less

- [Modified] bottom margin for .form-item-set-occurrence-view to visually separate formItemSets

XP-552 Content Wizard - Design broken for formItemSets

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/ContentWizardActions.ts

- [Modified] wizard actions to enable delete button for newly created content

XP-535 Always enable delete button right after content created

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/page/PageModel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts

-Bringing back changes, error in console when pressing ''customize" in LE

XP-519 Live Edit - Reset button no longer working

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageHelperImpl.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ImageParams.java
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentImageUrlResolver.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageUploadDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts

-[Modified] ContentImageResource class to accept scaleWidth parameter which when true makes ContentImageHelper to use  ScaleWidthFilter that prefers image width parameter over its height
-[Modified] ImageUploader and ImageUrlResolver to manage scaleWidth parameter

XP-553 Image Content Type - Problem with presentation of tall images

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/action/PublishContentAction.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/PublishAction.ts

- [Modified] Wizard's publish action to trigger ContentPublishPromptEvent

XP-562 Add publish wizard to publish button inside content

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ResolvedContent.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishContentJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResolveDependantsRequestParamsJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResolveDependantsResultJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResolvePublishDependenciesResultJson.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/resolve_publish_dependencies.json
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDependantItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishRequestedItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ResolvedPublishContentViewer.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/SelectionPublishItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/PublishContentRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ResolveDependantsRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolveDependantsResultJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvePublishDependenciesResultJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvedDependantContentJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvedPublishDependencyJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvedPublishRequestedContentJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/browse/browse-selection-item.less
modules/core-api/src/main/java/com/enonic/xp/content/PushContentRequests.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ResolvePublishDependenciesCommand.java
modules/core-impl/src/test/java/com/enonic/xp/core/impl/content/ResolvePublishDependenciesCommandTest.java

- Modified publishing process to fetch initially requested items only and lazily load dependants

XP-577 support lazy-loading of dependencies

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tinymce.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/color.less

XP-522 TinyMCE - Remove gradient from "pressed" paste as text button

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/main.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tinymce.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/tooltip.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/color.less

Merged design of TinyMCE tooltip and our tooltip:
-Used tooltip from tiny as base for new design
-Removed dropshadow
-Kept white on black
-Kept rounded corners
-Used same font as rest of XP
-[Important!] Updated all tooltips for content manager

XP-523 TinyMCE - Align tooltip design

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/shader.less

* Shade the page when it's locked and clicked
* Hide the customize context menu when locked page is clicked and the menu is visible

XP-525 Live Edit - Page context menu selection tuning

---

modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentView.ts

- improved component view parsing to reuse existing components in PageView, LayoutComponentView and RegionView
- unbound region listeners in RegionView when setting new region

XP-590 Live Edit - Dragging the first component into a "locked" page is buggy

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts

-[Modified] LiveFormPanel to not clean context window upon template change

XP-591 Live Edit - Buggy behaviour when toggling page templates

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/getDependantsRequestParamsJson.java
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDependantItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ResolvedPublishContentViewer.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/SelectionPublishItem.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ResolveDependantsRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvedPublishDependencyJson.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/browse/browse-selection-item.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less

-[Modified] publishing wizard in accordance with task's design

XP-539 Publish wizard GUI fixes and refactoring

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/region/DescriptorBasedDropdownForm.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/region/LayoutInspectionPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/region/PartInspectionPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/context-window.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/color.less

XP-636 Live Edit - Adjustments to context window styling

---

modules/core-api/src/main/java/com/enonic/xp/module/ModuleService.java
modules/core-module/src/main/java/com/enonic/xp/core/impl/module/ModuleServiceImpl.java
modules/core-module/src/test/java/com/enonic/xp/core/impl/module/ModuleServiceImplTest.java

-[Removed] install, update and uninstall actions from module service and tests

XP-627 Remove install from ModuleService

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/module/ModuleResource.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/module/ModuleResourceTest.java

-[Removed] install, uninstall and update methods from ModuleResource and from appropriate tests

XP-625 Remove install from ModuleResource

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TinyMCE.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tinymce-editor.css

- Updated margin for first and last elements in editor's body

XP-639 TinyMCE - Reduce padding

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/button/Button.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/FocalEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/focal-editor.less

XP-546 Focal point - Add reset button
XP-548 Focal point - Initially disable "Set focus" button

XP-545 Focal point - Center buttons

---

modules/portal-api/src/main/java/com/enonic/xp/portal/PortalRequest.java
modules/portal-api/src/main/java/com/enonic/xp/portal/PortalResponse.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/controller/ControllerScript.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/controller/ControllerScriptImpl.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/postprocess/PostProcessorImpl.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/DescriptorBasedComponentRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/ImageRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/LiveEditAttributeInjection.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/PageRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/TextRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/controller/ControllerResource.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/render/ComponentControllerResource.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/render/PageControllerResource.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/render/ShortcutControllerResource.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/service/ServiceControllerResource.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/controller/AbstractControllerTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/controller/ControllerScriptImpl_simpleTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/controller/PortalResponseSerializerTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/postprocess/PostProcessorImplTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/postprocess/injection/LiveEditInjectionTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/postprocess/instruction/ComponentInstructionTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/LiveEditAttributeInjectionTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/TextRendererTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/resource/service/ServiceResourceTest.java

- Builder added for PortalResponse
- code refactored

XP-620 Implement Builder on PortalResponse

---

modules/admin-ui/src/main/resources/web/admin/common/js/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/site/SiteDescriptor.ts
modules/admin-ui/src/main/resources/web/admin/common/js/site/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/site/json/SiteDescriptorJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/site/json/_module.ts

-[Added] SiteDescriptor class and SiteDescriptorJson interface

XP-652 Create TypeScript class SiteDescriptor

---

modules/core-api/src/main/java/com/enonic/xp/schema/mixin/Mixins.java
modules/core-api/src/test/java/com/enonic/xp/schema/mixin/MixinNameTest.java
modules/core-api/src/test/java/com/enonic/xp/schema/mixin/MixinNamesTest.java
modules/core-api/src/test/java/com/enonic/xp/schema/mixin/MixinTest.java
modules/core-api/src/test/java/com/enonic/xp/schema/mixin/MixinsTest.java

-'add' methods added
-Mixins related tests updated/refactored

XP-658 Implement add methods on Mixins

---

modules/core-api/src/main/java/com/enonic/xp/schema/content/ContentTypes.java
modules/core-api/src/test/java/com/enonic/xp/schema/content/ContentTypeTest.java
modules/core-api/src/test/java/com/enonic/xp/schema/content/ContentTypesTest.java

-'add' methods implemented
-tests updated

XP-659 Implement add methods on ContentTypes

---

modules/core-api/src/main/java/com/enonic/xp/schema/relationship/RelationshipTypes.java
modules/core-api/src/test/java/com/enonic/xp/schema/relationship/RelationshipTypeTest.java
modules/core-api/src/test/java/com/enonic/xp/schema/relationship/RelationshipTypesTest.java

XP-657 Implement add methods on RelationshipTypes

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/SelectionPublishItem.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less
modules/core-api/src/main/java/com/enonic/xp/content/PushContentRequests.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/PushContentCommand.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/PushContentRequestsFactory.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ResolvePublishDependenciesCommand.java

- [Modified] publishing process to include initial items into dialog even if  they are already published
- [Modified] dialog to disable “Publish” button when there is 0 items to publish
- [Modified] styling to correctly show content statuses

XP-680 Make selected published item appear in list even if online

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/SortContentTreeGrid.ts

-Removed strange symbol from browse grid and sort dialogue

XP-716 Sorting - Remove strange symbol associated with sorting

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts

-small fix (when editing content's name title was set again)

XP-715 Tooltip - Remove unnessesary tooltips

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

- also added deep child search by id to Element.findChildById

XP-642 Image Cropping - Add viewport resizing

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/icons/icons.less
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

- [Modified] ContentTreeGrid and TreeGrid to be able to handle row click events not only from subscribeOnClick() method
- [Modified] .icon-arrow-up4 class to show appropriate arrow

XP-718 Sorting - Enable clicking on "sort icon" in grid

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/icons/icons.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-tree-grid.less

XP-734 The manual sort icon is missing

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TinyMCE.ts

-disabling tinymce sticky toolbar in live edit

XP-736 Error updating TinyMCE toolbar offset when used in Part config

---

modules/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/Shader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

- also turned off debug in Shader.ts

XP-551 Image cropping - Implement zooming

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

- also fixed focus point double normalization on save

XP-554 Image cropping - Implement panning

---

modules/web-api/src/main/java/com/enonic/xp/web/HttpHeaders.java
modules/web-api/src/test/java/com/enonic/xp/web/HttpHeadersTest.java

-[Added]. Implemented TODO methods. Created tests for them.

XP-753 Implement HttpHeaders methods

---

modules/web-api/src/main/java/com/enonic/xp/web/HttpHeaders.java
modules/web-api/src/main/java/com/enonic/xp/web/WebRequest.java
modules/web-api/src/test/java/com/enonic/xp/web/HttpHeadersTest.java
modules/web-api/src/test/java/com/enonic/xp/web/WebRequestTest.java

- [Added] added implementations for WebRequest methods and tests for them.
- [Modified] HttpHeaders methods to check for null values and added tests for that.

XP-754 Implement WebRequest methods

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TinyMCE.ts

-workaround for chrome that scrolls back if scroll event triggered immediately after adding tinymce occurence

XP-635 TinyMCE - unexpected scrolling of content manager form

---

modules/portal-api/src/main/java/com/enonic/xp/portal/PortalResponse.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/controller/PortalResponseSerializerTest.java

- [Added] options block to Portal response
- [Added] test to PortalResponseSerializer test

XP-765 Implement options block for PortalResponse

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/ContentWizardActions.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/action/UserItemWizardActions.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/MaskWizardPanelEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardActions.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-panel.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/inputtype/imageupload/image.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/mask.less

- also refactored WizardActions and added suspendActions() method to base class to be able to suspend them

XP-727 Image Cropping - Fixup inline wizard modal effect

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/uploader/Uploader.ts

XP-795 Image Uploader - Add image placeholder for nicer loading

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less

XP-801 Publishing Wizard - Misc fixes of the dependencies list

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/relationship/ContentSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/tag/Tag.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfigurator.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/InputView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/InputValidationRecording.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/combobox/ComboBox.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/support/BaseInputTypeManagingAdd.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/inputtype/ContentTypeFilter.ts

* Refactored ContentSelector, ImageSelector, ContentTypeFilter, Tag and SiteConfigurator classes by moving 'validate' method and common properties into the base class

XP-825 content with type 'Image Selector', wrong validation message

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/relationship/ContentSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/data/PropertyArray.ts

* Check for existing values in ContentSelector

XP-882 Wizard - ContentSelector is buggy

---

modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/url/PortalUrlServiceImpl_processHtmlTest.java

- Fixed assert argument to correspond to service call result

XP-906 Fix @Ignore tests: PortalUrlServiceImpl_processHtmlTest

---

modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/DeleteSnapshotsCommand.java
modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/DeleteSnapshotsJsonRequest.java

XP-912 Implement DeleteSnapshotCommand in Java

---

modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/SnapshotCommand.java
modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/SnapshotJsonRequest.java

XP-916 Implement SnapshotCommand in Java

---

modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/ImportCommand.java
modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/ImportJsonRequest.java

XP-917 Implement ImportCommand in Java

---

modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/RestoreCommand.java
modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/RestoreSnapshotJsonRequest.java

XP-915 Implement RestoreCommand in Java

---

modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/ReindexCommand.java
modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/ReindexJsonRequest.java

XP-914 Implement ReindexCommand in Java

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/export/ExportNodesRequestJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/export/ExportResource.java

XP-935 Rename importWithIds in ExportResource

---

modules/distro/src/tools/export.sh
modules/toolbox/src/main/java/com/enonic/xp/toolbox/repo/ExportCommand.java

XP-918 Implement ExportCommand in Java

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/repo/SystemDumpResource.java
modules/core-api/src/main/java/com/enonic/xp/export/ExportNodesParams.java
modules/core-api/src/test/java/com/enonic/xp/export/ExportNodesParamsTest.java
modules/core-export/src/main/java/com/enonic/xp/core/impl/export/ExportServiceImpl.java
modules/core-export/src/main/java/com/enonic/xp/core/impl/export/NodeExporter.java
modules/core-export/src/main/java/com/enonic/xp/core/impl/export/writer/FileExportWriter.java
modules/core-export/src/test/java/com/enonic/xp/core/impl/export/NodeExporterTest.java

Merge of XP-865 & XP-889 in 5.3.0

XP-889 Move version-file to dump root-folder

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

-Updated viewport to drag bottom border with rest of page

XP-897 Image cropping - Fix height resizer

---

modules/toolbox/src/test/java/com/enonic/xp/toolbox/repo/DeleteSnapshotsCommandTest.java
modules/toolbox/src/test/java/com/enonic/xp/toolbox/repo/DumpCommandTest.java
modules/toolbox/src/test/java/com/enonic/xp/toolbox/repo/ExportCommandTest.java
modules/toolbox/src/test/java/com/enonic/xp/toolbox/repo/ImportCommandTest.java
modules/toolbox/src/test/java/com/enonic/xp/toolbox/repo/ReindexCommandTest.java
modules/toolbox/src/test/java/com/enonic/xp/toolbox/repo/RestoreCommandTest.java

XP-937 Create tests for tool commands

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

* Fixed things lost during the merge
* Fixed position of the toolbar for a cropped image
* Added highlighting of Focus/Crop buttons if image has been focused or cropped
* Cleanup

XP-866 Image Editing - Change styling of the toolbar

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

-Now when clicking reset rather in crop of focus edit mode - edit mode is closed

XP-922 Image Editor - Change behaviour of the Reset button

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/Input.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/InputView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/json/InputJson.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/input-common.less

- Added support for Maximize property that makes input take whole width and puts its label above it

XP-880 Wizard - Add support for maximizing input widget size

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less

- Adjusted publish dialog to disable publish button when there is a invalid item among the resolved items. Note, that if there are invalid children items - publish button will not be disable until children items get resolved.

XP-964 Disable publish button when there is invalid content

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishItem.ts

- I made publish dialog to use up to 15 initially selected items to render kind of publish preview. While items are resolved - publish button is disabled and subheader message shows appropriate label.

XP-955 Publishing Wizard - Instantly display the selected items

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishContentResultJson.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/publish_content_deleted.json
modules/admin-ui/src/main/resources/web/admin/common/js/content/PublishContentRequest.ts
modules/core-api/src/main/java/com/enonic/xp/content/PushContentsResult.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/PushContentCommand.java

- Adjusted push process to pass back content names for deleted contents for consistency with other pushed contents.

XP-966 Notification for publish of deleted item uses content's id

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less

- Made dependencies list to be shown by default with appropriate label
- Removed hide/show dependencies toggle

XP-954 Publishing Wizard - Show all dependencies by default

---

modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/browse/UserItemsTreeGrid.ts

- Added handling of dblclick event
- Moved some initialization to separate methods from constructor

XP-1008 User App: double click on User or Role does not  open wizards

---

modules/core-api/src/test/java/com/enonic/xp/schema/content/validator/OccurrenceValidatorTest.java

XP-777 Standardize our builder creators in core-api

---

modules/core-api/src/main/java/com/enonic/xp/app/ApplicationRelativeResolver.java
modules/core-api/src/main/java/com/enonic/xp/form/inputtype/ContentSelectorConfigXmlSerializer.java
modules/core-api/src/main/java/com/enonic/xp/form/inputtype/ImageSelectorConfigXmlSerializer.java
modules/core-api/src/main/java/com/enonic/xp/xml/parser/XmlFormMapper.java
modules/core-api/src/test/java/com/enonic/xp/app/ApplicationRelativeResolverTest.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/site/XmlSiteParser.java
modules/core-schema/src/main/java/com/enonic/xp/core/impl/schema/content/XmlContentTypeParser.java
modules/core-schema/src/main/java/com/enonic/xp/core/impl/schema/relationship/XmlRelationshipTypeParser.java

- Rename ModuleRelativeResolver to ApplicationRelativeResolver
- Move com.enonic.xp.module.ApplicationRelativeResolver to com.enonic.xp.app.ApplicationRelativeResolver

XP-998 Rename ModuleRelativeResolver to ApplicationRelativeResolver

---

modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/applauncher/Applications.ts

Updated the app name from "Modules" to "Applications".

XP-1005 Rename Module-Manager title to Applications

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageHelperImpl.java
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageInspectionPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/core-api/src/main/java/com/enonic/xp/content/ContentPropertyNames.java
modules/core-api/src/main/java/com/enonic/xp/content/Media.java
modules/core-api/src/main/java/com/enonic/xp/image/Cropping.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/ImageRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/image/ImageHandleResource.java

- fixed missing import in PageInspectionPanel.ts
- added zoom to content's crop data
- changed Cropping.java fields from int to double because these are percents of the original image in 0..1 interval
- added scale param to ImageRenderer.java because it would throw an exception when rendering an image part otherwise
- updated sub image calculations in ImageHandleResource.java and ContentImageHelperImpl.java

XP-1076 Image Cropping - Use mask in all image services

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

- fixed reset button behavior
- updated buttons style

XP-1098 Image Editing - Add Reset button

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

Contains XP-1099 commits, so merge that one first.

XP-1100 Image Editing - Remove zooming with mouse wheel in Image cropping

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardToolbar.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardToolbarPublishControls.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-steps-panel.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- Added publish controls to the menu with status value and publish button
- Adjusted styling for mobile publish button as well to fix some css mistakes

XP-1114 Publish button - Add item state and Publish button to the menu

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

- switched Dropdown with TabMenu

XP-1099 Image Editing - Add sticky toolbar and selector of edit mode

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindow.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindowController.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindowToggler.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- Removed automatic mode for context window.
- Removed redundant calls and methods

XP-1104 Branch: Context window state fixup

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/button.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/uploader.less

- also added button.transparent class to have it looking like a link

XP-1103 Image Editing - Move controls to the toolbar

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- Changed color of disabled publish button in the edit mode
- Changed label of publish button in publish wizard

XP-1135 Publish button - Small fixes

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

- changed focal point storing mode to percents of the crop area instead of the percents of the original image

XP-1134 Image Editing - Wrong values in focal point

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardToolbar.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/button/CycleButton.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabBar.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/cycle-button.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

Implemented the collapsible button and navigation.
Fixed the navigation panel when it become sticky.
Updated the CycleButton implementation and styles.

XP-1101 Branch: Split Panel fixups

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemStatisticsPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemVersionsPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/widget/Widget.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/widget/WidgetsPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/widget/widgets.less

- Removed tab dropdown from ContentItemStatisticsPanel and changed its parent
- Made Version history a widget
- Adjusted styling of Widgets

XP-1090 Wigdet Panel - Add version history widget

---

modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/repo/IndexResourceTest.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/reindex.json
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/reindex_params.json

Implemented IndexResource test.

XP-1150 Create test for IndexResource

---

modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/repo/SnapshotResourceTest.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/delete.json
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/delete_params.json
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/list.json
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/restore.json
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/restore_params.json
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/snapshot.json
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/repo/snapshot_params.json

Implemented SnapshotResource tests.

XP-1151 Create test for SnapshotResource

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/widget/WidgetDescriptorResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/widget/json/WidgetDescriptorsJson.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/widget/WidgetDescriptorResourceTest.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/widget/get_widgets_by_interface.json
modules/core-api/src/main/java/com/enonic/xp/widget/WidgetDescriptors.java

- Added WidgetDescriptorResource  that serves rest requests
- Added getByInterface() method that accepts "interface" param
- Added test

XP-1051 Widget panel - Rest service - Widget Descriptor by interface

---

modules/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowsePanel.ts

-Currently it's shown by default. Making it hidden.

XP-1186 Content Manager search view must be hidden as default

---

modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/applauncher/Applications.ts
modules/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityInitializer.java

- Renamed User Manager app
- Renamed User Manager roles (for this change to take effect, repo has to be cleaned or updated manually)

XP-1222 User Manager Application - Rename to Users

---

modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- Removed bg color for minimize button, though on hover it will appear

XP-1239 Remove background color from the "hide wizard panel" button

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/filter/ContentBrowseFilterPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/browse/filter/BrowseFilterPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/browse/browse-filter-panel.less

- Adjusted filter input styling
- Changed label for empty filter value

XP-1232 Search Panel adjustments

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- Made disabled mode grey (both in edit mode, and in wizard)
- In edit mode, moved button closer to menu icon
- In edit mode, adjusted size of the publish button

XP-1233 Adjustments to "publish" button

---

modules/admin-ui/src/main/resources/web/admin/common/js/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/radiobutton/RadioButton.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/radiobutton/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/radiobuttons/_module.ts
modules/core-api/src/main/java/com/enonic/xp/inputtype/InputTypeName.java
modules/core-api/src/main/java/com/enonic/xp/inputtype/InputTypes.java
modules/core-api/src/main/java/com/enonic/xp/inputtype/RadioButtonType.java
modules/core-api/src/test/java/com/enonic/xp/inputtype/RadioButtonTypeTest.java
modules/core-api/src/test/resources/com/enonic/xp/form/form-with-all-input-types.xml
modules/core-impl/src/test/resources/com/enonic/xp/core/impl/schema/content/serializer/ContentTypeJsonSerializerTest-contentType-allInputTypes.json

- Renamed radiobuttons to radiobutton

XP-1252 Rename RadioButtons input-type to RadioButton

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less

- Added check if publish dialog extends available window height
- Slightly adjusted max-height value

XP-1251 Publish Wizard - Modal window does not position properly

---

modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/view/LocalizeFunction.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/view/LocalizeParams.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/view/LocalizeParamsTest.java

- Moved LocalizeParams into portal-impl (com.enonic.xp.portal.impl.view) as a package protected class.

XP-1292 Move LocalizeParams into portal-impl

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts

Updated SplitPanel size calculation method to consider the hidden status.

XP-1305 Content preview is not completely hidden in mobile mode

---

modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/ActivatedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/Navigator.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/panel/NavigatedPanelStrip.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/panel/PanelStrip.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabBar.ts

Update the navigation handling.

XP-1262 Content Wizard Panel Collapsing - Prevent unnecessary scrolling

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/widget/WidgetsPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Added separate panel for mobile preview with widgets panel

XP-1092 Widget Panel - Add support for detail panel in mobile mode

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

* Fixed top border being covered by the toolbar
* Added padding around zoom control

XP-1357 Add padding to the zoom control in Image cropping mode

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/_module.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemStatisticsPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/WidgetView.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/_module.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/widget/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/widget/widgets.less

- Renamed WidgetPane, WidgetToggleButton and WidgetContainer

XP-1338 Detail panel - Rename WidgetPanel to DetailPanel

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-view.less

* Fixed UI in SiteConfigurator
* Renamed "Clear contents" to "Reset" in LiveEdit context menu

XP-1364 SiteConfigurator - Fix UI when there are no options

---

modules/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/ApplicationTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsView.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindow.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentAddedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentLoadedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentRemovedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/DragAndDrop.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemViewAddedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemViewDeselectedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemViewSelectedEvent.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/context-window.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/page-components-view.less
modules/admin-ui/src/main/resources/web/admin/live-edit/js/LiveEditPage.ts

- implemented add/move/update/remove listeners
- implemented expanded node rendering for tree grid
- fixed node fetching when id of node has changed
- turned off debug for ImageEditor

XP-1137 Page Component View - Add interaction between the view and LiveEdit Context panel

---

modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts

* Moved removal of pageview listener

XP-1378 Live Edit - Error removing component

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindow.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

Disabled the wizard toggle animation.

XP-1396 Live Edit - problems with detecting when to "fix" context panel

---

modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemViewContextMenu.ts

XP-1452 LiveEdit - Wrong vertical positioning of context menu

---

modules/core-api/src/main/java/com/enonic/xp/convert/Converters.java
modules/core-api/src/test/java/com/enonic/xp/convert/BooleanConverterTest.java
modules/core-api/src/test/java/com/enonic/xp/convert/ContentIdConverterTest.java
modules/core-api/src/test/java/com/enonic/xp/convert/ContentPathConverterTest.java
modules/core-api/src/test/java/com/enonic/xp/convert/NumberConverterTest.java
modules/core-api/src/test/java/com/enonic/xp/convert/ResourceKeyConverterTest.java
modules/core-api/src/test/java/com/enonic/xp/convert/StringConverterTest.java
modules/core-mail/build.gradle
modules/core-mail/src/main/java/com/enonic/xp/mail/impl/MailConfigurator.java
modules/core-mail/src/main/java/com/enonic/xp/mail/impl/MailServiceImpl.java
modules/core-mail/src/test/java/com/enonic/xp/mail/impl/MailServiceImplTest.java
modules/distro/src/home/config/com.enonic.xp.mail.cfg

- Implemented session creation

XP-1414 Implement MailServiceImpl with configuration

---

modules/core-api/build.gradle
modules/distro/src/system/bundles.xml
modules/launcher/build.gradle
modules/launcher/src/main/resources/META-INF/config/system.properties

XP-1402 Upgrade to use OSGi R6 specification

---

modules/admin-impl/build.gradle
modules/core-api/build.gradle
modules/core-image/build.gradle
modules/core-repo/build.gradle
modules/distro/src/system/bundles.xml
modules/portal-impl/build.gradle
modules/repack-attoparser/build.gradle
modules/repack-elasticsearch/build.gradle
modules/repack-elasticsearch/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
modules/repack-elasticsearch/src/main/resources/META-INF/services/org.apache.lucene.codecs.DocValuesFormat
modules/repack-elasticsearch/src/main/resources/META-INF/services/org.apache.lucene.codecs.PostingsFormat
modules/repack-jhlabs-filters/build.gradle
modules/repack-jmustache/build.gradle
modules/repack-jparsec/build.gradle
modules/repack-resteasy/build.gradle
modules/web-jaxrs/build.gradle
settings.gradle

XP-1495 Move repack osgi libraries to xp project

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

Depends on XP-1465 so merge it first

XP-1472 Image Editor - Apply changes and close edit mode by clicking the mask

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/page-components-view.less

Fixed the grid layout and scroll display;
Updated the `TreeGrid.scrollToRow()` method, made scrollable element changeable .

XP-1475 Component View - Scroll the view after navigating up and down

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/browse/browse-filter-panel.less

- Indent result count: added indent
- Indent facet headers: added indent
- Reduce size of facet fonts + add more padding: reduced size of facet headers font from 15px to 14px, did not reduce size of facet font as 12px seem to be correct, added 1px top and bottom padding for facets
- Make facet lists "grey" when not selected, and black when selected: added gray color for unchecked facets
- Reduce font size for "clear": reduced size from 16px to 14px
- Adjust alignment between facet font and checkbox (should be vertically centered): set 2px to top attribute of label:before selector
- Added more space after hits and clear button div

XP-1488 Content Manager - Tuning design of Search Panel

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/field-set-view.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/dropdown/dropdown.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/context-window.less

Updated `context-window` styles;
Fixed the dropbox width and box model.

XP-1518 LiveEdit InspectionsPanel - Fix padding

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar-tab-menu.less

Changed tab border radius from 7px to 5px.

XP-1542 Tab Adjustments - harder corners

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-view.less

-Fixed vertical centralizing of a modal dialog

XP-1535 Site App configuration - Move editing panel into modal window

---

modules/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/home/HomeMainContainer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/LazyImage.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/lazy-image.less
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less
modules/admin-ui/src/main/resources/web/admin/common/styles/styles.less

Added LazyImage to launcher background.

XP-1519 Admin UI - Improve loading of background image

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/page-components-view.less

- updated coloring according to task description

XP-1583 PCV - Fixing the menu icon coloring

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/content-wizard-toolbar.less
modules/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-view.less

Fixed the colors on screen button;
Fixed the underline style on remove button of `ContentWIzard`.

XP-1543 Live Edit Toggle button - Replace current "icon" with "screen"

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/uploader/Uploader.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/content/image-uploader.less

- added pulsating bubble on drag

XP-869 Image editor - Add drag'n'drop support for uploading images

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar-tab-menu.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/liveedit/item-view-context-menu.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/menu/action-menu.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/menu/context-menu.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/tab/tab-menu.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/time/date-picker.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/time/date-time-picker.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/time/time-picker.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/page-components-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/shadows.less
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/_module.less
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/page-view.less

Added `shadows.less` with predefined shadow classes.
Replaced simple box shadow from layers with material shadow.

XP-1537 Toolbar Overflow menu - Use white background color

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

- pop image at the same position
- added scrolling in edit mode

XP-1464 Image Editor - Stick toolbar to top of the screen (in edit mode)

---

modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Made back-button arrow to pint to left. 
- Sped-up the animation.

XP-1533 Detail Panel - In mobile mode - Arrow pointing wrong way

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ContentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/Action.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/menu/TreeContextMenu.ts

* Implemented sortOrder field in Action class to control order of action items
* Added sorting of actions by sortOrder field when rendering context menu
* Moved creation of "Select parent" action into ItemView class
* Changed "Select parent" action to always be the first action in the context menu

XP-1554 Live Edit context menu - Implement order of menu items

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/details/details.less

- Added details panel toggle button for large screens
- Made details panel for large screens to slideout smoothly
- Removed padding for widget selector

XP-1540 Detail Panel - blind spot for detail panel at 1920px

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/details/details.less

- Adjusted styling of the toggle button for large screens to align it with other screens behavior
- For large screens made details panel to show upon size change only if there is a selected content

XP-1585 Detail Panel - Icon tuning

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

- also fixed mouse up outside focus area closing edit mode

XP-1638 Image editor - Autofocus doesn't work properly after canvas resize

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/PublishAction.ts

-update to make saving of content correctly handled on frontend when pressing Publish

XP-1633 Publish button should be enabled without saving

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts

- Removed redundant entries left after merge

XP-1671 Detail panel - Final adjustments

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/details/details.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Made toggle button always enabled
- Added no-selection handling
- Hidden empty icon spans of version history grid
- Adjusted padding of info widget button
- Made 'close' details icon for mobile view balck (instead of blue)

XP-1693 Detail panel - Enable when no content selected

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-view.less

- Validation is already there hence only made siteview to correctly update parent form state on validity change
- Appropriate color added for broken site view

XP-1567 Site App configuration - Implement validation

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts

- Unbounded resize events from removed html areas

XP-1711 SiteConfig modal window - Errors in console

---

modules/admin/admin-event/src/main/java/com/enonic/xp/admin/event/impl/EventHandler.java
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/ServerEventsConnection.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentVersion.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/GetActiveContentVersionsRequest.ts

- changed web socket idle timeout from 1 minute to 8 hours
- added logging to ServerEventsConnection
- also removed console logs from ContentVersion and GetActiveContentVersionsRequest

XP-928 The grid in the Browse panel not refresed, when content deleted

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfigurator.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteView.ts

- Disabled auto open of dialog upon site config selection
- Enabled validation upon site config selection

XP-1749 Site Config - Problems handling multiple site configurations

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/ShowFormAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/ShowLiveEditAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/main.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/Action.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/Button.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/CycleButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/TogglerButton.ts

* Implemented tooltip on TogglerButton
* Implemented tooltip on CycleButton based on action context
* Changed icons for the toolbar buttons

XP-1792 Feature Request: Tooltip for all the new icons in Admin

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentRequiresSaveEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/upload/FileUploader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/file-uploader.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less

- Adjusted functionality to replace existing attachment via replacing it with a file of same extension
- Added content save() call upon file uploaded
- Adjusted styling

XP-1727 BUG: Can't Edit files in Content Manager

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

- fixed panning was limited by original image size, instead of the cropped area
- fixed the focus to stay 0.25 of the smallest cropped side
- fixed focus position to stay inside cropped area

XP-1778 Focal point values out of range after cropping

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/details/details.less

- Adjusted version history grid width calculation
- Changed css class name and height of non-mobile details toggle button
- Adjusted status cell position to make it always float right

XP-1811 Version history - Floating issue with right padding

---

modules/admin/admin-ui/grunt/ts.js
modules/admin/admin-ui/package.json
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/create/NewContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/SaveBeforeCloseDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/ReorderChildContentsJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/ElementHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/lib/jquery.d.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/lib/jqueryui.d.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/DragAndDrop.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/query/FulltextSearchExpression.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/query/expr/FunctionExpr.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/Grid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/dropdown/SelectedOptionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/text/FileInput.ts
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/js/jquery.d.ts
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/js/jqueryui.d.ts

Updated the version of packages.
Fixed the typescript ('strict mode') errors and warnings in files.
Updated the TypeScript version.
Updated jQuery*.d.ts files.
Fixed the compiling errors.

XP-1812 Upgrade to TypeScript 1.6.2

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentInspectedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageInspectedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/image/ImageComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/part/PartComponentView.ts

-Added 'Inspect' button to the context menu for Components (except Text) and Page

XP-1793 Add "Settings" button to context menu

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/page/PageModel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/ElementHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/js/main.ts

- added check for duplicate jQuery.ready(document) events in main.ts
- fixed NPE in PageModel.getPage
- fixed NPE in ElementHelper.getData
- removed unnecessary setParentElement from PageView

XP-1855 LiveEdit - Error when opening Superhero for edit in XP admin

---

modules/core/core-api/src/main/java/com/enonic/xp/event/Event2.java
modules/core/core-api/src/test/java/com/enonic/xp/event/Event2Test.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/NodeEvents.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/AbstractNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/CreateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/CreateRootNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/MoveNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/NodeEventsTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/AccessControlTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/ApplyNodePermissionsCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/CheckNodeExistsCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/CompareNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/CreateRootNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/FindNodesByParentCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/FindNodesWithVersionDifferenceCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/GetNodesByIsCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/ImportNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/MoveNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/NodeChildOrderResolverTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/NodeServiceImplTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/PushNodesCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/RenameNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/ResolveSyncWorkCommandTest.java
modules/core/core-security/src/test/java/com/enonic/xp/core/impl/security/SecurityServiceImplTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/AbstractContentServiceTest.java

- Created NodeEvents class with static method
- Added test for it
- Adjusted Service and Test classes to manage addition of event publisher to NodeServiceImpl

XP-1853 Fire moved event from node layer

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGridToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-browse-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less

Update toolbar and dropdown styling.

XP-1861 Fix layout of "More" and "Actions" fold buttons

---

modules/core/core-api/src/main/java/com/enonic/xp/site/SiteDescriptor.java
modules/core/core-api/src/main/java/com/enonic/xp/site/filter/FilterDescriptor.java
modules/core/core-api/src/main/java/com/enonic/xp/site/filter/FilterDescriptors.java
modules/core/core-api/src/main/java/com/enonic/xp/site/filter/FilterType.java
modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/XmlSiteParser.java
modules/core/core-api/src/main/resources/META-INF/xsd/model.xsd
modules/core/core-api/src/test/java/com/enonic/xp/xml/parser/XmlSiteParserTest.java
modules/core/core-api/src/test/resources/com/enonic/xp/xml/parser/XmlSiteParserTest-serialized-site.xml
modules/core/core-impl/src/test/java/com/enonic/xp/core/impl/site/SiteDescriptorBuilderTest.java
modules/core/core-impl/src/test/resources/com/enonic/xp/core/impl/site/SiteDescriptorBuilderTest-site.xml

- Added descriptors and adjusted tests

XP-1892 Add FilterDescriptors to site.xml

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts

XP-1833 Details Panel is empty, when content have been selected and published

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/PortalError.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/mapper/PortalErrorMapper.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/mapper/PortalErrorMapperTest.java
modules/portal/portal-impl/src/test/resources/com/enonic/xp/portal/impl/mapper/PortalErrorMapperTest-simple.json

Implemented `PortalError` and `PortalErrorMapper` classes and tests.

XP-1898 Implement PortalError and PortalErrorMapper

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-header-with-display-name-and-name.less

* Removed refresh of the page component tree after renaming of content

XP-1845 Component View - Fix presentation of page in tree

---

modules/admin/admin-api/src/main/java/com/enonic/xp/admin/widget/WidgetDescriptor.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/widget/WidgetDescriptorResource.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/widget/WidgetDescriptorResourceTest.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/widget/XmlWidgetDescriptorParserTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/widget/get_widgets_by_interface.json
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/WidgetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/GetWidgetsByInterfaceRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/Widget.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/WidgetDescriptorResourceRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/WidgetDescriptorJson.ts

- Changed request paths for both front and back ends
- Changed resource returned json format and apporpriate .ts handler classes

XP-1920 Refactor WidgetDescriptorResource rest service

---

modules/core/core-api/src/main/java/com/enonic/xp/site/filter/FilterDescriptor.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/filter/FilterChainResolver.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/filter/FilterChainResolverTest.java

XP-1893 Implement FilterChainResolver in portal-impl

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/WidgetHandler.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/WidgetHandlerWorker.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/portal/WidgetHandlerTest.java
modules/portal/portal-api/src/main/java/com/enonic/xp/portal/RenderMode.java
modules/portal/portal-api/src/main/java/com/enonic/xp/portal/handler/ControllerHandlerWorker.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/render/RenderHandlerWorker.java

- Added WidgetHandler and WidgetHandlerWorker classes with appropriate tests
- Added RenderMode.ADMIN
- Moved abstract PortalHandlerWorker to Portal-Api
Note, I did not implement XxxUrlParams, XxxUrlFunction and XxxUrlHandler classes as they seem to be out of scope of this task.

XP-1919 Implement widget endpoint for portal

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveEditPageProxy.ts

- refactored load mask operation in LiveEditPageProxy

XP-1960 Incorrect appearence of Spinner , when site-wizard was opened

---

modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/ImageRendererTest.java

Implemented test for ImageRenderer.

XP-1979 Implement unit test for ImageRenderer

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/DeleteContentResultJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/delete_content_both.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/delete_content_failure.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/delete_content_success.json
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ResolvedPublishContentViewer.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/DeleteAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/UserAppPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatusViewer.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryViewer.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentUnnamed.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/DeleteContentResult.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/DeleteContentResultJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/NamesAndIconViewer.ts

Added content type name into the delete response.

XP-1949 Fix delete confirmation message for unnamed content

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts

XP-2007 Detail panel - Missing display name for unnamed content

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/PrincipalMapper.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/PrincipalMapperTest.java
modules/lib/lib-content/build.gradle
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/mapper/PrincipalsResultMapper.java
modules/lib/lib-content/src/test/java/com/enonic/xp/lib/content/mapper/PrincipalsResultMapperTest.java
modules/lib/lib-content/src/test/resources/com/enonic/xp/lib/content/mapper/PrincipalsResultMapperTest-groupPrincipals.json
modules/lib/lib-content/src/test/resources/com/enonic/xp/lib/content/mapper/PrincipalsResultMapperTest-rolePrincipals.json
modules/lib/lib-content/src/test/resources/com/enonic/xp/lib/content/mapper/PrincipalsResultMapperTest-userPrincipals.json

- Created mapper
- Added tests
- Added gradle dependency to access lib-auth from lib-content

XP-1971 Implement PrincipalsResultMapper

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/GetPrincipalHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/GetPrincipalHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/PrincipalMapperTest.java
modules/lib/lib-auth/src/test/resources/site/test/getPrincipal-test.js

- Added GetPrincipalHandler with appropriate function and tests

XP-1972 Implement getPrincipal in lib-auth

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/GetMembershipsHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/ChangePasswordHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/GetMembershipsHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/GetPrincipalHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/GetUserHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/HandlerTestHelper.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/HasRoleHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/LoginHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/LogoutHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/PrincipalMapperTest.java
modules/lib/lib-auth/src/test/resources/site/test/getMemberships-test.js

- Implemented function and added/adjusted tests

XP-1973 Implement getMemberships in lib-auth

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichSelectedOptionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/content-combo-box.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less

Added pencil icon near the content to open in new tab for edit.

XP-2013 Content selector - Add icon to open selected content for edit

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/WidgetsSelectionRow.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/details/details.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- In order to align styles of the InfoWidget toggle button and the rest of widget selection row controls, I moved InfoWidget toggle button to the DropdownHandle.
- Adjusted styling.

XP-2050 Detail panel - UI adjustments of the widget dropdown

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/CreateGroupHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/CreateGroupHandlerTest.java
modules/lib/lib-auth/src/test/resources/site/test/createGroup-test.js

- Implemented createGroup with tests

XP-1923 implement createGroup in lib-auth

---

modules/core/core-api/src/main/java/com/enonic/xp/security/EditableUser.java
modules/core/core-api/src/main/java/com/enonic/xp/security/UpdateUserParams.java
modules/core/core-api/src/main/java/com/enonic/xp/security/UserEditor.java
modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/ModifyUserHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/ModifyUserHandlerTest.java
modules/lib/lib-auth/src/test/resources/site/test/createGroup-test.js
modules/lib/lib-auth/src/test/resources/site/test/createUser-test.js
modules/lib/lib-auth/src/test/resources/site/test/modifyUser-test.js

- Implemented modify user function
- UserEditor and EditableUser classes created to adhere to editor pattern used in modify content handler
- Adjusted createGroup  and createUser functions to accept json params object as argument
- Added docs to auth.js functions

XP-1924 Implement modifyUser in lib auth

---

modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/PartRendererTest.java

XP-1981 Implement unit test for PartRenderer

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/AddMembershipsHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/AddMembershipsHandlerTest.java
modules/lib/lib-auth/src/test/resources/site/test/addMemberships-test.js

- Added function with appropriate tests

XP-1975 Implement addMemberships to lib-auth

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/RemoveMembershipsHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/RemoveMembershipsHandlerTest.java
modules/lib/lib-auth/src/test/resources/site/test/removeMemberships-test.js

- Added function with appropriate tests

XP-1976 Implement removeMemberships to lib-auth

---

modules/core/core-api/src/main/java/com/enonic/xp/security/EditableGroup.java
modules/core/core-api/src/main/java/com/enonic/xp/security/GroupEditor.java
modules/core/core-api/src/main/java/com/enonic/xp/security/UpdateGroupParams.java
modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/ModifyGroupHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/ModifyGroupHandlerTest.java
modules/lib/lib-auth/src/test/resources/site/test/modifyGroup-test.js

- Added function with appropriate tests

XP-2047 Implement modifyGroup in lib auth

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/LiveEditPageViewReadyEvent.ts

* Handle the case when LE page returns raw response

XP-2142 LiveEdit - Endless spinner when page template has raw content

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/remove/ContentDeleteDialog.ts

- Added spinner and disabled button while request is being performed for Publish and Delete dialogues

XP-2146 No mask or spinner in publish dialog on publish

---

modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/json/form/FormItemJsonTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/json/form/FormItemJsonTest-fieldSet.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/json/form/FormItemJsonTest-formItemSet.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/json/form/FormItemJsonTest-input.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/json/form/FormItemJsonTest-inputWithConfig.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/application/get_application_by_key_success.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/application/get_application_list_success.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/page/layout/get_by_applications_success.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/schema/content/ContentTypeResourceTest-get_contentType_with_all_formItem_types-result.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/schema/content/ContentTypeResourceTest-get_contentType_with_only_one_input-result.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/schema/content/ContentTypeResourceTest-list_one_contentType_with_only_one_input-result.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/schema/mixin/get_mixin.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/schema/mixin/list_mixins.json
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less
modules/core/core-api/src/main/java/com/enonic/xp/form/Input.java
modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/XmlFormMapper.java
modules/core/core-schema/src/main/java/com/enonic/xp/core/impl/schema/content/BuiltinContentTypeLoader.java

* Maximize input labels by default

XP-2074 Handle long input labels better (only first part is shown now)

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

Fixed the image init process in `ImageEditor`.

XP-2200 Error editing multiple images simultaneously

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/WidgetItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/WidgetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/LinkEl.ts

* Use native "load" event of widget document instead of custom event to get contents of widget body

XP-2273 Widget - Simplify deployment of a static widget

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentSelectorQueryJsonToContentQueryConverter.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentSelectorQueryJsonToContentQueryConverterTest.java

- Made QueryConverter to throw exception when resolving parent site to null
- Added and adjusted tests

XP-2187 Handle complicated path expressions in allowPath entry

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/SettingsWizardStepForm.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfigurator.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormItemOccurrenceView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormItemOccurrences.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormItemSetOccurrences.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/RemoveButtonClickedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/support/InputOccurrences.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts

- fixed SettingsWizardStepForm NPE
- removed unnecessary debuggers;

XP-2232 Make sure every BaseInputTypeManagingAdd descendant update its occurrences on update

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/Button.ts

-Issue related to https://youtrack.enonic.net/issue/XP-2314

XP-2339 Save Before Close dialog: html-tags displayed on buttons

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowseItem.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowseItemPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/action/ContentTreeGridActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemsChanges.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemsSelectionPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/actions/TreeGridActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/ArrayHelper.ts

Implemented changes saving in the `BrowsePanel`.
Added `ContentBrowseItem` object, that will store the permissions list to prevent unnecessary requests.

XP-2244 Improve handling of enabled actions in ContentTreeGrid

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserWizardPanel.ts

- Added call of notifyRename method on NewItemPersisted, which triggers Wizard's tab id rename

XP-2381 User App: New user selects already open user tab

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemsSelectionPanel.ts

Added update for the changed BrowseItems.

XP-2384 Toolbar not updated when applications are started or stopped

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/app-launcher/js/app/login/LoginForm.ts

-When pressing 'enter' : keyboard event was processed and also login button treated it as a click/submit event

XP-2398 Login request sent twice

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

-tooltip style was overriden by dropdown

XP-2392 FoldButton - Fix positioning and styling of the dropdown

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/details-panel.less

- Changed positioning of floating panel to fixed.

XP-2425 Extra detail panel shows up when tabbing through admin

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/ElementRegistry.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/RadioGroup.ts

Added unique name for the radio group representation.

XP-2442 Selection not shown for multiple RadioButtons inside item-set

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/Highlighter.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemViewContextMenu.ts

- also removed ItemView.getElementDimensions() in favor of Element.getEl().getDimensions()

XP-2467 Page Editor - Fix positioning of the context menu

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/url/PortalUrlServiceImpl.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/url/PortalUrlServiceImpl_processHtmlTest.java
modules/portal/portal-owasp/src/test/resources/com/enonic/xp/portal/owasp/impl/figure_tag.html
modules/portal/portal-owasp/src/test/resources/com/enonic/xp/portal/owasp/impl/figure_tag_sanitized.html

- Removed sanitizeHtml() call from processHtml

XP-2489 Remove sanitizeHtml from processHtml

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PagePlaceholder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/image/ImageComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutPlaceholder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/part/PartComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/part/PartPlaceholder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts

- Added check that will select clicked element
- Made liveEditModel field incapsulated

XP-2487 Select a new component view with one click

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSelectorQueryRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelectorLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/Grid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/loader/BaseLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/loader/event/LoadingDataEvent.ts

Added dynamic postLoad with ContentSelectorQueryRequest.
Added support for the postLoad to the loaders and rich comboBoxes.
Fixed the Grid scroll & scrolled events handling.

XP-2449 Combobox selector does not load more than 100 options

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/NonMobileDetailsPanelsManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/details-panel.less

* Enable vertical scrolling
* Auto-recalculate scroller height on detail panel resize

EXT-93 Content Viewer app: Not possible to scroll for large JSON

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/GroupWizardPanel.ts

- Made newly created group to be skipped in the dropdown loader after creation

XP-2516 Principal allowed to be added as a member of itself in admin

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/ApplicationBrowseActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/ApplicationBrowseToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/InstallApplicationAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/InstallAppDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/InstallAppPromptEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/main.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/module/install-application-dialog.less

XP-2579 App installation - "Install" menu link and modal dialog

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/htmlarea/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tiny/modal-dialog.less

* Fixed preview of existing image not being displayed in the "Add image" dialog
* Fixed parsing of image src with additional parameters

XP-2592 Error adding image in HtmlArea with keep original size

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelectorLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/loader/BaseLoader.ts

XP-2561 ImageSelector does not show image selected

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/ApplicationBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/ApplicationTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/InstallAppDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/main.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/ApplicationUploadStartedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/ApplicationUploaderEl.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/ProgressBar.ts

- Added uploading of selected file
- Adjusted progress bar due value calculation due to its normalizeValue method works incorrectly

XP-2580 App installation - Upload selected application file

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/DropdownGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/DropdownList.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBoxDropdown.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/loader/BaseLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/loader/event/LoadedDataEvent.ts

Fixed the selection loss on postLoad in RichComboBox.

XP-2627 ImageSelector: unselected items are not saved

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-steps-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/panel/split-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- also thrown errors when trying add children from SplitPanel
- refactored places where items where added to split panel manually
- moved mobile publish button styles from wizard steps to content wizard file

XP-2593 Wrong panel height in mobile resolution

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryPreLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/MoveContentSummaryLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelectorLoader.ts

Added preload custom implementation to all loaders, that load ContentSummary.

XP-2631 Link modals in HtmlArea do not show the value selected

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/AttachmentItem.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/AttachmentUploaderEl.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/attachment-item.less

nameView changed to link for AttacmentItem.

XP-2602 Improvements to AttachmentUploader input type

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/ContentItemPreviewPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/IFrameEl.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/UriHelper.ts

- Added frame click handler that parses the clicked link href attribute and then manages fires appropriate event

XP-2670 Content navigation - Select content before loading preview

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

- added grid active state notification
- updated grid columns when grid became active for the first time

XP-2653 Content Grid doesn't initially switch to Compact mode in low resolution

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

- also fixed the upscaled image rendering to be the same both in svg and html

XP-2685 Image editor - Small images are no longer upscaled

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageResource.java
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentImageUrlResolver.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/htmlarea/ImageCroppingOption.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/htmlarea/ImageCroppingOptions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/htmlarea/ImageCroppingSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/htmlarea/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/UriHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tiny/modal-dialog.less

-Added scale param to image src to be processed on backend. Backend updated to handle it.
-In case 'keep original size' used - not setting size parameter in url to request original image

XP-2662 HTML Editor - Support scaling in the image preview

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/url/PortalUrlServiceImpl.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/url/UrlHelper.java

-Updated portal url handler to parse url params and set non-default scale params if needed

XP-2664 HTML Editor - Support image scaling when rendering in the portal

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/htmlarea/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tiny/modal-dialog.less

-Hiding vertical scrollbar with negative margin
-Scrolling controls are drawn as SVGs
-Small methods rearrangement for readability

XP-2800 HTML Editor - Implement scrolling controls in the Image dialog

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/ApplicationResource.java

XP-2820 Install App Dialog: Exception occurs, when wrong url typed

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/text-view.less

- On toolbar shown making page view position relative with 'top'=toolbar height to have space enough for toolbar
- Fixed right border of toolbar to be shown

XP-2793 Page Editor - Text edit mode toolbar

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/InputView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-configurator.less

- Removed old solution
- Made dialog class to parse form's input views for content and image selectors in order to manage their expanded event (just as in "Add image" dialog)

XP-2768 SiteConfig dialog - Dropdowns must overflow the dialog window

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/tinymce-editor.css

-Updated required styling + responsivity handling
-Also had to add cycle check for tinymce toolbar shown (to find out it's height) because it is being shown by tiny's internal code not immediately after setting edit mode to true

XP-2868 Page Editor - HTML editor toolbar - Dynamically wrap buttons

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ThumbnailUploaderEl.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/thumbnail-uploader-el.less

-added svg to allowed types for upload
-added text-align: center so svg image is centered in container

XP-2892 Thumbnail Uploader - Allow SVG

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/data/ValueTypeLocalDate.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/data/ValueTypeLocalDateTime.ts

- Fixed incorrect equals comparison

XP-2939 Fix validation problem that occured because of XP-2925

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/AllContentVersionsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/widget-view.less
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java

-Also fixed issue in ContentVersionFactory that made displayName returned like "displayName: displayName: XXXXX"

XP-2963 Version History - Expand div on click to show version info

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/SetActiveVersionJson.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/AllContentVersionsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/SetActiveContentVersionRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/event/ActiveContentVersionSetEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/event/_module.ts

- adjusted ContentResource.setActiveVersion
- added SetActiveContentVersionRequest
- added ActiveContentVersionSetEvent
- updated ContentWizardPanel form when active version is set
- used draft branch active version to display on UI

XP-3000 Version History - Set active version

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/AllContentVersionsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/widget-view.less

XP-2964 Version History - Add Restore button to enable version rollback

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetView.ts

- Fixed issue with dynamic height

XP-3049 Version Panel not scrolled, when history item was extended

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/button/MobileDetailsPanelToggleButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Added method that calculates and sets top offset for details panel based on header height
- Fixed problem with incorrect state of details toggle button

XP-2473 Content preview - Long content name overlaps widget selector

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/ApplicationResource.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/view/MarketAppsTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/ApplicationCache.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/ApplicationEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/module/install-application-dialog.less
modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationService.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/event/ApplicationEvents.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/event/ApplicationInvalidatorListener.java
modules/web/web-jetty/src/test/java/com/enonic/xp/web/jetty/impl/configurator/RequestLogConfiguratorTest.java

- replaced spinner with api.ui.ProgressBar
- moved app loading to ApplicationService from ApplicationResource
- generated load progress events
- updated progress bar with values from these events
- also fixed RequestLogConfiguratorTest

XP-3033 Install Application dialog - Replace spinner with progress bar

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/radiobutton/RadioButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/time/Date.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/time/Time.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/geo/GeoPoint.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePickerPopup.ts

XP-3067 Date: Content data not refreshed in the wizard after version rollback
XP-3069 GeoPoint: Content data not refreshed in the wizard after version rollback
XP-3068 Time: Content data not refreshed in the wizard after version rollback
XP-3073 RadioButton: Content data not refreshed in the wizard after version rollback
XP-3072 HtmlArea: Content data not refreshed in the wizard after version rollback
These will follow later:
XP-3071 ContentSelector: Content data not refreshed in the wizard after version rollback
XP-3070 ImageSelector: Content data not refreshed in the wizard after version rollback

XP-3063 Child tasks

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-configurator.less

- Added same handling for regular combobox selectors as it is made for image  and content selectors in SiteConfiguratorDialog.

XP-3082 ComboBoxes inside small app/site settings not displayed fully

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/PrincipalWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserEmailWizardStepForm.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/text/EmailInput.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/text/email-input.less

- Adjusted validation for user email input - fixed problem with 'Available' status

XP-3180 User Wizard - Error about invalid email on save

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/NewContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/text/FileInput.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/uploader/UploaderEl.ts

- hidden reset and cancel buttons for FileInput and NewContentDialog's MediaUploader
- also fixed reference to config in UploaderEl

XP-3185 Upload button broken in New content dialog

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/schema/content/inputtype/ContentTypeFilter.ts

- Added binded onContentTypesLoaded handler

XP-3186 Browser error selecting a page controller

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FieldSetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormView.ts

- Added layout listening to FormView so that we could subscribe on end of layout() call
- Subscribed Site config dialog to FormView layout event to ensure that comboboxes are rendered before we handle them
- Adjusted handleSelectorsDropdowns() method to check for FormItemViews of FieldSetView objects as well

XP-3127 SiteConfigurator dialog - Dropdown layer is misplaced

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/event/ContentServerChange.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/event/ContentServerEventsHandler.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts

- modified ContentServerChange to have content path and content id that come back from server
- used them both in ContentDeletedEvent
- also unbound ContentDeletedEvent listener in ImageSelector on remove

XP-3132 Exception in wizard when deleting content of type ImageSelector

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/filter/ContentBrowseFilterPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/filter/BrowseFilterPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/query/ContentQuery.ts

-Now handling situation when some content delete triggers  search panel refresh event and no result returned after

XP-3142 Empty grid appears, when all filtered content was removed

---

modules/admin/admin-ui/src/main/resources/admin/tools/launcher/launcher.html

single tab per every kind of app

XP-3157 Improved tab handling for admin tools

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/PageComponentsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts

- Added method that hides components view in mobile mode on certain actions
- Fixed focus on text component edit action

XP-2482 Auto-hide the Page Components view in mobile mode

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts

- returned back processing of image paths in text component

XP-3225 Text component - Wrong processing of image path

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/DeleteContentJson.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/DeleteContentAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/DeleteContentRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/delete/delete-dialog.less
modules/core/core-api/src/main/java/com/enonic/xp/content/DeleteContentParams.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeleteContentCommand.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/DeleteContentCommandTest.java

-Added param pendingDelete for delete request to enable deleting PENDING_DELETE content on backend

XP-3193 Instantly delete items with "Pending delete" status

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/PageComponentsGridDragHandler.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/PageComponentsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/BrowserHelper.ts

- Disabled d'n'd in page components for mobile platforms which does not work correctly - it might take a while to implement this feature for mobiles

XP-2480 Page Components view / Mobile - Drag'n'drop is not working

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/field-set-view.less

XP-3155 Minor visual bug: Fieldsets gets weird left margin on site.xml

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/InstallApplicationAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/InstallAppDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/InstallAppPromptEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/view/MarketAppPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/view/MarketAppsTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/main.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/ListMarketApplicationsRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/MarketApplication.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/MarketApplicationFetcher.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/MarketApplicationMetadata.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/MarketApplicationResponse.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/application/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

XP-3110 Market Apps Tree Grid - Add lazy loading

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/NamePrettyfier.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
modules/admin/admin-ui/src/main/resources/web/dev/test/common/index.html
modules/admin/admin-ui/src/main/resources/web/dev/test/common/js/NamePrettyfierTest.js

- Added name prettyfier class for javascript - I tried to make it as similar to NamePrettifier.java as possible. Comparing to it, js version misses removeUnsafeCharacters() method

XP-1787 Implement transliteration support in Admin UI

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/ContentTreeGridActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/UnpublishContentAction.ts

- also updated grid toolbar publish button

XP-3285 Unpublish - Context menu item

---

modules/admin/admin-ui/src/main/resources/assets/styles/_launcher.css
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/page/LiveFormPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/MinimizeWizardPanelEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemViewContextMenu.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemViewSelectedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/html-editor.css

Update the selection handler on the `ItemView`.
Added proxied event to hide context menu on `WizardPanel.toggleMinimize`.

XP-3138 Page Editor - Don't collapse the wizard panel on right-click

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentIndexConfigFactory.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/IndexConfigVisitor.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateNodeParamsFactory.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/ContentIndexConfigFactoryTest.java

- Added visitor that adds index config for eact Input of type html area
- Added test for it

XP-3190 HTML-area index config is wrong

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/macro/YoutubeMacroProcessor.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/macro/YoutubeMacroProcessorTest.java

- Added converting to an embedded youtube url
- Added and adjusted tests

XP-3310 Fix Youtube macro URL

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowseToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentPublishMenuManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentPublishPromptEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/ContentTreeGridActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/PublishTreeContentAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/main.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/menu/Menu.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/button/menu-button.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-publish-menu-manager.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less

Implemented Publish `MenuButton`.
Removed the Publish/Unpublish actions from toolbar.
Implemented actions enable/disable logic in Publish `MenuButton`.

XP-3270 Unpublish - Replace Publish action button with MenuButton in ContentBrowseToolbar

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/ContentTreeGridActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemsSelectionPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/MenuButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/menu/Menu.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/button/menu-button.less

* Fixed the leaf node detection.
* Fixed no `ContentTreeGridActions` update on node publish.
* Fixed dropdown control not collapsed after the publish dialog opened.

XP-3337 Unpublish - Publish MenuButton behavior fixes

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentUnpublishPromptEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/UnpublishContentAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/dialog/DependantItemsDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentUnpublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/main.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/dialog/dependant-items-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/content-publish-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/content-unpublish-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/remove/content-delete-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less

- created ContentUnpublishDialog
- created ContentUnpublishPromptEvent
- slightly adjusted base, delete and publish dialogs
- added unpublish dialog styles
- refactored delete and publish dialogs styles

XP-3276 Unpublish - Add Unpublish dialog

---

modules/core/core-api/src/main/java/com/enonic/xp/inputtype/DateTimeType.java
modules/core/core-api/src/main/java/com/enonic/xp/inputtype/DateType.java
modules/core/core-api/src/main/java/com/enonic/xp/inputtype/RelativeTime.java
modules/core/core-api/src/main/java/com/enonic/xp/inputtype/RelativeTimeParser.java
modules/core/core-api/src/main/java/com/enonic/xp/inputtype/TimeType.java
modules/core/core-api/src/test/java/com/enonic/xp/inputtype/DateTimeTypeTest.java
modules/core/core-api/src/test/java/com/enonic/xp/inputtype/DateTypeTest.java
modules/core/core-api/src/test/java/com/enonic/xp/inputtype/RelativeTimeParserTest.java
modules/core/core-api/src/test/java/com/enonic/xp/inputtype/TimeTypeTest.java

final date, time, datetime commit

XP-2877 Default Value - DateTime

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/MenuButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/menu/MenuItem.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/dropdown/Dropdown.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DatePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/AppHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/button/menu-button.less

Add focus in/out support in `MenuButton`.
Moved the focusIn/focusOut pattern into the `AppHelper`.

XP-3377 Dropdown of the Publish menu button doesn't always close

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSelectorQueryRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryLoader.ts

* Add sorting by modifiedTime to empty expressions in ContentSelector and ContentSummarySelector
* Refactoring

XP-3335 Make sure empty ContentSelectorRequests adds order-expressions

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/MacroComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/MacroDescriptor.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/MacroPreview.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/PageContributions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/GetMacrosRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/GetPreviewRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/MacroPreviewJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/MacroResourceRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/MacrosJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/MacrosLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/CreateHtmlAreaDialogEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/HTMLAreaDialogHandler.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroDockedPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/editor/HTMLAreaBuilder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/macro-dialog.less

- Created request preview classes
- Moved request and json classes to separate package
- Enabled rendering of preview

XP-3321 Insert Macro dialog - Render macro preview

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/image-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/modal-dialog.less

- Hidden the "x" icon closing the dialog
- Adjusted validation error appearance

XP-3411 Insert Image dialog - Hide "x" icon and fix validation

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/macro/MacroResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/macro/json/PreviewMacroJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/macro/json/PreviewMacroStringResultJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/macro/json/PreviewStringMacroJson.java
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/GetPreviewRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/GetPreviewStringRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/MacroPreviewJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/MacrosLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/PreviewRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/resource/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/HTMLAreaDialogHandler.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroDockedPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/plugins/macro.js
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/combobox/rich-combobox.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/macro-dialog.less

- Added additional service that fetches only macro string that is used if macro preview was not loaded yet
- Added additional request to fetch macro string only and common parent request for it and macro list request
- Added inserting of macrostring onto editor's area as its made in image editor
- Made macro dialog to use resolved macro's macroString for insert
- Made macro loader to use fetched macros list and filter it on user input

XP-3323 Insert Macro dialog - Insert macro into text editor

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/macro/PageContributions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroDockedPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/macro-dialog.less

- Added new MacroPreviewFrame class that will render macro preview in separate iframe if there area page contributions to be included into preview

XP-3418 Handle Page Contributions while rendering preview

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroDockedPanel.ts
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/macro/TwitterMacroProcessor.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/macro/TwitterMacroProcessorTest.java

- Made preview iframe to render its content via document.write() method - it makes browser to evaluate dynamically inserted scripts
- Moved twitter.js reference to contributions part of a response in the TwitterMacroProcessor.process() method

XP-3425 Fix Twitter preview

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-step-navigator-and-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/z-index.less

XP-3366 Mobile - "Navigate to"-bar covers the publish button

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroDockedPanel.ts
modules/app/app-system/src/main/resources/assets/css/macro/youtube/youtube.css
modules/core/core-macro/src/main/java/com/enonic/xp/impl/macro/BuiltinMacroDescriptors.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/macro/YoutubeMacroProcessor.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/macro/YoutubeMacroProcessorTest.java

- Removed height and width params from youtube form
- Added youtube.css to system app
- Added contribution to youtube macro for youtube.css

XP-3440 Change Youtube macro to be responsive

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/action/BasePreviewAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/notify/MessageBus.ts

Added notification on the popup block.
Added isBlocked check to prevent errors.

XP-3365 Incorrect behavior for disable/enable 'Preview' button

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeleteContentCommand.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/DeleteContentCommandTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_delete.java

-Made items delete recursively, as for publish/unpublish, beginning from childs up to parents, thus all deleted items get into result set

XP-3480 Delete notification - Take deleted child items into account

---

modules/admin/admin-ui/src/main/resources/admin/tools/home/home.html
modules/admin/admin-ui/src/main/resources/assets/js/home/launcher.js
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

* Turned on async mode for the launcher panel import
* Changed transition of the background image to not depend on loading of the launcher panel
* Small styling fixes

XP-3328 Content wizard opens in mobile layout under dev mode

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentUnpublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/event/ContentServerEventsHandler.ts
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UnpublishContentCommand.java

- Made unpublish command to remove pending-delete items from draft branch as well
- Adjusted handling of deleted events that contain both unpublished and deleted items

XP-3508 Allow unpublishing content items in "Pending delete" status

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/image-uploader-el.less

Fixed image uploader display style.

XP-3530 Wrong width for image drop zone in Page Editor

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/view/MarketAppsTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowseItemsSelectionPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/SortContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowseItemsSelectionPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/SelectionItem.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/NamesAndIconViewer.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/DataView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/Grid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less

Fixed the message from `undefined` to `'... loading more content.'`.
Fixed browse items rendering performance issue.

XP-3468 "Undefined" checkbox appears, during the scrolling of grid items

---

modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/resolver/ClassLoaderApplicationUrlResolver.java

Revert "XP-2923 Launcher is slow when XP is started in dev mode"

---

modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/page-view.less

- For live-edit made toolbar tooltip as sticky as toolbar

XP-3553 Text component - Wrong positioning of tooltip in editor toolbar

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/macro/MacroResource.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/postprocess/instruction/MacroInstruction.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/postprocess/instruction/MacroInstructionTest.java

XP-3554 Avoid executing and rendering macros in Edit mode.

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DatePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/Picker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/_module.ts

- Fixed popup toggle on TimPicker
- Made all pickers to toggle pop-up in a similar fashion
- Moved all the common code of time, date and datetime pickers into parent Picker class

XP-3564 Icon for showing of TimePicker does not work

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/LiveEditModel.ts

- Extracted initialization code of LiveEditModel into separate class LiveEditModelInitializer
- Refactored initialization methods

XP-3486 Refactor LiveEditModel.initPageModel

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ContentIdsPermissionsJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/get_permitted_actions_admin_allowed_all.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/get_permitted_actions_params_multiple_contents.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/get_permitted_actions_params_root.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/get_permitted_actions_params_root_all_permissions.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/get_permitted_actions_params_single_content.json
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/ContentTreeGridActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/GetPermittedActionsRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

-Returning from backend allowed actions for selected contents.  Example: ["READ", "CREATE"]. When no content ids set in request - checking permissions against root. When no permissions set in request - checking all possible permissions

XP-3510 Optimize API requests fetching content permissions

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/FilterableItemsList.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/MostPopularItemsBlock.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/MostPopularItemsList.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/NewContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/NewContentDialogList.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/NewContentDialogMediaUploader.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/RecentItemsBlock.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/RecentItemsList.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/ArrayHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less

-Removed mock modal dialog
-Refactored dialog

XP-3587 New content dialog: refactoring

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroDockedPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/macro-dialog.less

- Subscribed macro dialog on docked panel events
- Made preview frame to generate 'rendered' event
- Made docked panel to notify about panel shown/rendered events

XP-3654 Macro Dialog - Recenter after switching between the tabs

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroDockedPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/macro-dialog.less

- Made macro frame to calculate its height based on available height
- Sped up macro dialog centering
- Fixed youtube and instagram rendering bugs

XP-3655 Macro Dialog - Use max vertical space for preview

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/ApplicationResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/json/ApplicationInstallParams.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/json/ApplicationInstallResultJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/json/ApplicationInstalledJson.java

-Bringing back 'install' and 'installUrl' back into admin impl ApplicationResource because previously moved them to server rest module instead of copying

XP-3688 Implement application-load rest service in /api

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfigurator.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormItemSetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/InputView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-step-form.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/content-combo-box.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/inputtype/relationship/relationship.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/modal-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less

- Removed validation viewer from FormItemSetView - I assume that each FormItem will handle its validation separately
- Fixed validation look of Site configurator - made input view to check for appropriate InputType and skip its renderValidationErrors() call
- Fixed look of selected items within the ContentCombobox - removed extra padding, aligned edit and close icons, adjusted position of drag icon
- Fixed upload button's position in html area modal dialog

XP-3822 Validation - Don't show validation message for element blocks

---

modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationDescriptor.java
modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationDescriptors.java

XP-3879 Implement ApplicationDescriptor

XP-3879 Implement ApplicationDescriptor

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/responsive/ResponsiveManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/modal-dialog.less

- Fixed onAvailableSizeChanged() handler - now it will call item.update() after item is rendered as otherwise it may set incorrect range class to responsive item as it occurs with html area modal dialogs
- Fixed modal dialogs input-wrapper and validation-viewer indents for small resolutions

XP-3872 Validation - Input inside invalid itemview changes position

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/DateHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/DateTime.ts

- Refactored DateTime wrapper and DateHelper classes to handle extra hour that may occur due to Daylight Saving Time

XP-3905 DateTime content type - Discrepancy notification when saving

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/content/inputtype/image/image-selector.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dropzone.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/image-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

- Made image selector's input to be dropzone. Added styling for it.

XP-3886 HTML Area - Image dialog - Uploader is not working

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/GroupRoleWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/GroupWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/PrincipalWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/RoleWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserMembershipsWizardStepForm.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserWizardPanel.ts

-Updating membership step form for User wizard on save
-Refactored updatePersistedItem() for principals
-Removed overriden show() method from GroupRoleWizardPanel (issue it was added there because of is not reproduced anymore)

XP-3953 Group, that was removed, is displayed on the UserWizard

---

modules/admin/admin-api/src/main/java/com/enonic/xp/admin/widget/WidgetDescriptor.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/widget/WidgetDescriptorResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/widget/json/WidgetDescriptorJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/widget/XmlWidgetDescriptorParser.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/widget/XmlWidgetDescriptorParserTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/widget/XmlWidgetDescriptorParserTest.xml
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/Widget.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/WidgetDescriptorJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/WidgetDescriptorResourceRequest.ts
modules/core/core-api/src/main/resources/META-INF/xsd/model.xsd

- Added config property to custom widget config xml - it allows setting additional parameters for widget that can be used to style widget's behavior
- Adjusted widget parser test
- Added handling of "re-render-on-resize" config entry that forces widget to re-render on each resize (required for GA widget)

XP-3935 Do not re-draw the VWO widget on changing the details panel size

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/InputView.ts

-Type comparison improved to be case insensitive

XP-3994 Duplicated label for CheckBox input types

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/event/ContentServerEventsHandler.ts

-Issue was that after renaming content it's path changes also, and when fetching updated content summaries old path was used

XP-4033 Update event not triggered when content is renamed

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/ContentTreeGridActions.ts

-When single item selected, checking if parent allows content create to toggle duplicate action state

XP-4043 Impossible to duplicate an image content

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/ContentQueryRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/ContentSummaryLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/ContentSummaryRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/MoveContentSummaryLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/loader/PostLoader.ts

- All post loaders need to correctly implement isPartiallyLoaded and resetParams method hence ContentSummaryLoader and MoveContentSummaryLoader classes were adjusted
- All postloader requests need to correctly update their state so that each send call passes correct "from" value, so ContentSummaryRequest was adjusted to handle that.

XP-4077 RichCombobox: filtered option is blinking

---

modules/admin/admin-ui/gulp/config.js
modules/admin/admin-ui/gulp/tasks/clean.js
modules/admin/admin-ui/gulp/tasks/css.js

Added `common/icons` newer check for styles.
Added css dest files to the clean task.

XP-4090 Gulp build does not update artifacts after icons.less changed

---

modules/admin/admin-ui/src/main/resources/assets/js/home/main.js

-added cookie for xp tour, checking it when opening home dashboard

XP-4094 Show Welcome tour the first time dashboard opens

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/text/EmailInput.ts

XP-4112 Email validation does not allow new top level domains

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardStepForm.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardStep.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardStepForm.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardStepNavigatorAndToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormItemLayer.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/InputView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-step-navigator-and-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-step-navigator.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/input-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/page/contextwindow/inspections-panel.less

-hiding the common toggle icon if none of the inputs on the form have help text

XP-4109 Content Wizard - Implement toggle icon for help text

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/ApplicationRowFormatter.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/browse/ApplicationTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentRowFormatter.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/browse/UserItemsRowFormatter.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/browse/UserItemsTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

Moved formatters to the separate classes.
Refactor events.
Reordered node manipulation methods.
Moved event handlers initialization from the constructor to the method.

XP-4149 ContentTreeGrid - refactoring

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialog.ts

Added "focus" set on Delete button, once it becomes enabled.

XP-4146 Delete content dialog - Set focus on the "Delete" button

---

README.md

Updated important techincal information in main README.md file.

Updated important technical info in main README.md file

---

modules/admin/admin-ui/src/main/resources/assets/js/home/main.js
modules/admin/admin-ui/src/main/resources/assets/js/home/xptour.js

Added additional call of the responsive manager.

XP-4180 Welcome Tour modal dialog not always has a correct location

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts

- Moved 1ms timeout in onAdded from Element to SplitPanel, because of conflicts with TinyMce

XP-4218 Incorrect alignment of elements inside the Search Panel

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/view/item-preview-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

Added padding so that the iframe content won't be covered by header.

XP-4162 Mobile/lo-res - Preview header covers the previewed content

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/optionset/FormOptionSetOptionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/form-option-set.less

- Made inputs to be enabled/disabled on option select/deselect
- Adjusted managing of expanded property
- Made input to be reset on option deselect

XP-4154 Make expanded property to be used on initial open in wizard

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/ContentItemPreviewPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeRoot.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

Implemented `newly selection` check.
Updated the behaviour of the mobile preview/details panel.

XP-4163 Mobile/lo-res - Preview panel is showing wrong content when more than one item is selected

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts

* Removed delay on showing form mask in all wizard panels except for Content Wizard

XP-4242 Users app - Can't open User/Role/Group wizard pages

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentPublishMenuManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/Action.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/MenuButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/menu/Menu.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/toolbar/Toolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/button/menu-button.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-browse-toolbar.less

Implemented minimize and maximize methods in MenuButton.

XP-4164 Mobile/lo-res - Show compact version of the Publish button

---

modules/admin/admin-ui/gulp/config.js
modules/admin/admin-ui/gulp/tasks/js.js
modules/admin/admin-ui/gulp/util/webpackConfig.js

Added task to copy the launcher file to assets.

XP-4238 Launcher toolbar does not work for custom admin tools

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/DeleteAction.ts

…quotes
* Fixed inconsistency between frontend and backend delete notification messages

XP-4304 Display Name in the notification message should be in double quotes

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-step-navigator-and-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/combobox/rich-combobox.less

* Changed the look of inactive help text icon

XP-4247 Content Wizard - Replace help text icon

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/checkbox/Checkbox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/Checkbox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/LinkModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/checkbox.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/modal-dialog.less

XP-4322 Checkbox input - Set label placement from input config

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/checkbox.less

* Fixed position for top-aligned checkbox

XP-4322 Checkbox input - Set alignment from input config

---

modules/admin/admin-ui/src/main/resources/web/spec/specs.html

* Fixed reference to libraries js file

XP-4101 Implement new form item type - OptionSet

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/SettingsWizardStepForm.ts

XP-4351 Status of published content changes from "Modified" to "Online" after save

---

modules/admin/admin-ui/src/main/resources/web/spec/common/form/set/_spec.ts
modules/admin/admin-ui/src/main/resources/web/spec/common/form/set/itemset/FormItemSet.spec.ts
modules/admin/admin-ui/src/main/resources/web/spec/common/form/set/itemset/FormItemSetView.spec.ts
modules/admin/admin-ui/src/main/resources/web/spec/common/form/set/itemset/_spec.ts

- Added tests for FormItemSet and FormItemSetView

XP-4339 Refactor code in FormOptionSetView and FormItemSetView

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/FormSetOccurrenceView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/FormSetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/itemset/FormItemSetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/optionset/FormOptionSetView.ts

- Moved all the common code into parent class
- Added small fix into ContentWizardPanel for case when all FormItemOccurrences removed and then Save pressed

XP-4392 Refactor code in FormOptionSet and FormItemSet classes

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/dialog/dependant-items-dialog.less

Show all statuses in publish dialog dependants list

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/widget/info/PropertiesWidgetItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummary.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/ContentPublishTimeRangeJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/ContentSummaryJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/item/ItemJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/widget-info.less

* Show "Published from" date/time in the Info panel
* Show time for "Created" and "Modified" properties
* Redo layout of the panel on publish so that "Published from" is updated

XP-4402 Show publish.from info in detail panel in ContentStudio

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommand.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_duplicate.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_publish_update_publishedTime.java

XP-4409 Clear publish.from on duplicate

---

modules/admin/admin-ui/gulp/tasks/spec.js
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/form-item-set-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/form-option-set.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/color.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

* Changed radiobuttons to look as in the prototype
* Fixed missing bottom border of an itemset inside an optionset

XP-4410 OptionSet - Cosmetic improvements

---

modules/admin/admin-ui/src/main/resources/web/spec/common/form/set/optionset/FormOptionSetView.spec.ts

XP-4384 Add specs for Add and Collapse buttons inside FormOptionSetView
XP-4385 Add specs for occurrence views events inside FormOptionSetView

XP-4383 Add specs for validation inside FormOptionSetView

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormItemLayer.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/optionset/FormOptionSetView.ts
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/DuplicateValueResolverTest.java

- Adjusted new FormOptionSetView initialization to make it similar to ItemSet - it did not handle case with min=0 occurrence

XP-4466 OptionSet - Option set is shown when occurrences.min = 0

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts

- Added explicit call to unhighlight for onAdded event for TextComponentView

XP-4493 Page editor - On-hover border is shown in text mode

---

modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java

Disabled content delete tests, since logic changed to use progress reporter

Disable content delete tests

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/text-view.less

- Added "visible" class to toolbar container that enforces visibility of a tinymce toolbar
- For firefox added blur triggering on setEditMode to force toolbar to appear

XP-4494 Page editor - Text component incorrectly goes out of edit mode

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/SortContentDialog.ts

Added focus to the apply button on shown to make dialog not to lose focus.

XP-4500 Sort dialog - Catch key events

---

modules/admin/admin-ui/src/main/resources/web/admin/common/icons/icons.less
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/FormEl.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/KeyHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DatePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/Picker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/time/date-picker.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/time/date-time-picker.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/time/time-picker.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

- Moved common handlers to common picker class
- Fixed keyboard navigation
- Adjusted getNextFocusable() method of FormEl to skip hidden elements
- Adjusted styling

XP-4517 Date/Time picker - Fix keyboard navigation

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DatePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/Picker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts

- Added placeholder text
- Moved some common code into Picker.ts

XP-4519 Date/Time picker - Add placeholder text

---

modules/admin/admin-ui/src/main/resources/admin/tools/applications/applications.html
modules/admin/admin-ui/src/main/resources/admin/tools/content-studio/content-studio.html
modules/admin/admin-ui/src/main/resources/admin/tools/user-manager/user-manager.html
modules/admin/admin-ui/src/main/resources/web/admin/common/lib/_include.js
modules/admin/admin-ui/src/main/resources/web/admin/common/lib/launcher.js

* Append Launcher panel via direct reference to launcher.js

XP-4521 Adding the Launcher Panel menu - Assets not found

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/Content.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatus.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/ContentSummaryAndCompareStatusFetcher.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/isContentReadOnlyRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/DataView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/Grid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-tree-grid.less

XP-4463 Content Grid - Highlight content items with read-only access

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/tag/Tag.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/tags/Tags.ts

- Fixed Tag.update method so that it correctly returns promise
- Added debounce for search suggestion call

XP-4544 Page Editor - Error when using tags inside a Part component

---

modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationNameResolver.java

Deleting tmp-file after resolving name.

XP-4267 Application installation - Temporary application jar deletion

---

modules/distro/src/bin/server.bat
modules/distro/src/bin/server.sh
modules/lib/lib-http-client/build.gradle
modules/lib/lib-http-client/src/main/java/com/enonic/xp/lib/http/HttpRequestHandler.java
modules/lib/lib-http-client/src/main/java/com/enonic/xp/lib/http/ResponseMapper.java
modules/lib/lib-http-client/src/test/java/com/enonic/xp/lib/http/HttpRequestHandlerTest.java

Set JVM property `jsse.enableSNIExtension=true` in start up scripts
Upgrade okhttp from 2.5.0 to 3.4.2

XP-4552 HTTP client - SSL domain validation fails with hosts having multiple certificates

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishContentJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishScheduleJson.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/SchedulePublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/PublishContentRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/content-publish-dialog.less

- Added publish schedule dialog
- Adjusted publish request - added from and to fields
- Adjusted publish dialog to interact with schedule dialog
- Added Json class for Schedule object on back-end. Made PublishContentJson to use it.

XP-4560 Time-based publishing - Publish Wizard - Schedule publishing

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/SchedulePublishDialog.ts

- Added checking of fromDate() on schedule dialog show
- Added resetting if invalid status on date inputs reset

XP-4579 Time-based publishing - Publish Wizard - Publish from validation

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/CreateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/MoveNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/ResolveInsertOrderValueCommand.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/MoveNodeCommandTest.java

Moved resolvingof insert order value out of createNodeCommand, using this in MoveNodeCommand to insert first into manually ordered parents

XP-4619 Manual order fails after moving content to manual sorted parent

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/ActionButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/button/Button.ts

-Escaping html in  label value

XP-4626 SaveBeforeClose dialog- buttons have incorrect label

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentMoveComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/ContentSummaryRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/MoveAllowedTargetsRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/MoveContentSummaryLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/_module.ts

-Updated move dropdown loader so content query will not return descendants of selected contents

XP-4615 Move Dialog - Enable paging

---

modules/core/core-api/src/main/java/com/enonic/xp/node/NodeService.java
modules/core/core-api/src/main/java/com/enonic/xp/node/OperationNotPermittedException.java
modules/core/core-export/src/test/java/com/enonic/xp/core/impl/export/NodeServiceMock.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/AbstractDeleteNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/MoveNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/RenameNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/SetRootPermissionsCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/UpdateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/UpdateRootPermissionsCommand.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/DeleteNodeByIdCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/MoveNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/RenameNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/SetRootPermissionsCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/UpdateNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/UpdateRootPermissionsCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImplTest.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/NodeHandler.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/SetRootPermissionsHandler.java
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/modifyRootPermissions.js
modules/lib/lib-node/src/main/resources/site/lib/xp/node.js
modules/lib/lib-node/src/test/java/com/enonic/xp/lib/node/SetRootPermissionsHandlerTest.java

Stuff concerning root-node and permissions

XP-3997 Repo Service API

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/locale/locale-selected-option-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/security/acl/access-control-entry.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/security/acl/userstore-access-control-entry.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/security/principal-selected-option-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

* Fixed alignment of the X icon via mixin

XP-4696 Wizard Step Form - X icon is not correctly aligned

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less

* Removed zebra background in the grids

XP-4704 Content/Application/User Grid - Turn off zebra backround

---

modules/lib/lib-node/src/main/resources/site/lib/xp/node.js

XP-4630 Change signatures of methods with key/keys

---

modules/admin/admin-ui/src/main/resources/assets/js/home/launcher.js
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/main.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/icons/icons.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar-tab-menu.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/form-option-set-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/button/button.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/content-publish-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/reset.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

* Removed overrides of native browser outlining

XP-4733 Don't override native browser outline highlighting

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

XP-4787 Option Set content - button 'Edit' in the Image-selctor does not open an image-wizard

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/editor/HTMLAreaBuilder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/plugins/image.js

* Enabled Cmd-Alt-X (where X is number from 1 to 6) shortcuts for HTML Area headers

XP-4808 HTML Area - Fix shortcuts for H1-H6 headers

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/SchedulePublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ScheduleWizardStepForm.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/form-option-set-view.less

- Adjusted text entries
- Enforced red border for invalid expandable option which gets overriden by blue one

XP-4833 Publishing Wizard - Fix texts related to scheduled publishing

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

- Added handler for clicking rows with shift pressed

XP-4841 Shift+click should select a range of rows

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

- Added handler for clicking rows with ctrl pressed

XP-4842 Mod+click should select the row

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/main.ts

-can't use 'this' keyword out of classes

XP-4909 Content Wizard - Empty tooltip is visible

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ModalDialog.ts

-Submiting dialog on 'Enter' key pressed in text input fields

XP-4950 HTML Area - Modal dialogs must handle submit on Enter

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/LinkModalDialog.ts

-Small fix for Link Modal Dialog to set focus correctly on open

https://youtrack.enonic.net/issue/XP-4950

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/issue/IssueJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/issue/IssuesJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/CreateIssueJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/GetIssuesJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/UpdateIssueJson.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/CreateIssueParams.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/EditableIssue.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/CreateIssueCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/serializer/IssueDataSerializer.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/issue/CreateIssueCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/issue/serializer/IssueDataSerializerTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/issue/IssueServiceImplTest_create.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/issue/IssueServiceImplTest_getIssue.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/issue/IssueServiceImplTest_update.java

- Updated CreateCommand to set Creator and CreatedDate in command, not params
- Added issue service with three methods and appropriate classes
- Missing tests

#4547 - Implement create issue REST API

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/DetailsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetView.ts
modules/app/app-applications/src/main/js/app/browse/ApplicationBrowsePanel.ts

Added widgets update handler when apps are started, stopped or updated.

Automatically update the details panel whenever widgets are updated (#4580)

---

modules/core/core-api/src/main/java/com/enonic/xp/node/UpdateNodeParams.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/branch/storage/BranchServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/AbstractNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/UpdateNodeCommand.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/UpdateNodeCommandTest.java
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/PrincipalKeyNodeTranslator.java
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/PrincipalNodeTranslator.java
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityServiceImpl.java
modules/core/core-security/src/test/java/com/enonic/xp/core/impl/security/SecurityServiceImplTest.java
modules/core/core-security/src/test/java/com/enonic/xp/core/impl/security/UserNodeTranslatorTest.java

I still have some tests to do but can you start to look at the code?

Principal with uppercase name (#4462)

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetsSelectionRow.ts

Fixed the DefaultOptionDisplayValueViewer check.

`Version history` and `Dependencies` are displayed at the same time (#4581)

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/ResolveSyncWorkCommand.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/ResolveSyncWorkCommandTest.java

Please check my comment on the issue about unit tests. They seemed wrong to me but I am not sure if I am missing something here

Resolve dependencies with children for a selected online content (#4640)

---

modules/core/core-api/src/main/java/com/enonic/xp/query/filter/ValueFilter.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_find.java
modules/lib/lib-common/src/main/java/com/enonic/xp/lib/common/ObjectToValueMapper.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/FilterParamsFactory.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/QueryContentHandler.java
modules/lib/lib-content/src/main/resources/site/lib/xp/content.js
modules/lib/lib-content/src/main/resources/site/lib/xp/examples/content/query_filter.js
modules/lib/lib-content/src/test/java/com/enonic/xp/lib/content/FilterParamsFactoryTest.java
modules/lib/lib-content/src/test/java/com/enonic/xp/lib/content/QueryContentHandlerTest.java
modules/lib/lib-value/src/main/java/com/enonic/xp/lib/value/ScriptValueTranslator.java

Yes. Added support. For filters. In js-api.

 Add support for filters in js-api (#4689)

---

modules/lib/lib-common/src/main/java/com/enonic/xp/lib/common/JsonToFilterMapper.java
modules/lib/lib-common/src/test/java/com/enonic/xp/lib/common/JsonToFilterMapperTest.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/QueryContentHandler.java
modules/lib/lib-content/src/main/resources/site/lib/xp/content.js
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/FindNodesByQueryHandler.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/NodeHandler.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/QueryNodeHandlerParams.java
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/query.js
modules/lib/lib-node/src/main/resources/site/lib/xp/node.js

Added filter support for node-api, did some refactoring and cleanup

Support filters in node-query api (#4700)

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts

Removed redundant check for `new` state.

OptionSet content - incorrect validation of the content in the wizard when all required fields are filled (#4594)

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/core/core-api/src/main/java/com/enonic/xp/content/UndoPendingDeleteContentParams.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UndoPendingDeleteContentCommand.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_undoPendingDelete.java

Ensures that parents are revived also

Undelete must revive deleted parents (#4707)

---

modules/core/core-api/src/main/java/com/enonic/xp/vfs/BundleResource.java
modules/core/core-api/src/main/java/com/enonic/xp/vfs/NullResource.java
modules/core/core-api/src/test/java/com/enonic/xp/vfs/NullResourceTest.java
modules/core/core-export/src/main/java/com/enonic/xp/core/impl/export/NodeImporter.java

Added NullResource for bundle resources that does not exist

Application import fails with NP #4737

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/UpdateNodeCommand.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/ModifyNodeHandler.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/QueryNodeHandlerParams.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/mapper/NodeMapper.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/mapper/PropertyTreeMapper.java
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/modify-keep-types.js
modules/lib/lib-node/src/test/java/com/enonic/xp/lib/node/ModifyNodeHandlerTest.java
modules/lib/lib-value/src/main/java/com/enonic/xp/lib/value/ScriptValueTranslator.java

Using raw values for internal processing of node properties

RepoConnection.modify converts properties to String #4632

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentTypeFromMimeTypeResolver.java

*.odp (libreOffice...) files becomes media:unkown should be media:presentation? #4578

keynote files becomes media:unkown should be media:presentation? #4577

---

modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/IndexConfigAlias.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/IndexConfigFactory.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/mapper/IndexConfigDocMapper.java
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/create-1.js
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/create-2.js
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/get-1.js
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/modify-keep-types.js
modules/lib/lib-node/src/main/resources/site/lib/xp/examples/node/modify.js
modules/lib/lib-node/src/test/java/com/enonic/xp/lib/node/IndexConfigFactoryTest.java
modules/lib/lib-node/src/test/java/com/enonic/xp/lib/node/mapper/IndexConfigDocMapperTest.java
modules/lib/lib-node/src/test/resources/com/enonic/xp/lib/node/mapper/index_config_full.json

Added alias and mappings for path indexing

Missing support for index as path in node-API (#4397)

---

modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/mapper/ContentMapper.java

Content Mapper - Missing attribute #4746

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/spec/common/security/Principal.spec.ts
modules/admin/admin-ui/src/main/resources/web/spec/common/security/acl/AccessControlEntry.spec.ts

Edit Permissions Dialog shows incorrect content name #4752

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/ApplicationResource.java

remove hardcoded value for market version (#4710)

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts

Fixed securityWizardStepForm trying to update before initialized (for newly created content).

The Wizard page is blank for a new folder (#4809)

---

modules/core/core-api/src/main/java/com/enonic/xp/query/filter/FieldFilter.java
modules/core/core-api/src/main/java/com/enonic/xp/query/filter/IdFilter.java

Id-filter missing default fieldName #4855

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/DetailsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/NonMobileDetailsPanelsManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetsSelectionRow.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/button/NonMobileDetailsPanelToggleButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/panel/panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-browse-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/details-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/widget-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

Updated details panel UI.
Updated UI in mobile mode.
Fixed text size in the options dropdown in mobile mode.

Detail Panel - UI improvements (#4816)

---

modules/core/core-api/src/main/java/com/enonic/xp/content/ExtraDatas.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentCommand.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/AbstractContentServiceTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_move.java

Moved `ContentService` move implementation to a separate command.
Added logic to remove Content ExtraData related to the site it was removed from.

Alert about unsaved changes appears when closing content that was moved out of a site (#4646)

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeleteAndFetchContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/GetBinaryCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/GetNearestSiteCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ReprocessContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateMediaCommand.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/CreateContentCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/DeleteAndFetchContentCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/GetNearestSiteCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/RenameContentCommandTest.java

Impossible to upload image in a page template #4820

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/IssueDialogForm.ts

Removed current user from `approver ` dropdown in `IssueDialogForm`.

Fields overflow the "New issue" dialog #4834

---

modules/core/core-api/src/main/java/com/enonic/xp/issue/CreateIssueParams.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/Issue.java

-Id used to generate name for Node -> thus for path also

Allow issues with existing title #4911

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResource.java
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/list/ListBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/issues-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less
modules/app/app-contentstudio/src/main/js/app/dialog/ProgressBarDialog.ts
modules/app/app-contentstudio/src/main/js/app/publish/CreateIssueDialog.ts
modules/app/app-contentstudio/src/main/js/app/publish/IssueDetailsDialog.ts
modules/app/app-contentstudio/src/main/js/app/publish/IssueList.ts
modules/app/app-contentstudio/src/main/js/app/publish/IssueStatus.ts
modules/app/app-contentstudio/src/main/js/app/publish/IssuesDialog.ts
modules/app/app-contentstudio/src/main/js/app/publish/IssuesPanel.ts
modules/app/app-contentstudio/src/main/js/app/publish/UpdateIssueRequest.ts

* Changed success message for published issue.
* Added update of the issue lists after the issue is (closed).
* Fixed `.creator` styles in issue dialog.
* Fixed `IssueList.reload()` not removing actual items.

Implement closing the issue after publishing from the Issue dialog #4685

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueMailMessageGenerator.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationsSender.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationsSenderImpl.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageGenerator.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageParams.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/UpdateIssueJson.java
modules/admin/admin-impl/src/main/resources/com/enonic/xp/admin/impl/rest/resource/issue/email.html
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResourceTest.java
modules/app/app-contentstudio/src/main/js/app/issue/resource/UpdateIssueRequest.ts
modules/app/app-contentstudio/src/main/js/app/issue/view/IssueDetailsDialog.ts
modules/core/core-api/src/main/java/com/enonic/xp/issue/Issue.java

-Also included small fix for issue index to be set while updating issue

Send email notification on issue update #4683

---

modules/app/app-contentstudio/src/main/js/app/issue/view/IssueDetailsDialog.ts

Disable child toggler inside issue dialog when it's in read-only mode #4983

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

Removed limitation on selected options in options set if maximum occurrences equal 0.

Can not set maximum="0" on options in option-set #5001

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueMailMessageGenerator.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueMailMessageParams.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationsSenderImpl.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageParams.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageParams.java
modules/admin/admin-impl/src/main/resources/com/enonic/xp/admin/impl/rest/resource/issue/item.html
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationsSenderImplTest.java

-Added content type svg icon (if available) for publish content item email representation

Use inline SVG in content list inside issue email #4987

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/IssueIndexConfigFactory.java

-Set index-config "FULLTEXT" for Issue.title and Issue.description

Index title and description as fulltext #5041

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/details-panel.less
modules/app/app-contentstudio/src/main/js/app/view/detail/WidgetsSelectionRow.ts

Moved DetailsPanel ContentSummaryViewer from dropdown to widget.
Fixed typos.

Details Panel - Show content summary inside the Info Widget #5042

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/AbstractDeleteNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImpl.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/elasticsearch/snapshot/SnapshotServiceImplTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImplTest.java
modules/core/core-security/src/test/java/com/enonic/xp/core/impl/security/SecurityServiceImplTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/AbstractContentServiceTest.java

Using DeleteByIdCommand to delete rootNode with children

repositoryService.deleteBranch does not delete recursivly #5064

---

modules/app/app-applications/src/main/js/app/view/ApplicationItemStatisticsPanel.ts
modules/app/app-users/src/main/js/app/wizard/ChangeUserPasswordDialog.ts

Localization of app-users #5055

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/issue/IssueListJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/issue/IssueResolvedAssigneesJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/ListIssuesJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResourceTest.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/json/ListIssuesJsonTest.java
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/tooltip.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/issue-details-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/issue-list-dialog.less
modules/app/app-contentstudio/src/main/js/app/issue/IssueSummary.ts
modules/app/app-contentstudio/src/main/js/app/issue/IssueWithAssignees.ts
modules/app/app-contentstudio/src/main/js/app/issue/json/IssueWithAssigneesJson.ts
modules/app/app-contentstudio/src/main/js/app/issue/resource/IssueResponse.ts
modules/app/app-contentstudio/src/main/js/app/issue/resource/ListIssuesRequest.ts
modules/app/app-contentstudio/src/main/js/app/issue/resource/ListIssuesResult.ts
modules/app/app-contentstudio/src/main/js/app/issue/view/IssueList.ts
modules/app/app-contentstudio/src/main/js/app/issue/view/IssueStatusInfoGenerator.ts

-also fixed issue with sorting when items in issue list were not sorted properly according to modified date

Show assignees in compact mode in the list of issues #5060

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/issue/IssueStatsJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/ListIssuesJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResourceTest.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/json/ListIssuesJsonTest.java
modules/app/app-contentstudio/src/main/js/app/issue/json/IssueStatsJson.ts
modules/app/app-contentstudio/src/main/js/app/issue/resource/GetIssueStatsRequest.ts
modules/app/app-contentstudio/src/main/js/app/issue/view/IssueListDialog.ts
modules/app/app-contentstudio/src/main/js/app/issue/view/IssuesPanel.ts
modules/core/core-api/src/main/java/com/enonic/xp/issue/FindIssuesParams.java

Optimise requests in the issue list #5110

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentAddedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/GridDragHandler.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/app/app-contentstudio/src/main/js/app/wizard/PageComponentsGridDragHandler.ts
modules/app/app-contentstudio/src/main/js/app/wizard/PageComponentsTreeGrid.ts
modules/app/app-contentstudio/src/main/js/app/wizard/PageComponentsView.ts

Updated DnD, so that items won't expand after the drop.

Page Component View - Don't expand layout after DnD #5136

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/responsive/ResponsiveItem.ts
modules/app/app-contentstudio/src/main/js/app/browse/ContentBrowsePanel.ts
modules/app/app-contentstudio/src/main/js/app/view/detail/NonMobileDetailsPanelsManager.ts

Fixed the problem with switch from non-mobile to mobile mode, when ItemStatisticsPanel is visible.
Fixed the problem with switch from mobile to non-mobile mode, when ItemStatisticsPanel is visible.

Details Panel goes blank instead of switching into floating mode #5210

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ImageCroppingSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/editor/HTMLAreaHelper.ts

-Adding custom option when scaling is not from provided list
-Fixed image src converting to correctly handle 'size' and 'scale' params in url

Support custom image scaling in HTML Area #5216

---

modules/core/core-api/src/main/java/com/enonic/xp/issue/IssueConstants.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/CreateIssueCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/IssueInitializer.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/issue/CreateIssueCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/issue/GetIssueCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/issue/UpdateIssueCommandTest.java

-Updated issue creation command to create node with permissions inherited from issue root node READ/CREATE/MODIFY/DELETE

Wrong permissions on Issues-node #5225

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TextLine.ts

Hide regex validation text inside TextLine control when there's no regex in config #5431

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/Principal.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/UserStore.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGridBuilder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/combobox/combobox.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/user/browse/user-browse-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/user/create/new-principal-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less
modules/app/app-users/src/main/js/app/browse/ShowNewPrincipalDialogEvent.ts
modules/app/app-users/src/main/js/app/browse/UserBrowsePanel.ts
modules/app/app-users/src/main/js/app/browse/UserItemsTreeGrid.ts
modules/app/app-users/src/main/js/app/browse/action/NewPrincipalAction.ts
modules/app/app-users/src/main/js/app/create/NewPrincipalDialog.ts
modules/app/app-users/src/main/js/app/create/UserItemTypesRowFormatter.ts
modules/app/app-users/src/main/js/app/create/UserItemTypesTreeGrid.ts
modules/app/app-users/src/main/js/app/create/UserTypeTreeGridItem.ts
modules/app/app-users/src/main/js/app/create/UserTypesTreeGridItemViewer.ts
modules/app/app-users/src/main/js/main.ts
modules/app/app-users/src/main/resources/admin/i18n/phrases.properties
modules/app/app-users/src/main/resources/admin/i18n/phrases_no.properties

Created a new grid, grid item, and viewer to handle new principal dialog.

Implement Create user entity dialog #5119

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeleteContentCommand.java

Removed recursive fetch and moved fetching children until its needed

Optimize delete content command (#5451)

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/security/SecurityResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/security/json/CreateGroupJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/security/json/GroupJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/security/json/UpdateGroupJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/security/SecurityResourceTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/security/getPrincipalGroupById.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/security/getPrincipalGroupByIdWithMemberships.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/security/updateGroupParams.json
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/view/ItemDataGroup.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/CreateGroupRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/GetPrincipalByKeyRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/Group.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/GroupJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/UpdateGroupRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/ArrayHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/security/principal-combobox.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/user/principal-item-statistics-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less
modules/app/app-users/src/main/js/app/view/UserItemStatisticsPanel.ts
modules/app/app-users/src/main/js/app/wizard/GroupWizardPanel.ts
modules/app/app-users/src/main/js/app/wizard/MembershipsWizardStepForm.ts
modules/app/app-users/src/main/js/app/wizard/PrincipalWizardDataLoader.ts
modules/app/app-users/src/main/js/app/wizard/UserWizardPanel.ts
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityServiceImpl.java

Added support of roles selection in Group wizard.

Add selection of Role in the User Group wizard #5285

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/editor/HTMLAreaHelper.ts

-Now calling required img processing methods, but for full testing need ImageModalDialog implemented to insert image

Process contents of the HTML Area when saving #5131

---

modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/item-view.less

-Something wrong with tree-grid's height calculating, set to auto, but origin of issie is unknown

Fragment Wizard - incorrect location of the dropdown handler #5424

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/security/acl/Access.ts

-access constants translations order misplaced

Incorrect access rights in the Administrator(system.admin) #5529

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less
modules/app/app-users/src/main/js/app/browse/ShowNewPrincipalDialogEvent.ts
modules/app/app-users/src/main/js/app/browse/UserBrowsePanel.ts
modules/app/app-users/src/main/js/app/browse/UserItemsTreeGrid.ts
modules/app/app-users/src/main/js/app/browse/action/NewPrincipalAction.ts
modules/app/app-users/src/main/js/app/create/NewPrincipalDialog.ts
modules/app/app-users/src/main/js/app/create/UserItemTypesTreeGrid.ts
modules/app/app-users/src/main/js/main.ts

_Depends on commits from PR #5532, since it makes changes to the same code.
Please, review and merge this PR, after merging the #5532._

Check permissions and hide "User Store" and "Role" options if user is not User Admin #5494

---

modules/core/core-api/src/main/java/com/enonic/xp/security/EditableRole.java
modules/core/core-api/src/main/java/com/enonic/xp/security/RoleEditor.java
modules/core/core-api/src/main/java/com/enonic/xp/security/UpdateRoleParams.java
modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/ModifyRoleHandler.java
modules/lib/lib-auth/src/main/resources/site/lib/xp/auth.js
modules/lib/lib-auth/src/main/resources/site/lib/xp/examples/auth/modifyGroup.js
modules/lib/lib-auth/src/main/resources/site/lib/xp/examples/auth/modifyRole.js
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/ModifyRoleHandlerTest.java
modules/lib/lib-auth/src/test/resources/site/test/modifyRole-test.js

Implemented `modifyRole` function and handlers.

Lib Auth - Modify role #5703

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/elasticsearch/snapshot/SnapshotServiceImpl.java

Checking configured path when deciding if snapshot repo must be initialized.

Changing snapshot-location does not work (#5827)

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/DuplicateContentProgressListener.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/DuplicateContentJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentService.java
modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentException.java
modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentListener.java
modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentParams.java
modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentsResult.java
modules/core/core-api/src/main/java/com/enonic/xp/node/DuplicateNodeListener.java
modules/core/core-api/src/main/java/com/enonic/xp/node/NodeService.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentCommand.java
modules/core/core-export/src/test/java/com/enonic/xp/core/impl/export/NodeServiceMock.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_duplicate.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_publish_update_publishedTime.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/MoveNodeHandler.java
modules/lib/lib-node/src/test/java/com/enonic/xp/lib/node/MoveNodeHandlerTest.java

Added support for the progress reporter in the duplicate command.
Updated move request handler to receive multiple ids.
**Important:** as discussed, tests will be added in a different task, along with the refactoring `ContentResource`.

DuplicateContentRequest should create a task on the server and respond with taskId #5758

---

modules/core/core-task/src/main/java/com/enonic/xp/impl/task/TaskManagerImpl.java
modules/core/core-task/src/main/java/com/enonic/xp/impl/task/TaskWrapper.java

Issue 5820

---

modules/core/core-api/src/main/java/com/enonic/xp/security/EditableUserStore.java
modules/core/core-api/src/main/java/com/enonic/xp/security/UpdateUserStoreParams.java
modules/core/core-api/src/main/java/com/enonic/xp/security/UserStore.java
modules/core/core-api/src/main/java/com/enonic/xp/security/UserStoreEditor.java
modules/core/core-api/src/test/java/com/enonic/xp/security/UserStoreTest.java
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityServiceImpl.java
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/UserStoreNodeTranslator.java
modules/core/core-security/src/test/java/com/enonic/xp/core/impl/security/SecurityServiceImplTest.java

Added `editor` support for `UserStore` creation and update with `UpdateUserStoreParams`.
Added tests for the new code.

Users App - GraphQL - Update user store #5983

---

modules/lib/lib-admin/src/main/java/com/enonic/xp/lib/admin/AdminLibHelper.java
modules/lib/lib-admin/src/main/resources/lib/xp/admin.js

Added methods to fetch URLs of an admin tool, the Home tool and the Launcher panel (#6028)

Expand lib-admin with methods to retrieve admin urls

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/reader/FileDumpReader.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/dump/DumpServiceImplTest.java

Allow for missing versions-file

Toolbox CLI - Load of dump with skipped versions fails (#5925)

---

modules/lib/lib-thymeleaf/src/main/java/com/enonic/xp/lib/thymeleaf/ThymeleafViewFunctions.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/view/IdProviderUrlFunction.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/view/LoginUrlFunction.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/view/LogoutUrlFunction.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/view/AbstractViewFunctionTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/view/IdProviderUrlFunctionTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/view/LoginUrlFunctionTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/view/LogoutUrlFunctionTest.java

To test you can use app-features in branch issue-49

View functions - idProviderUrl, loginUrl & logoutUrl (#6123)

---

modules/core/core-api/src/main/java/com/enonic/xp/index/ChildOrder.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/FindContentByParentCommand.java

Added child order by `publish` field for client-server homogeneity.

Sort content dialog - Add an option to sort by Published date #6197

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/schema/content/ContentTypeResource.java

ContentTypeFilter incorrectly filters content types in context

---

modules/lib/lib-content/src/main/resources/site/lib/xp/content.js
modules/lib/lib-content/src/test/java/com/enonic/xp/lib/content/CreateMediaHandlerTest.java
modules/lib/lib-content/src/test/resources/site/test/CreateMediaHandlerTest.js

-now setting focal points in lib only if they are set, otherwise default values 0.5 will be used

lib-content sets default value of focalPoint for new media content #6247

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/UpdateIssueJson.java

…issue has been published #6332

Number of assignees disappears from the tab after an issue is published

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/ContentsExistByPathJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ContentPathsJson.java

-Creating resource method for checking if content with such path already exists

Fetch dragged URLs from the ImageSelector #6378

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/schema/mixin/MixinResource.java

-Filtering nulls from site descriptors list to avoid NPE

Can't access content after application is uninstalled #6463

---

modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/XmlFormMapper.java

JsonExceptionMapper - label is required #6461

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/AdminToolHandler.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/AdminToolHandlerWorker.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/AdminToolPortalHandler.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/portal/AdminToolHandlerTest.java
modules/lib/lib-portal/src/main/java/com/enonic/xp/lib/portal/current/GetCurrentAbstractHandler.java
modules/lib/lib-portal/src/test/java/com/enonic/xp/lib/portal/current/GetCurrentContentScriptTest.java
modules/lib/lib-portal/src/test/java/com/enonic/xp/lib/portal/current/GetCurrentSiteConfigScriptTest.java
modules/lib/lib-portal/src/test/java/com/enonic/xp/lib/portal/current/GetCurrentSiteScriptTest.java
modules/portal/portal-api/src/main/java/com/enonic/xp/portal/handler/ControllerHandlerWorker.java

Incorrect URL generation from endpoints under /admin/tool (#6508)

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/AdminPortalHandler.java
modules/portal/portal-api/src/main/java/com/enonic/xp/portal/RenderMode.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/exception/ExceptionRendererImpl.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/DescriptorBasedComponentRenderer.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/PageRenderer.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/TextRenderer.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/LayoutRendererTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/PartRendererTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/TextRendererTest.java

…studio or separate window #6120

Support inline preview mode

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/application/json/ApplicationJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/schema/xdata/XDataResource.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/schema/xdata/XDataResourceTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/schema/xdata/get_content_x_data_duplicated_config.json

…ons with duplicated x-data has been installed #6629

Incorrect handling of multiple x-data entries

---

build.gradle
buildSrc/build.gradle
gradle.properties
gradle/java.gradle
gradle/maven.gradle
modules/docs/build.gradle
modules/runtime/build.gradle
settings.gradle

* Replaced mavenDeployer with maven publishing.
* Made publishing configuration to run before the project evaluation.
* Fixed timeouts, when downloading plugins.

Update publish configuration #6572

---

modules/web/web-impl/src/main/java/com/enonic/xp/web/impl/context/ContextFilter.java

explicit connectors for ContextFilter

Run /api and /status on separate ports #6864

---

modules/core/core-cluster/src/main/java/com/enonic/xp/cluster/impl/ClusterHealthError.java
modules/core/core-cluster/src/main/java/com/enonic/xp/cluster/impl/HealthValidator.java
modules/core/core-cluster/src/test/java/com/enonic/xp/cluster/impl/ClusterManagerImplTest.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/NodeRepositoryServiceImpl.java

Merge https://github.com/enonic/xp/pull/6974 first

Use custom number of replicas for new repositories (#6977)

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/DescriptorBasedComponentDataSerializer.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/PageDataSerializer.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/serializer/PageDataSerializerTest.java

-Now storing component configs by descriptor key (applicationKey + descriptor name)

Component config - Group by descriptor key - Serialization #6953

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/ImageRenderer.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/ImageRendererTest.java

-Also refactored ImageRenderer class

Apply "alt" attribute when rendering image element #6984

---

modules/runtime/src/bin/service.sh
modules/runtime/src/service/init.d/xp
modules/runtime/src/service/install_service.sh

install as service fails (#7074)

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/MarkAsReadyJson.java

-Created backend endpoint to not update content entirely via 'update' url, but just solely workflow state

Implement "Mark as Ready" action #7208

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishContentJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/task/PublishRunnableTask.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/publish_content_with_message.json
modules/core/core-api/src/main/java/com/enonic/xp/content/PushContentParams.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/PublishContentCommand.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/PublishContentHandler.java
modules/lib/lib-content/src/main/resources/lib/xp/content.js
modules/lib/lib-content/src/main/resources/lib/xp/examples/content/publish.js
modules/lib/lib-content/src/test/java/com/enonic/xp/lib/content/PublishContentHandlerTest.java
modules/lib/lib-content/src/test/resources/test/PublishContentHandlerTest.js

Note: Cherry-picked commits from branch  epic-workflow. Will probably cause merge conflict when we merge that branch into master.

Publish message on master

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/issue/IssueJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishRequestScheduleJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/CreateIssueJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/json/UpdateIssueJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueResourceTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/issue/get_issue_scheduled_result.json
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/issue/get_issues_result.json
modules/core/core-api/src/main/java/com/enonic/xp/data/PropertySet.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/CreateIssueParams.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/CreatePublishRequestIssueParams.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/EditableIssue.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/EditablePublishRequestIssue.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/Issue.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/IssueService.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/IssueType.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/PublishRequestIssue.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/PublishRequestIssueSchedule.java
modules/core/core-api/src/main/java/com/enonic/xp/issue/PublishRequestIssueScheduleSerializer.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/IssuePropertyNames.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/IssueServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/UpdateIssueCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/issue/serializer/IssueDataSerializer.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/issue/IssueServiceImplTest_create.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/issue/IssueServiceImplTest_update.java

I have been a little confused why there already is a field called PublishRequest in the old Issue class. Should the PublishRequest field in the Issue class not be moved into the new PublishRequestIssue class.
Anyway then I have covered all the points in the issue description. Looking forward to get some feedback.

Workflow - PublishRequest

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/ContentVersionJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/ContentVersionPublishInfoJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishContentJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/task/PublishRunnableTask.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/publish_content_with_message.json
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersion.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersionPublishInfo.java
modules/core/core-api/src/main/java/com/enonic/xp/content/PushContentParams.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/PublishContentCommand.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_publish.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/PublishContentHandler.java
modules/lib/lib-content/src/main/resources/lib/xp/content.js
modules/lib/lib-content/src/main/resources/lib/xp/examples/content/publish.js
modules/lib/lib-content/src/test/java/com/enonic/xp/lib/content/PublishContentHandlerTest.java
modules/lib/lib-content/src/test/resources/test/PublishContentHandlerTest.js

This branch is based on branch [issue-7181-master](https://github.com/enonic/xp/tree/issue-7181-master), so pull request #7197 is kind of redundant at this point.

ContentVersion - Publish information - Issue 7198

---

modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentQuery.java
modules/core/core-api/src/main/java/com/enonic/xp/content/FindContentByQueryResult.java
modules/core/core-api/src/main/java/com/enonic/xp/content/FindContentIdsByQueryResult.java
modules/core/core-api/src/test/java/com/enonic/xp/content/query/ContentQueryTest.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentQueryNodeQueryTranslator.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/FindContentByQueryCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/FindContentIdsByQueryCommand.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/QueryContentHandler.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/QueryHighlightParams.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/mapper/ContentsResultMapper.java
modules/lib/lib-content/src/main/java/com/enonic/xp/lib/content/mapper/HighlightMapper.java
modules/lib/lib-content/src/main/resources/lib/xp/content.js
modules/lib/lib-content/src/main/resources/lib/xp/examples/content/query.js
modules/lib/lib-content/src/test/java/com/enonic/xp/lib/content/QueryContentHandlerTest.java
modules/lib/lib-content/src/test/resources/test/QueryContentHandlerTest.js
modules/lib/lib-node/src/main/resources/lib/xp/examples/node/query.js

Highlight - Content level #7265

---

modules/core/core-api/src/main/java/com/enonic/xp/auditlog/AuditLogConstants.java
modules/core/core-api/src/main/java/com/enonic/xp/auditlog/AuditLogService.java
modules/core/core-audit/src/main/java/com/enonic/xp/core/impl/auditlog/AuditLogRepoInitializer.java
modules/core/core-audit/src/main/java/com/enonic/xp/core/impl/auditlog/AuditLogServiceImpl.java

Note: Tests and Codacy problems fixed in the last pull request: #7295

Audit Log - Initializer (#7248)

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResolvePublishContentResultJson.java
modules/admin/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/resolve_publish_content.json

…rd if all content is going to be deleted #7322

Admin - ResolvePublishContent - Add pending delete flag

---

modules/server/server-config/src/main/java/com/enonic/xp/server/internal/config/ConfigLoader.java

ConfigLoader FileReader is not properly closed #7340

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/schema/content/LocaleMessageResolver.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/schema/content/LocaleMessageResolverTest.java
modules/core/core-api/src/main/java/com/enonic/xp/i18n/MessageBundle.java
modules/core/core-i18n/src/main/java/com/enonic/xp/core/impl/i18n/MessageBundleImpl.java

Handle localization format errors

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/branch/storage/NodeFactory.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/NodeStorageService.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/NodeStorageServiceImpl.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/storage/NodeStorageServiceImplTest.java

- implemented
- added unit test

Get node by version ID - Storage #7320

---

modules/core/core-api/src/main/java/com/enonic/xp/node/NodeService.java
modules/core/core-export/src/test/java/com/enonic/xp/core/impl/export/NodeServiceMock.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/branch/storage/NodeFactory.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/GetNodeByIdAndVersionIdCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/GetNodeByPathAndVersionIdCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/NodeStorageService.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/NodeStorageServiceImpl.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/GetNodeByIdAndVersionIdCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/GetNodeByPathAndVersionIdCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/NodeServiceImplTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/storage/NodeStorageServiceImplTest.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/GetNodeHandler.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/GetNodeHandlerParams.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/NodeHandler.java
modules/lib/lib-node/src/main/java/com/enonic/xp/lib/node/NodeKey.java
modules/lib/lib-node/src/main/resources/lib/xp/examples/node/get-3.js
modules/lib/lib-node/src/main/resources/lib/xp/node.js
modules/lib/lib-node/src/test/java/com/enonic/xp/lib/node/GetNodeHandlerTest.java

Get node by version ID - Node library #7321

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/CmsResourceDynamicFeature.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/schema/content/ContentTypeResource.java

-ContentTypeResource uses contentService that relies on knowing current layer

ContentTypeFilter is not aware of layers #7368

---

modules/core/core-api/src/main/java/com/enonic/xp/content/ContentNotFoundException.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentService.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/GetContentByIdAndVersionIdCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/GetContentByPathAndVersionIdCommand.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/GetContentByIdAndVersionIdCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/GetContentByPathAndVersionIdCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/GetNodeByIdAndVersionIdCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/GetNodeByPathAndVersionIdCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/storage/NodeStorageServiceImplTest.java

Get content by version ID #7367

---

modules/core/core-api/src/main/java/com/enonic/xp/dump/RepoDumpResult.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/RepoDumper.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/serializer/json/RepoDumpResultJson.java
modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/RepoDumpResultJson.java
modules/server/server-rest/src/test/resources/com/enonic/xp/impl/server/rest/task/DumpRunnableTaskTest-dump_result.json

Dump failing on missing blob #7296

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/RevertContentJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java

Content Revert - Content Resource #7388

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/exception/ExceptionRendererImpl.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/exception/ExceptionRendererImplTest.java

Generic Custom error handling #7404

---

modules/itest/itest-core/src/test/java/com/enonic/xp/core/repo/vacuum/versiontable/VersionTableCleanupTaskTest.java

Don't rely on randomness 
because we assert exact number of changes.

VersionTableCleanupTaskTest is failing regularly on Concourse #7434

---

gradle/java.gradle
modules/tools/testing/build.gradle
modules/tools/testing/src/main/java/com/enonic/xp/testing/ScriptTestSupport.java

Made testing framework to run on both Junit4 (to support libraries which use it) and Junit5 (sice we use Junit5 internally)

All unit tests fail on app-users #7467

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentService.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/GetBinaryByVersionCommand.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/GetBinaryByVersionCommandTest.java

fixed revert for attachments of content

Revert of attachments does not work #7470

---

gradle/java.gradle
modules/web/web-impl/build.gradle
modules/web/web-jetty/build.gradle
modules/web/web-session/build.gradle
modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/IgniteSessionDataStore.java
modules/web/web-session/src/test/java/com/enonic/xp/web/session/impl/IgniteSessionDataStoreTest.java

Updated to the current stable 9.4.21

Update Jetty to version >= 9.4.12 #7449

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentService.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java

- return ContentVersionJson instead of ContentJson for the revert action
- remove and create attachments if needed, to exclude a creation new a version of content

Give a different message when a version was not reverted #7487

---

modules/core/core-extractor/src/main/java/com/enonic/xp/extractor/impl/BinaryExtractorImpl.java
modules/core/core-extractor/src/main/java/com/enonic/xp/extractor/impl/config/ExtractorConfig.java
modules/core/core-extractor/src/main/java/com/enonic/xp/extractor/impl/config/ExtractorConfigImpl.java
modules/core/core-extractor/src/main/java/com/enonic/xp/extractor/impl/config/ExtractorConfigMap.java
modules/core/core-extractor/src/test/java/com/enonic/xp/extractor/impl/BinaryExtractorImplTest.java
modules/core/core-extractor/src/test/java/com/enonic/xp/extractor/impl/config/ExtractorConfigImplTest.java
modules/core/core-extractor/src/test/resources/com/enonic/xp/extractor/impl/config/extractor-complete.properties
modules/core/core-extractor/src/test/resources/com/enonic/xp/extractor/impl/config/extractor-disabled.properties
modules/core/core-extractor/src/test/resources/com/enonic/xp/extractor/impl/config/extractor-invalid.properties
modules/runtime/src/home/config/com.enonic.xp.extractor.cfg

Make binary extractor max length configurable #7294

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/postprocess/PostProcessorImpl.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/postprocess/PostProcessorImplTest.java

Handle POST-requests in parts on the page-url #7585

---

gradle/java.gradle
modules/core/core-api/build.gradle
modules/launcher/launcher-impl/build.gradle
modules/launcher/launcher-impl/src/main/resources/META-INF/config/system.properties
modules/runtime/build.gradle
modules/tools/testing/build.gradle

This time all logging is delegated to framework to avoid classloading issues.

Update slf4j to 1.7.29 #7611

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentService.java
modules/core/core-api/src/main/java/com/enonic/xp/content/GetActiveContentVersionParams.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java

- refactored the getActiveVersion method of ContentService

Content Revert - Refactor getActiveVersion #7545

---

modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ScriptLogger.java
modules/script/script-impl/src/test/resources/myapplication/logging/log-test.js

JS Logger - Handle throwable #6905

JS Logger - Handle throwable #6905

---

build.gradle
buildSrc/build.gradle

I tested the two other plugins that produced HTML.  Had problems with both.  The documentation is a lot about Android, and I wonder if they were made to work with Android and that Java is just and afterthought, so either way, I do think this is the best plugin, even if the report generated is not all that easy to work with.

#7761 - Correct configuration of the gradle license plugin.

---

.github/workflows/gradle.yml
settings.gradle

https://github.com/enonic/xp/issues/7845#issuecomment-590336697

Turn on Gradle build scans on Github Actions #7845

---

modules/core/core-event/src/main/java/com/enonic/xp/core/impl/event/cluster/ClusterEventSender.java

- added a warning log in cases when transport protocol could not send data via socket. It does not help to "recover" from undelivered events, but helps to debug some cluster conditions when some nodes are not reachable (TCP connection closed).
- in addition changed thread which would handle an error. It is an overkill to use MANAGEMENT pool for simple logging.

No logs for undelivered events #8018

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/elasticsearch/query/translator/NodeVersionQueryTranslator.java

Version translator uses getSize() in getBatchSize() #8095

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/task/ApplyPermissionsTaskMessageGenerator.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/task/ApplyPermissionsRunnableTaskTest.java

Wrong message when insufficient permissions to change project access mode #8129

---

modules/web/web-api/src/main/java/com/enonic/xp/web/WebRequest.java
modules/web/web-impl/src/test/java/com/enonic/xp/web/impl/handler/WebDispatcherServletTest.java

(cherry picked from commit ca0b5a67672469f8f0117ccd3b03ce7c4a14b56f)

WebRequest "deduplicates" equal query params #8210

---

modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ParentProjectSyncTask.java
modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java
modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectNodeEventListener.java
modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectServiceImpl.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/AbstractContentServiceTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/project/ProjectServiceImplTest.java

POC: Initiate Sync job immediately after child project gets created #8215

---

gradle/versions.gradle
modules/core/core-mail/src/main/java/com/enonic/xp/mail/impl/MailServiceImpl.java
modules/runtime/build.gradle

(cherry picked from commit cfab63e11909fcc9b975ca8ce1f7ce581a53da4c)

Can't send mail with attachment #8293

---

gradle/java.gradle
gradle/versions.gradle

Test Dependency updates Trail 7.5 #8345

---

gradle/versions.gradle

Jackson Dependency updates Trail 7.5 #8345

---

gradle/versions.gradle

Jetty and Metrics Dependency updates Trail 7.5 #8345

---

gradle/versions.gradle

Revert "Tika Dependency updates Trail 7.5 #8345"

---

modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java
modules/core/core-api/src/main/java/com/enonic/xp/project/NameValueResolver.java
modules/core/core-api/src/main/java/com/enonic/xp/project/ParentProjectSynchronizer.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java

…e same path already exists in the current layer? #8358

Resolve name conflict when trying to replicate a new item with existing name

---

modules/core/core-event/src/main/java/com/enonic/xp/core/impl/event/cluster/ClusterEventReceiver.java
modules/core/core-event/src/test/java/com/enonic/xp/core/impl/event/cluster/ClusterEventReceiverTest.java

(cherry picked from commit b8ababe9bc29c5cc15e2ca8cd26d709ac9b5bf69)

Don't deliver distributed event to the sender itself #8429

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/DumpServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/RepoLoader.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/reader/AbstractEntryProcessor.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/reader/BranchEntryProcessor.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/reader/CommitEntryProcessor.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/reader/VersionEntryProcessor.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/UpdateRepositoryEntryParams.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/dump/DumpServiceImplTest.java
modules/core/core-repo/src/testFixtures/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java

(cherry picked from commit 20d45ad83b522e90203c1be723ff51ca0dd46d3c)

Repository attachments get lost after loading a dump #8208

---

gradle/versions.gradle
gradle/wrapper/gradle-wrapper.properties
modules/portal/portal-owasp/build.gradle

Dependency updates Trail 7.6 #8477

---

gradle/java.gradle
modules/core/core-api/src/main/java/com/enonic/xp/inputtype/InputTypeName.java
modules/core/core-api/src/test/java/com/enonic/xp/inputtype/InputTypeNameTest.java

It is a first attempt to use Equalsverifier that #7377

InputTypeName issues #8470

---

NOTICE.txt
modules/core/core-api/src/main/java/com/enonic/xp/index/HtmlStripper.java
modules/core/core-api/src/test/java/com/enonic/xp/index/HtmlStripperTest.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/page/region/CreateFragmentCommand.java
modules/core/core-internal/build.gradle
modules/core/core-internal/src/main/java/com/enonic/xp/core/internal/HtmlHelper.java
modules/core/core-macro/build.gradle
modules/core/core-macro/src/main/java/com/enonic/xp/impl/macro/MacroParser.java
modules/portal/portal-impl/build.gradle
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/macro/EmbedIframeMacroProcessor.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/macro/EmbedIframeMacroProcessorTest.java

Second attempt, as previous one has problems with OSGi

Replace StringEscapeUtils with alternatives #8533

---

modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExportsCache.java
modules/script/script-impl/src/test/java/com/enonic/xp/script/impl/executor/ScriptExportsCacheTest.java

(cherry picked from commit 5a1b54b049dff64e5ecd4e2543c1d96204800695)

Dev mode is broken in 7.6 #8604

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueMailMessageGenerator.java

(cherry picked from commit 0ca9ecf906d125591dd18d4d1303b96c59a28ef2)

Escape HTML in Issue emails #8659

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java

(cherry picked from commit e9d25f2f0aea0b4bcca095d4cdf112b2c2eed3f9)

Allow only http and https for external content upload #8673

---

buildSrc/build.gradle
gradle/java.gradle
gradle/versions.gradle
gradle/wrapper/gradle-wrapper.properties
settings.gradle

jcenter -> mavenCentral
gradle 6.8.2 -> 6.8.3
equalsverifier 3.5.4 -> 3.6
mockito 3.7.7 -> 3.9.0
bnd 5.2.0 -> 5.3.0
ben-manes.versions 0.36.0 -> 0.38.0

build dependency updates #8655

---

modules/web/web-vhost/src/main/java/com/enonic/xp/web/vhost/impl/VirtualHostFilter.java
modules/web/web-vhost/src/main/java/com/enonic/xp/web/vhost/impl/VirtualHostInternalHelper.java
modules/web/web-vhost/src/main/java/com/enonic/xp/web/vhost/impl/config/VirtualHostConfigMap.java
modules/web/web-vhost/src/main/java/com/enonic/xp/web/vhost/impl/mapping/VirtualHostMapping.java
modules/web/web-vhost/src/test/java/com/enonic/xp/web/vhost/impl/VirtualHostFilterTest.java
modules/web/web-vhost/src/test/java/com/enonic/xp/web/vhost/impl/VirtualHostInternalHelperTest.java
modules/web/web-vhost/src/test/java/com/enonic/xp/web/vhost/impl/VirtualHostResolverImplTest.java
modules/web/web-vhost/src/test/java/com/enonic/xp/web/vhost/impl/config/VirtualHostConfigMapTest.java
modules/web/web-vhost/src/test/java/com/enonic/xp/web/vhost/impl/mapping/VirtualHostMappingTest.java

Trailing slash is removed from rawPath #8858

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/main/MainExecutor.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/main/MainExecutorTest.java

(cherry picked from commit 5675f96d2ca405e75cfa8898d72f1bc2d89f78f6)

main.js exception is swallowed #8844

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentListTitleResolver.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentListTitleResolverTest.java

(cherry picked from commit 927dce8be50c1c3e6e3cc8f9b899d18588f0cb0c)

NPE after deleting a content type and trying to fetch the list #8901

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/PortalRequestAdapter.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/url/PortalUrlBuilder.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/url/ImageUrlBuilderTest.java
modules/runtime/src/home/config/com.enonic.xp.web.jetty.cfg
modules/web/web-impl/src/main/java/com/enonic/xp/web/impl/handler/WebDispatcherServlet.java
modules/web/web-jetty/src/main/java/com/enonic/xp/web/jetty/impl/JettyConfig.java
modules/web/web-jetty/src/main/java/com/enonic/xp/web/jetty/impl/configurator/ConnectorConfigurator.java

(cherry picked from commit 54fef082f61ca55ba1780bc31e5a5e14cb9e0c8a)

Path traversal in assets (and other) services #8981

---

modules/core/core-elasticsearch/src/main/java/com/enonic/xp/elasticsearch/impl/NodeSettingsBuilder.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/elasticsearch/snapshot/SnapshotServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImpl.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/elasticsearch/snapshot/SnapshotServiceImplTest.java
modules/core/core-repo/src/testFixtures/java/com/enonic/xp/repo/impl/elasticsearch/EmbeddedElasticsearchServer.java
modules/core/core-repo/src/testFixtures/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java

(cherry picked from commit 004388b0d7ef61482d18c02becfe08784ce99f36)

Snapshot Restore may leave repositories half-initialized #8879

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/index/ReindexExecutor.java
modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/ModelToStringHelper.java
modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/ReindexResultJson.java

Since the format of returned value is strictly defined (value is parsed by CLI for some reason) added custom JsonFormat
Also made a correction to duration, so it is a positive value.

reindex command causes an error pointing to ReindexResultJson #9085

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/DuplicateNodeResult.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommandPerformanceTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/ResolveSyncWorkCommandTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ProjectContentEventListenerTest.java

#9239 Duplicate of a content is inherited in layer without child elements

---

modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/DeletePrincipalHandlerTest.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/RemoveMembersHandlerTest.java
modules/lib/lib-repo/src/test/java/com/enonic/xp/lib/repo/RefreshScriptTest.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ErrorHelper.java

revert logic for IllegalArgumentException

(Still) Cannot trigger 404 when filter applied #9349

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ParentContentSynchronizerTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ProjectContentEventListenerTest.java

Content changes in parent project are not synced to layer after restore from archive #9468 

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateMediaCommand.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_media.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ParentContentSynchronizerTest.java

#9520 Uploading a new attachment won't change workflow state of the content

---

modules/blobstore/blobstore-file/src/main/java/com/enonic/xp/internal/blobstore/file/FileBlobRecord.java
modules/blobstore/blobstore-file/src/main/java/com/enonic/xp/internal/blobstore/file/FileBlobStore.java
modules/blobstore/blobstore-file/src/test/java/com/enonic/xp/internal/blobstore/file/FileBlobStoreTest.java
modules/core/core-api/src/main/java/com/enonic/xp/blob/BlobKey.java
modules/core/core-api/src/main/java/com/enonic/xp/blob/Segment.java
modules/core/core-api/src/main/java/com/enonic/xp/blob/SegmentLevel.java
modules/core/core-app/src/test/java/com/enonic/xp/core/impl/app/ApplicationServiceImplTest.java
modules/core/core-blobstore/src/test/java/com/enonic/xp/internal/blobstore/cache/CachedBlobStoreTest.java
modules/core/core-blobstore/src/test/java/com/enonic/xp/internal/blobstore/readthrough/ReadThroughBlobStoreTest.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/writer/AbstractDumpWriter.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/vacuum/blob/AbstractBlobVacuumCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/vacuum/segment/SegmentVacuumCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/vacuum/versiontable/VersionTableVacuumCommand.java

Vacuum does not release directory locks properly #9646

---

modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/resolver/RealOverVirtualApplicationUrlResolver.java
modules/core/core-app/src/test/java/com/enonic/xp/core/impl/app/resolver/RealOverVirtualApplicationUrlResolverTest.java

add config to disable and set priority for virtual apps #9624

---

modules/lib/lib-node/src/main/resources/lib/xp/node.ts

* Made repo connection classes local to prevent leaking `ScriptValue` outside of the TS files via constructor -> `NodeHandler` -> `create(node: ScriptValue)` and many others.
* Fixed `NodeHandler.delete` method, making it return `string[]` instead of a `boolean` (it actually returns array of the deleted ids).
* Made `RepoConnection.refresh()` to use `'ALL'` as a default parameter value, so the parameter is no longer a required one.

Fix lib-node compilation problem when included as dependency #9704

---

modules/lib/lib-io/src/main/resources/lib/xp/io.ts
modules/lib/lib-node/src/main/resources/lib/xp/node.ts

Prevented class from being exported.
Updated docs.

Refactor IO library Resource class #9741

---

modules/lib/build.gradle
modules/lib/core/README.md
modules/lib/core/index.d.ts
modules/lib/lib-auditlog/src/main/resources/lib/xp/auditlog.ts
modules/lib/lib-auth/src/main/resources/lib/xp/auth.ts
modules/lib/lib-content/README.md
modules/lib/lib-content/src/main/resources/lib/xp/content.ts
modules/lib/lib-context/src/main/resources/lib/xp/context.ts
modules/lib/lib-io/src/main/resources/lib/xp/io.ts
modules/lib/lib-node/src/main/resources/lib/xp/node.ts
modules/lib/lib-portal/src/main/resources/lib/xp/portal.ts
modules/lib/lib-scheduler/src/main/resources/lib/xp/scheduler.ts
modules/lib/lib-schema/src/main/resources/lib/xp/schema.ts
modules/lib/lib-task/src/main/resources/lib/xp/task.ts
modules/lib/package-lock.json
modules/lib/package.json

Replaced local types with core types.
Updated lib root dependencies.
Removed unused lib root dependencies.
Updated build.

Core Libraries shared types imports #9729

---

modules/lib/lib-node/src/main/resources/lib/xp/node.ts

NodeMultiRepoQueryResult type is wrong #9805

---

modules/runtime/src/bin/server.sh

add java_opt to use system File Descriptor Limit value on MacOS #9932

---

modules/lib/lib-node/src/main/resources/lib/xp/node.ts

I also wrote some tests https://github.com/enonic/enonic-js-utils/blob/main/test/types/Node.test-d.ts

TypeScript: Node<> Generic: Too strict #9895

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/ApplyNodePermissionsCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/CreateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/CreateRootNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/LoadNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/MoveNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/ReorderChildNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/SetNodeChildOrderCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/SetRootPermissionsCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/UpdateNodeCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/RepositoryEntryServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/NodeStorageService.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/NodeStorageServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/NodeVersionData.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/repository/RepositoryServiceActivatorTest.java

target branches are upgraded with obsolete version data #10454

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/mapping/MediaServiceMappingHandler.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/handler/mapping/MediaServiceMappingHandlerTest.java

Ability to intercept media endpoint

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/app/MainWebHandler.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/AdminToolPortalHandler.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/portal/WidgetHandler.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/tool/AdminToolDescriptorServiceImpl.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/app/MainWebHandlerTest.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/portal/AdminToolHandlerTest.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/portal/WidgetHandlerTest.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/tool/AdminToolDescriptorServiceImplTest.java
modules/lib/lib-admin/src/main/resources/lib/xp/admin.ts
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/DefaultContextPathVerifier.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/SlashApiHandler.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/idprovider/PortalRequestAdapter.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/handler/AssetHandlerTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/handler/MediaHandlerTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/handler/SlashApiHandlerTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/idprovider/IdProviderControllerServiceImplTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/idprovider/PortalRequestAdapterTest.java
modules/web/web-impl/src/main/java/com/enonic/xp/web/impl/trace/TraceWebFilter.java

This reverts commit 485e8951b64c76be0124893b40e76cdf4f299d38.

Revert "Remove tool path segment for admin tools #10625"

---

modules/app/app-system/src/main/java/com/enonic/xp/app/system/VacuumTaskHandler.java
modules/app/app-system/src/test/java/com/enonic/xp/app/system/VacuumTaskHandlerTest.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/vacuum/VacuumServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/vacuum/snapshots/SnapshotsVacuumTask.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/vacuum/VacuumServiceImplTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/vacuum/snapshots/SnapshotsVacuumTaskTest.java

Vacuum should delete old snapshots #10691
(cherry picked from commit c5a0178f0a13acbae40ec327440d88b36c726c12)

Vacuum should delete old snapshots #10691 (#10791)

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/websocket/WebSocketEntryImpl.java

- Using async RemoteEndpoint for sending a message via Websocket

WebSocket: message is sent via non-async RemoteEndpoint #10759

---

modules/lib/lib-auth/src/main/resources/lib/xp/auth.ts
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/LoginHandlerTest.java
modules/lib/lib-auth/src/test/resources/test/login-test.js

(cherry picked from commit 989c5488bd7f07cfb51c6b0f12efad4401a3fbf6)

Improve type definition for login #10487

---

modules/core/core-api/src/main/java/com/enonic/xp/security/EditableUser.java
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/PrincipalNodeTranslator.java
modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityServiceImpl.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/security/SecurityServiceImplTest.java
modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/ChangePasswordHandler.java
modules/lib/lib-auth/src/main/resources/lib/xp/auth.ts
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/ChangePasswordHandlerTest.java
modules/lib/lib-auth/src/test/resources/test/changePassword-test.js

Password clearing #10846
(cherry picked from commit 530ccf35d3bac087e9aeecf691d3c727febf7aaa)

Password clearing #10846 (#10847)

---

modules/lib/core/index.d.ts
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/createUser.js
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/findPrincipals.js
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/findUsers.js
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/getMembers.js
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/getPrincipal.js
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/getUser.js
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/login.js
modules/lib/lib-auth/src/main/resources/lib/xp/examples/auth/modifyUser.js
modules/lib/lib-auth/src/test/resources/com/enonic/xp/lib/auth/PrincipalsResultMapperTest-userPrincipals.json
modules/lib/lib-auth/src/test/resources/test/createUser-test.js
modules/lib/lib-auth/src/test/resources/test/findPrincipals-test.js
modules/lib/lib-auth/src/test/resources/test/getMembers-test.js
modules/lib/lib-auth/src/test/resources/test/getPrincipal-test.js
modules/lib/lib-auth/src/test/resources/test/getUser-test.js
modules/lib/lib-auth/src/test/resources/test/login-test.js
modules/lib/lib-auth/src/test/resources/test/modifyUser-test.js
modules/lib/lib-common/src/main/java/com/enonic/xp/lib/common/PrincipalMapper.java
modules/lib/lib-common/src/test/resources/com/enonic/xp/lib/common/PrincipalMapperTest-user.json
modules/lib/lib-context/src/test/resources/test/context-test.js

(cherry picked from commit a024b9f1883714453b6dc3159680d2788dcc10dd)

Add the `hasPassword` field to the user JS object #10848

---

modules/lib/lib-event/src/main/resources/lib/xp/event.ts

Added explicit info about wildcards in type parameter.

Update lib-event doc

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/NodeEvents.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/ApplyNodePermissionsCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/node/NodeServiceImplTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/node/PatchNodeCommandTest.java

#10995 applyPermissions and node.patch must not commit

---

modules/core/core-api/src/main/java/com/enonic/xp/archive/ArchiveContentParams.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentConstants.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ArchiveContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_archive.java

Enable providing a message when archiving content #11164
