enonic/xp

modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/checkbox.less
modules/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

Fixed the checkbox `:focus` styles.

CMS-4912 Wizard - Input type checkbox, not highlighted when in focus

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/module-manager/js/app/browse/ModuleTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/browse/UserItemsTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/grid/Grid.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/responsive/ResponsiveItem.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

Boost up the `TreeGrid.postLoad` method.
Replaced the jQUery code with the direct access from the SlickGrid
itself.
Added a single canvas resize call on resize for each grid.

CMS-4946 Live Edit - Performance problems caused by TreeGrid.postLoad

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageTemplateOptionViewer.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/browse/UserTreeGridItemViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/NamesView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentPath.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatusViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentVersionViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelectorViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/PageDescriptorViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/PageTemplateViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/region/LayoutDescriptorViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/region/PartDescriptorViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionComponentViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/image/ImageComponentViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/part/PartComponentViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/module/ModuleViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/schema/content/ContentTypeSummaryViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/NamesAndIconViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/security/PrincipalViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/security/acl/AccessControlEntryViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/security/acl/UserStoreAccessControlEntryViewer.ts

Added `NamesAndIconViewer` parent class for the viewers with
`NamesAndIconView`.
Replaced `setHtml()` with the `setText()` in the path and `NameView`.
Updated all the viewers.
Make the viewers to display `<Display Name>`, `<name>` and `<unnamed>`
instead of the empty fields.

CMS-5058 Unnamed - Fix presentation of "Unnamed" in browse lists etc

---

modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/new/new-content-dialog.less

Corresponding styles adjusted to hide "Recently used" column when screen is less then 360px and make another column 100% width

CMS-5105 Modal windows - Fix newContentDialogue

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/action/PreviewContentAction.ts

Added focus call for bringing preview window to front, but it may fail due to user settings and the window isn't guaranteed to be frontmost before this method returns.

CMS-5152 Preview has stopped working

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/create/NewContentDialog.ts

Reproduced only for new content dialog - when dialog is opened first time it's content types are not yet loaded, so positioning is done over initial size of window, however when data finishes loading size of content div increses what leads to modal window stretching according to css limits; repositioning is required after data loaded.

CMS-5182 Modal window - Modal window often positioned low on first load

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts

Status element was not correctly set in case of uploading - html as pure text was set instead of appending progress bar as a child

CMS-5171 Upload - html characters visible in status field during upload

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabMenu.ts

SortTabMenu's parent TabMenu was recently changed, that broke sorting behaviour.
Updated required method in TabMenu to correctly remove all navigation items when needed.

CMS-5167 Sorting - Sorting is buggy

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar.less

-fix alignment of icon when tabs are open and screen <540px (previously icon shifted 10 px right)

CMS-5166 Admin UI - Show app name by default - even in mobile view

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/filter/ContentBrowseFilterPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/ContentQueryRequest.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/query/ContentQuery.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts

Implemented postload in the filter.
Removed `TreeGrid.stash`, as deprecated.

XP-18 Browse - Infinite scrolling not working on search results

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/UserAppPanel.ts

Replaced "New" with "Unnamed" for the new tabs.

XP-93 wizard tab - name fixups

---

modules/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelectorSelectedOptionsView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/time/DatePicker.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePicker.ts

-In order to correctly hide popup - moved outside click listener event handling one level up - to the level of popup parent, not popup itself 
-Improved tab navigation behavior, including shift+tab cases

XP-116 Datetime, date and time - picker boxes remain open after moving focus to another input

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts

- fixed resolveContentNameForUpdateRequest()  - now it can handle all situations when contentWizardHeader name is empty
- Made Publish button to be disabled when Wizard's content is invalid

XP-211 Wizard tab - Invalid content blocks save and closing of tab

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/SortContentDialog.ts

-keys were unbinded for sort modal dialog when closing because it contains treegrid which close handler was triggering keys unbinding after modal dialog close handler

XP-135 Grid - keyboard operations stop working after sortting

---

modules/core-api/src/main/java/com/enonic/xp/content/attachment/Attachment.java
modules/core-api/src/main/java/com/enonic/xp/content/attachment/Attachments.java
modules/core-api/src/test/java/com/enonic/xp/content/attachment/AttachmentsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/attachment/CreateAttachmentTest.java
modules/core-api/src/test/java/com/enonic/xp/content/attachment/CreateAttachmentsTest.java
modules/core-api/src/test/java/com/enonic/xp/content/attachment/UpdateAttachmentsParamsTest.java
modules/core-api/src/test/java/com/enonic/xp/support/AbstractImmutableEntityListTest.java

- added missing size param to Attachment.Builder
- made Attachments.add(iterable) public to cover it with tests

XP-246 Add more unit tests for content.attachment package in API

---

modules/core-api/src/main/java/com/enonic/xp/content/query/ContentQueryHit.java
modules/core-api/src/test/java/com/enonic/xp/content/query/ContentQueryHitTest.java
modules/core-api/src/test/java/com/enonic/xp/content/query/ContentQueryResultTest.java
modules/core-api/src/test/java/com/enonic/xp/content/query/ContentQueryTest.java

-added more unit tests for data package 'com.enonic.xp.content.query' so we cover more than 85% line coverage.

XP-248 Add more unit tests for content.query package in API

---

modules/core-api/src/test/java/com/enonic/xp/schema/relationship/RelationshipTypeTest.java

- Used org.junit.Assert instead of the deprecated junit.framework.Assert

XP-244 Add more unit tests for schema package in API

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/radio-group.less
modules/admin-ui/src/main/resources/web/admin/common/styles/reset.less

- Made radio inputs to ignore browser appearance settings
- Added same property value for firefox as for chrome for consistency
- Adjusted styling for radio input. Verified adjusted styling with Chrome and FF

XP-268 Radio buttons are not visible for input type Single Selector

---

modules/admin-ui/src/main/resources/web/admin/common/js/util/DateHelper.ts
modules/admin-ui/src/main/resources/web/admin/common/js/util/DateTime.ts
modules/admin-ui/src/main/resources/web/admin/common/js/util/Timezone.ts

...mezone
- As on the back-end an Instant is used as a backing type - DateTime comes from back-end in UTC format, which was not expected by DateTime domain object on the front-end.

XP-315 The dateTime value sent in update content must contain correct timezone

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/singleselector/SingleSelector.ts

- Made Single Selector to extend BaseInputTypeSingleOccurrence instead of BaseInputTypeNotManagingAdd in order to reflect inability to have more that one input

XP-267 Remove button 'Add' from the Single Selector Form View Panel

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/FormItemOccurrences.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/input/input-occurrence-view.less

1. Fixed disappearing right border of the editor
2. Fixed crash when adding a new editor after rearranging existing ones

Xp 253: Fix reordering of TinyMCE inputs

---

modules/core-impl/src/test/java/com/enonic/xp/core/impl/content/CreateContentCommandTest.java

Please, review if provided tests are sufficient.
Note that there is only one public method available for CreateContentCommand.

XP-324 Add integration-test for CreateContentCommand

---

modules/core-api/src/main/java/com/enonic/xp/media/MediaInfo.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/ContentTypeFromMimeTypeResolver.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/CreateMediaCommand.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/UpdateMediaCommand.java

- [Fixed] CreateMedia and UpdateMedia commands to use value detected by MediaInfoService for mimetype when "application/octet-stream" type is within the request params.
- Added"application/x-rar-compressed" type to MimeTypeResolver

XP-339 Improve detection of media type for up\loaded content

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentIconResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageHelper.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageHelperImpl.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentImageResource.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ImageParams.java
modules/core-api/src/main/java/com/enonic/xp/media/MediaInfoService.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/media/MediaInfoServiceImpl.java

When creating image attachments besides source one we use ImageIO that is not preserving image metadata such as image orientation. Thus when fethcing image not from source attachment and trying to get it orientation we won't get expected result. So:
[Added] Added 'tiffOrientation' entry to Content's extraData when processing newly added image. Previously only 'Orientation' image metadata was taken into Content's extraData but it is pure text which is not static (may vary through devices). 'tiffOrientation' is a number according to specification.
Updated and refactored required code

XP-352 Preserve image orientation in image thumbnails

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TinyMCE.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/form/inputtype/text/tinymce.less

-[Updated] Updated toolbar of TinyMCE editor to be 'sticky', i.e. toolbar always stays visible

XP-402 TinyMCE Editor - make toolbar floating

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/time/DateTime.ts

-Found and fixed  issue with check for value breaking required contracts (incorrect condition)
-Found and fixed issue with trying to convert null value into DateTime (added check for null)

XP-400 Input of type DateTime does not validate for required

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/SelectionPublishItem.ts

- [Modified] ContentPublishDialog to show compare statuses as in a content tree grid
- [Modified] includeChildren to show children count in case of initially requested to resolve items were not returned due to Online status

XP-495 Styling of publish status in publish wiz

---

modules/core-api/src/main/java/com/enonic/xp/content/PushContentRequests.java
modules/core-api/src/main/java/com/enonic/xp/node/ResolveSyncWorkResult.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/PushContentCommand.java
modules/core-impl/src/main/java/com/enonic/xp/core/impl/content/PushContentRequestsFactory.java
modules/core-impl/src/test/java/com/enonic/xp/core/impl/content/PushContentCommandTest.java
modules/core-impl/src/test/java/com/enonic/xp/core/impl/content/ResolvePublishDependenciesCommandTest.java
modules/core-repo/src/main/java/com/enonic/wem/repo/internal/entity/ResolveSyncWorkCommand.java
modules/core-repo/src/test/java/com/enonic/wem/repo/internal/entity/ResolveSyncWorkCommandTest.java

- [Modified] Push Content request and ResolveSyncWorkCommand to manage initially published node more correctly via adding initialNodeId field to ResolveSyncWorkResult
- [Modified] tests

XP-494 Publish parent of modified content broken wizard

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TinyMCE.ts

-[Fixed] Fixed TinyMCE to correctly react on InputOccurence's giveFocus() event. In createInputOccurrenceElement() DivEL wrapper for tinymce was returned, and calling giveFocus() on it was not setting focus on editor area.

XP-509 TinyMCE - set focus inside editor after adding a new instance

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageInspectionPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/PageModel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/layout/LayoutComponentView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/part/PartItemType.ts

- turned off debug in InsertablesPanel and PartItemType
- turned off live edit page parsing when selecting auto template because the page will be reloaded and parsed anyways
- added unMouseEnter and unMouseLeave to Element.ts
- did unregistering of children before parsing in PageView, RegionView and LayoutComponentView
- made sure super.remove() is called in ComponentView.remove
- made sure all listeners are unboud on remove in ItemView

XP-519 Live Edit - Reset button no longer working

---

modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TinyMCE.ts

[Fixed]  Removed 'title' attribute from editor area -> tooltip won't be shown

XP-588 TinyMCE - Remove big tooltip for help text etc

---

modules/portal-api/src/main/java/com/enonic/xp/portal/rendering/Renderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/postprocess/instruction/ComponentInstruction.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/DescriptorBasedComponentRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/ImageRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/PageRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/TextRenderer.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/render/ComponentControllerResource.java
modules/portal-impl/src/main/java/com/enonic/xp/portal/impl/resource/render/PageControllerResource.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/postprocess/instruction/ComponentInstructionTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/RendererFactoryImplTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/TextRendererTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/resource/render/ComponentResourceTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/resource/render/PageResourceTest.java

Refactor Renderer interface to remove PortalResponse parameter. All renderers should just new their own PortalResponse inside implementations.

XP-617 Remove PortalResponse parameter in Renderer interface

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveFormPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageControllerSelector.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageInspectionPanel.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageTemplateSelector.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/page/PageModel.ts

- [Fixed]. Added check that skips page reload for case when automatic template is switched to the default one upon page unlock
- Replaced hardcoded strings in a few places.

XP-671 Live Edit - Have to press "Customize" twice

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/ContextWindow.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/NamesAndIconView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/bar/AppBarTabMenuItem.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
modules/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardStep.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/InputLabel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/tiny/LinkModalDialog.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/panel/DockedPanel.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabItem.ts

Removed tooltips from the following places:
Content Grid:
Over displayname and path)
Content Wizard
-Tab (at top of view)
WizardStepPanels
Every "label" in the form
Live Edit
Context window tabs
All forms in "inspect" panel

XP-715 Tooltip - Remove unnessesary tooltips

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ResolvePublishDependenciesResultJsonFactory.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ResolvedContent.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResolvePublishDependenciesResultJson.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ResolvePublishDependenciesResultJsonFactoryTest.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/resolve_publish_dependencies.json
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishDialog.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ContentPublishRequestedItem.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/publish/ResolvedPublishContentViewer.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvePublishDependenciesResultJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvedPublishContentJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/ResolvedPublishRequestedContentJson.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/json/_module.ts
modules/admin-ui/src/main/resources/web/admin/common/styles/api/app/publish/publish-dialog.less

- Made dependencies list to be shown as one per line
- Show full content path instead of display name
- Sort alphabetically by full path
- No empty space between the "Show/hide dependents and child items" link and its contents
- Hide "Show/hide dependents and child items" if there are no dependencies
- Cursor must change to "hand" when hovered over "Show/hide dependents and child items" and "Include child items" so that it's obvious that they are clickable
- Rename "Show/hide dependents and child items" to "Show/hide dependencies and child items to be published"
- Move the main section inside scrollable area - when the list of dependencies is being scroller the main section should scroll as well

XP-801 Publishing Wizard - Misc fixes of the dependencies list

---

modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/RegionView.ts

- Fixed. Made Region view to remember its mousedown target and check if it belongs to one of the TextComponents elements on mouse up.

XP-837 Select text in Text component leaves focus onmouseup

---

modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts

- Actual problem seemed to occur only when inserting while all text in component was selected. In case of such insert - replaced text was removed, but its tags, such like "\<h2>" were not removed completely. Fixed via manual emptying of component onpaste event for such case.

XP-836 Bug: Copy Pasting text into Text component

---

modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts

* Deselect context item in LiveEdit whenever a new content is inserted
* Deselect all context items whenever a new one is selected

XP-826 Bug: Parts info/context menu never goes away

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/PublishContentResultJson.java
modules/admin-impl/src/test/resources/com/enonic/xp/admin/impl/rest/resource/content/publish_content_success.json
modules/admin-ui/src/main/resources/web/admin/common/js/content/PublishContentRequest.ts

- Adjusted resulting json to pass failed content's name instead of path
- For now deleted items are passed back as list of ids - hence adjusted feedback() method to not reference deleted items name
- Adjusted message for case when a few items were deleted

XP-961 Bad notification messages are shown upon publish

---

modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java

- Removed test, that might pass or fail on different machine due to unpredicted order of resulting items.

XP-964 Disable publish button when there is invalid content

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

-Updated restraimZommY() to let image pan up till lower border
-Fixed issue with drag handle  near lower border of crop area
-Updated crop reset (was resetting sometimes incorrectly)

XP-944 Image Cropping - Image hits the roof when panning up

---

modules/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/mask/Mask.ts

-Updated edit mode to zoom image only when inside cropped area
-Implemented fix for FF as scroll  in edit mode was not dispatching from Mask to masked element

XP-951 Image Cropping - Fix zoom behaviour

---

modules/core-api/src/main/java/com/enonic/xp/module/Module.java
modules/core-api/src/main/java/com/enonic/xp/module/ModuleService.java
modules/core-module/src/main/java/com/enonic/xp/core/impl/module/ModuleBuilder.java
modules/core-module/src/main/java/com/enonic/xp/core/impl/module/ModuleImpl.java
modules/core-module/src/main/java/com/enonic/xp/core/impl/module/ModuleServiceImpl.java
modules/core-module/src/test/java/com/enonic/xp/core/impl/module/ModuleBuilderTest.java
modules/portal-impl/src/test/java/com/enonic/xp/portal/impl/controller/AbstractControllerTest.java
modules/portal-script/src/main/java/com/enonic/xp/portal/impl/script/ScriptServiceImpl.java
modules/portal-script/src/test/java/com/enonic/xp/portal/impl/script/AbstractScriptTest.java
modules/testing/src/main/java/com/enonic/xp/testing/script/ScriptTestSupport.java
modules/upgrade/src/test/java/com/enonic/xp/upgrade/PathHelperTest.java

-Added a method "ClassLoader getClassLoader(Module)" on ModuleService. This will just create a new BundleClassLoader.
-Used ModuleService.getClassLoader(..) every place we use Module.getClassLoader
-Removed Module.getClassLoader and implementation.

XP-992 Remove use of Module.getClassLoader

---

modules/core-itest/src/test/java/com/enonic/wem/core/content/ContentServiceImplTest_update.java

- Ignored test removed, since the logic has been changed. There is no longer an automatic translation of properties in a tree based on the form.

XP-908 Fix @Ignore tests in itest

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/repo/SnapshotResource.java

- Fixed problem with saving snapshot files on Windows - generated date's format was not acceptable as a file name on windows, hence replaced some delimeters

XP-1038 Fix snapshot-command on windows

---

modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/application/ApplicationJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/page/DescriptorJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/page/PageDescriptorJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/FieldSetJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/FormItemJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/FormItemJsonFactory.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/FormItemSetJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/FormJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/InlineMixinJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/InputJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/LayoutJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/LayoutJsonFactory.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/form/OccurrencesJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/schema/content/ContentTypeJson.java
modules/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/schema/mixin/MixinJson.java
modules/admin-impl/src/test/java/com/enonic/xp/admin/impl/json/form/FormItemJsonTest.java

- Moved json classes to com.enonic.xp.admin.impl.json.form" in admin-impl module
- There were no tests to move
- Seems like all-input-types input type should be removed from features module

XP-1156 Move some form json classes to admin

---

modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsTreeGrid.ts
modules/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsView.ts
modules/admin-ui/src/main/resources/web/admin/common/js/content/MoveContentSummaryLoader.ts
modules/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGridBuilder.ts

The actual fix was the same, as in CMS-3733, which I've solved earlier. There was a conflict between the default slickgrid navigation and the KeyBinding. The new `PageComponentsTreeGrid` class is using the custom Options, so the `enableCellNavigation` was set to `true`, which is wrong. I've set it to `false` and added a comments about the conflict.

XP-1382 Component View - Fix keyboard navigation in the tree

---

modules/admin-ui/src/main/resources/web/admin/common/styles/api/ui/toolbar.less

Changed toolbar background from transparent to white.
Changed dropdown menu background from `#EEEEEE` to white.

XP-1537 Toolbar Overflow menu - Use white background color

---

modules/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Issue has already been fixed - I only adjusted the opacity a bit.

XP-1534 Detail Panel - Background color missing from mobile toolbar

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemVersionsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/Grid.ts

- Removed redundant spinner from ContentItemVersionsPanel as now spinner is handled directly in grid
- Updated grid to lazily create spinner on demand (when mask 'show' triggered)

XP-1721 Spinner overkill - Remove redundant instances, optimize usage

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts

- Fixed details panel is empty after publish
- Updated to view last selected item instead of the first one on events like publish
- Removed view item check when updating details panels to allow status update

XP-1833 Details Panel is empty, when content have been selected and published

---

modules/core/core-event/src/main/java/com/enonic/xp/core/impl/event/EventPublisherImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/NodeEvents.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/PushNodesCommand.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/NodeEventsTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/index/IndexServiceImplTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/CompareNodeCommandTest.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/FindNodesWithVersionDifferenceCommandTest.java

- Added appropriate method to NodeEvents
- Pushed nodes' ids and paths are stored in Event2 data as a String
- Added check for null event into EventPublisherImpl.publish(..) method

XP-1899 Fire pushed event from node layer

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageTemplateOption.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageTemplateOptionViewer.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/page/PageTemplateSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/page/PageMode.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts

* Show "Automatic" display name/icon in the root of page components tree when the page is in "forced controller" mode

XP-1958 Page Components View, display name of site not present

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/NonMobileDetailsPanelsManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/details/details.less

- Adjusted hiding of details panel
- Added min-height for properties widget view that assists in widget's height calculation as  properties widget view is rendered asynchronously after back-end request

XP-1946 Details panel has empty content on first open with selected item

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/NonMobileDetailsPanelsManager.ts

- Added additional check to non-mobile details panel manager, that checks if content browse panel is visible. If not true - there is no sense to do animations/calculations on non-mobile details panels

XP-1997 Detail panel unexpectedly goes to floating mode

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/AttachmentsWidgetItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/PropertiesWidgetItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/StatusWidgetItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/WidgetItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/WidgetView.ts

- Added wemQ chaining of layout calls for each WidgetItemView to allow WidgetView track ending of all its children' layout methods. WidgetItemView layout method might take a while due to need to make a back-end request.
- Added layoutCallbackFunction to WidgetView that will fire when all children Layout() methods will end up completely

XP-2000 Detail panel - Remove delay when switching between content items

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts

- Made tree grid to reload on new content event, if content's type is Site

XP-1948 ContentDeleteDialog - Wrong number of items to delete

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/detail/DetailsPanel.ts

- Made non-mobile details panel to recalculate widgets heights on shown event and mobile panel to  recalculate widgets heights each time item is about to be shown

XP-2035 Detail panel - Contents disappear after modifying an item

---

README.md

Took me 15 minutes to figure out how to start the application.
This patch adds a quick note about how to start Enonic locally after building it.

Add note about starting the application

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/live-edit.less

- CSS pointer-events is supposed to work in IE 11 http://caniuse.com/#feat=pointer-events but as always there are issues - Does not work on links in IE11 unless display is set to block or inline-block. So our pointer-events: none not working in IE because of display css. Implemented workaround that disables links in Live Edit for IE only and adjusted styling a bit. One small thing that will remain is link's color change on hover.

XP-2100 IE 11 - Links are clickable in Live Edit

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/BrowserHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/rest/JsonRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/system/StatusRequest.ts

- Added 'Cache-Control' and 'Pragma' headers with 'no-cache' value for IE requests to prevent caching http GET requests ( not cached by default  in FF and Chrome)
- Removed changes made in XP-2046 as no-cache headers will cover XP-2046 specific case
- Updated browser helper to store static boolean variable indicating if browser is IE or not to not evaluate each time

XP-2121 IE 11 - HTTP requests caching issues

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts

* Hide second split panel when item doesn't have renderable content

XP-2136 Hidden LE panel is masked upon saving of content

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/htmlarea/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-configurator.less

- Added additional check to Modal Dialog that checks if mce element was clicked while dialog is open
- Added counter for number of open dialogs so that we don't hide mask when any of the open dialogs closed
- Added remove() call to HtmlArea.ModalDialog in order to remove HtmlArea dialogs on close - it creates new dialog each time anyway, so we do not pollute dom tree with redundant dialog elements (other option would be to init and use single dialog once for each html area option that requires dialog - see openXxxDialog() methods in HtmlArea)
- Added border for dialog that appears next to site dialog

XP-2148 Cannot edit links or view source in HtmlAreas in site config.

---

modules/core/core-api/src/main/java/com/enonic/xp/xml/alias/ContentSelectorAliasConverter.java
modules/core/core-api/src/main/java/com/enonic/xp/xml/alias/XmlAliasConverter.java
modules/core/core-api/src/main/java/com/enonic/xp/xml/alias/XmlAliasConverters.java
modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/XmlFormMapper.java
modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/XmlInputTypeConfigMapper.java
modules/core/core-api/src/test/java/com/enonic/xp/xml/alias/XmlAliasConvertersTest.java
modules/core/core-api/src/test/java/com/enonic/xp/xml/parser/XmlContentTypeParserTest.java
modules/core/core-api/src/test/java/com/enonic/xp/xml/parser/XmlInputTypeConfigMapperTest.java
modules/core/core-api/src/test/resources/com/enonic/xp/xml/parser/XmlContentTypeParserTest.xml
modules/core/core-api/src/test/resources/com/enonic/xp/xml/parser/XmlInputTypeConfigMapperTest-aliased.xml

- For input types of type ContentSelector and ImageSelector made possible to use aliased names for some filter entries.
- Added XmlAliasConverters functionality for converting alias names into basic ones
- Created and adjusted tests

XP-2185 Handle relationship and allowType alliases

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/responsive/ResponsiveItem.ts

Optimized `ContentTreeGrid` update calls.
`ResponsiveItem.isRangeSizeChanged()` now actually works as it should.

XP-2109 ContentTreeGrid - Fix redundant re-rendering of grid columns

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less

Fixed the `names-view` styling in grid.

XP-2222 NamesView: character 'g' not fully displayed

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/ContentAppPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/DeleteContentAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentDeletedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts

- Adjusted ContentDeletedEvent to contain an array of ContentDeletedItems. ContentDeletedItem contains both id and path of deleted item to satisfy whoever handles this event.
- Made ContentWizardPanel to close itself on receiving ContentDeleteEvent after check for being equal or descendant of deleted item

XP-1428 Tab not closed, but content was deleted

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentSelectorQueryJsonToContentQueryConverter.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentSelectorQueryJsonToContentQueryConverterTest.java
modules/core/core-api/src/main/java/com/enonic/xp/content/ContentRelativePathResolver.java
modules/core/core-api/src/test/java/com/enonic/xp/content/ContentRelativePathResolverTest.java

- Adjusted ContentRelativePathResolver to expand ${site} wildcard if it present in the beginning - used getNearestSite() method
- Adjusted converter to manage cases with missing parent site - made converter to skip paths that can not resolve ${site} (must be quite rare case), but maybe it needs to throw an exception in that case

XP-2187 Handle complicated path expressions in allowPath entry

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/ServerEventAggregator.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/ServerEventsConnection.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentDeletedEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentServerChange.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentServerEvent.ts

- Optimized handling of server events on front-end
- Simplified parsing result of websocket event data - now it generates exactly one ContentServerChange per event
- Removed promises chaining in the ServerEventsHandler
- Added Move ContentServerChangeType and added appropriate handler

XP-2325 Simplify server events handling  code in ContentBrowsePanel

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/page/PageDescriptorDropdown.ts

-PageDescriptorDropdown is created on live edit page and binds some handlers (onApplicationAdded and onApplicationRemoved) on siteModel during construction. When we press 'save' on content -  live edit page is reloaded, PageDescriptorDropdown is recreated but siteModel is not, so sitemodel keeps some listeners that no longer relevant (created in other iframe). Usually it is not a problem for FF and Chrome to call such a listener that was released by window (but IE will complain and throw error) but not this time: from my observations there was error when creating XMLHttpRequest in JsonRequest in those 'window released' handlers. Small fix - remove those handlers when dropdown removed.

XP-2248 Need to click twice for selecting a application in a site-wizard

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/PageComponentsView.ts

-PageComponentsView has a 'flex' set as a display option, but when it is being shown jquery sets display option to 'block' so styling breaks (PCV was already scrollable)

XP-2364 Page Components view - Implement vertical scrolling

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentSelectorQueryJsonToContentQueryConverter.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ContentSelectorQueryJson.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentSelectorQueryJsonToContentQueryConverterTest.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/page/contextwindow/inspect/region/ImageInspectionPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSelectorQueryRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelectorLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/image/ImagePlaceholder.ts

- While implementing XP-2153, I did not take into account inputs that come from mixins and parts, whereas current implementation expects content selectors to be specified in content types only. Due to its not possible to precisely fetch part's and mixin's input configs just by content id and input name, I had to use exact data from rendered input.
- Removed setAllowedContentTypes() method of ContentCombobox builder to exclude ambiguities with setting content types that are actually required for loader
- Fixed problem with not setting Image content type into ContentSummaryLoader
- Added possibility to pass ContentTypes for ContentSelector query as a parameter - this allows to programmatically set allow types, not only by config
- Updated tests

XP-2403 LiveEdit - Image Selector is no longer filtered

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/view/ContentItemPreviewPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-manager/js/app/wizard/action/ContentWizardActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ImageErrorEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ImageUploader.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/ImgEl.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/uploader/Uploader.ts

- Fixed preview panel of content browser when image is broken
- Added image load error listening functionality
- Added removal of image editor upon failing to upload an image
- Added image error event that notifies editor to enable delete button only disable publish button
- Made uploader to check if it tries to re-create existing item - currently method setValue() of uploader is called a  few times with the same value - this helps to avoid loading same image several times

XP-2404 BUG? Broken images after upload crash admin

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts

- Added debounced click handler for ItemView which helps to avoid calling same handler during click event fall-through. Also, set debounce time to 300ms, as text component click handler is called after quite a while (at least on my machine)

XP-2590 Page editor - Wrong behaviour of context menu for text component

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/filter/TextSearchField.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/InputEl.ts

-Issue appeared due to changes in InputEl after adding onInput handler with refreshValueChanged() call (XP-2234 Add and verify that all descendants of FormInputEl correctly update dirty flag)
-Issue origin: in TextSearchField we  handle keyDown events with timeout to let user end his input into Search Field. After adding onInput handler into InputEl that is TextSearchField's parent , refreshValueChanged() started to trigger twice - in parent's onInput and in TextSearchField's onKeyDown, but handler in onKeyDown has timeout delay so it was called extra time with already invalid data after onInput called ages ago.
-Fix: added handleInput method in InputEl called  in onInput handler thus  handleInput can be overridden, what was done for TextSearchField

XP-2575 Grid is still filtered when search-text was cleared

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeNode.ts

Fixed the initial TreeGrid rendering issue, when the columns do not fit well.
Added duplicate handler in the TreeNode - no items with the same dataId can be added on the same level.

XP-2571 Duplicated content elements in ContentTreeGrid

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts

-Issue  origin: destroyEditor() method fails on content tab close. Appeared on latest FF versions, origin unknown but seems some resources cleanup fails on already disposed code
Tried replacing code 'editor.destroy(false)' with 'editor.remove()' and 'tinymce.EditorManager.execCommand('mceRemoveEditor',true/false, editor_id);' but didn't help.
Implementing workaround with try/catch as the only solution that helps

XP-2624 FF specific bug: impossible to close a wizard panel

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/support/BaseInputTypeManagingAdd.ts

- updated BaseInputTypeManagingAdd to ensure occurrence limits meaning that all descendant input types will inherit that
- trim is made on opening content wizard
- save is made on save

XP-2445 Bug: Problems getting ContentSelector to keep changes

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts

-Issue was in left padding 0->95px changing on step navigator after stretching; included left padding in width calculation

XP-2847 Wizard Step Navigator - Wrong width in docked mode

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/ElementHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/Highlighter.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts

-Issue: When the editor is in edit mode and another component is clicked/selected, its border will be displaced (shifted up by toolbar height).
-Explained: issue was in that empty text component takes different vertical space when in/out edit mode,  and after selecting other item it is getting highlighted, text edit mode gets switched off, empty text component takes more vertical space as when in text edit mode and moves html content except highlights that positioned absolutely.
-Solution: refresh highlights on switching text edit mode off

XP-2793 Page Editor - Text edit mode toolbar

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractCreatingOrUpdatingContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentTypeFromMimeTypeResolver.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateMediaCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateMediaCommand.java

- Added mime type resolver entries to determine executable files
- Also added special handling for executable files that uses file name and most expected mime type to determine if file is executable

XP-2899 Executable files are created as media:unknown

---

modules/tools/toolbox/src/main/java/com/enonic/xp/toolbox/app/InitAppCommand.java

This commit includes `.gitignore` and `.gitkeep` when downloading a
starter kit. Because it makes sense. 🙄
Fixes #2939

Include .gitignore in init-project clones

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts

tinymce editor in inline mode after move losses its root element of the editable area - made editor to re-init on move

XP-2988 HTML editor - Buggy behaviour after dragging a text component

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/ComponentView.ts

- As during move components are unsubscribed from events, made them to be subscribed again

XP-3006 ComponentViews are broken after move and reset in LiveEdit

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetView.ts

In order to enable dynamic height and keep widget view "transitionable":
- Made max-height property to be set to "none" on slide-in after animation ends
- Made max-height property to be equal to view's height before slide-out

XP-3049 Version Panel not scrolled, when history item was extended

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/DeleteContentAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialogAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/KeyHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ConfirmationDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/AnchorModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/LinkModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less

Fixed the ContentPublishDialog lose focus from the start, when default button is disabled.
Replaced `ModalDialog` import as `BaseDialog` with default usage.
Removed "Enter" key binding from the modal dialogs.
Removed the unnecessary key bindings from the htmlArea modal dialog.
Added modal window focus lock.
Added support for the arrows to change the focus on some elements in modal window.

XP-3032 Modal (confirmation) dialog: "Enter" key is bound on confirmation, regardless of focus; automatic focus on some dialogs is missing.

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/AppHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/html-editor.css
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/html-editor.less
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/text-view.less

Added `focusin` and `focusout` event firing in focus/blur handlers of the `HtmlArea`, since it doesn't have any real focusable elements.

XP-3085 SiteConfigurator dialog:  toolbar not appears in the htmlarea

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/Highlighter.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts

- Problem was common for LiveEditComponents - getDimensionsTopRelativeToParent() returned incorrect top offset which did not allow to correctly position highlighter box
- Adjusted highlight dimensions calculation to use getOffset() method instead of getOffsetToParent() and added correction on an top offset value of the text editor toolbar

XP-3192 PageEditor selection boxes are badly positioned in xeon app

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/html-editor.less

- Made toolbar buttons to be left aligned in non-live edit html areas
- Fixed problem with active toolbar width on resize - removed calls to updateEditorToolbarWidth(), which seems useless to me

XP-3206 HTML Area - Toolbar buttons are incorrectly positioned

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/DetailsPanel.ts

- Added mobile details panel that will check for IOS in order to use innerHeight property instead of outerHeight in slide up/bottom functions as IOS treats outerHeight differently than other platforms

XP-3198 Mobile preview - Incorrect behaviour of the detail panel icon

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/part/PartComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/part-view.less

- For parts that start with link: enabled pointer-events; set display property to 'block' value in order to enable correct selection and behavior
- In PartComponentView constructor I replaced href attribute value in order to disable navigation Otherwise, parts with links in the root just don't behave correctly

XP-3217 Page Editor - Disable anchor links in the root of a part

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/SelectorOnBlurEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/dropdown/Dropdown.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DatePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DatePickerPopup.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/DateTimePickerPopup.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePicker.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/time/TimePickerPopup.ts

Fixed the selector blur event issue, which was caused by the propagation stop on click.
Added `onfocus` handler.
Update `ComboBox` and `Dropdown` focus handling.
Fixed `TimePicker`, `DatePicker` and `DateTimePicker` popups closing.
Fix the calendar icon.

XP-3124 Open ContentSelector doesn't close when another ContentSelector is opened

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/NewContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/list/ListBox.ts

-listItems keeps original list of entries in new content dialog, it is being used to filter entries and show original list when no filtering applied. After listbox refactoring it happens that when items in contentList are being set it cleans old array of items so original list in listItems get erased.
Fixed by using copy of original array.

XP-3384 NewContent dialog: filtering does not work

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/action/UnpublishContentAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentUnpublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardToolbarPublishControls.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/action/ContentWizardActions.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/action/PublishAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/action/PublishTreeAction.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/action/UnpublishAction.ts

Removed the Unpublish button from the content wizard.
Replaced publish button with `MenuButton` in `ContentWizardPanel` and other places.

XP-3376 Replace Publish action button with the new menu button in ContentWizard toolbar

---

modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/common.less

Added dropdown-handle styles to the common css links of the live edit.

XP-3426 Dropdown handle button is not visible in Page Editor

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/dialog/DependantItemsDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentUnpublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/publish/content-publish-dialog.less

- Moved mask code to a common parent of delete and publish dialogs - DependantItemsDialog
- Simplified a little of code in DeletedDialog
- Added 100ms timeout in publish dialog before stash' items are displayed to give mask enough time to render - seems like element.show() method does it in asynchronous??? way
- Moved include checkbox in publish dialog to button row so that it does not cause autoscroll on click when there are many dependant items. Fixed display of checkbox in small resolutions.

XP-3478 Delete dialog - Show spinner while fetching child items

---

modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/resolver/ClassLoaderApplicationUrlResolver.java

- moved classpath creation to ClassLoaderApplicationUrlResolver constructor instead of doing it on every request
- also cached found files

XP-2923 Launcher is slow when XP is started in dev mode

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/NamePrettyfier.ts

… for edit (but also for preview and not always)
-String.prototype.normalize is not supported on Windows 8.1, thus no sense calling transcribe (error will be thrown)

XP-3557 IE: Contens open with errors in console under Win 8.1

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/ContentItemPreviewPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ClassHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/rest/JsonRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/rest/ResourceRequest.ts

-(Syntax Error) Issue was that IE can't accept timeout value '-1' in XMLHttpRequest, need to set zero if you don't want timeout to expire
-IE does not support yet function.name property, added name extractor for IE (in ClaassHelper.ts)
-In IE window.location.pathname for blank page is '/blank', we checked only 'blank' before (ContentItemPreviewPanel.ts)

XP-3501 IE11 users cannot edit any content

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialog.ts

-Issue occured because confirm dialog was opened before delete dialog is closed

 XP-3638 Confirm Delete Dialog - Close on pressing Escape

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/MoveContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ConfirmContentDeleteDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentMoveComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/MoveContentSummaryLoader.ts

-Issue occurs due to mousetrap skips event triggered by our shortcut if it's source is in input element. Same for input in delete confirmation dialog
-small refactoring on move dialog
-Fixed one more issue that was found during original task investigation: in move dialog request that being sent when opening destination dropdown is not properly cleared when reopening dialog; if you've entered some values and then reopened dialog and tried to open input dropdown - your request (in spite of fact  that input is empty after reopen) will send request with search string set with previously entered values.

XP-3639 Move Content Dialog - Close on pressing Escape

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialog.ts

-Issue occured because confirm dialog was opened before delete dialog is closed

XP-3638 Confirm Delete Dialog - Close on pressing Escape

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/filter/ContentBrowseFilterPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/query/ContentQuery.ts

- Made contentQuery equitable so that getAggregations() may compare query that already made with a new one and use existing results if equal

XP-3583 Avoid redundant back-end call in ContentBrowseFilterPanel

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/ContentsExistJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ContentIdsJson.java
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentsExistRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentsExistResult.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/contentselector/ContentSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageContentComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelector.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelectorDisplayValue.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/ImageSelectorSelectedOptionsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/form/inputtype/image/SelectionToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/ContentsExistJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/BaseSelectedOptionsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/RichComboBox.ts

- Added displayMissingSelectedOptions and removeMissingSelectedOptions to comboBox in order to enable handling of missing contents
- Made Content and Image selectors to remove missing properties on appropriate event
- Added service to ContentResource with appropriate front-end classes that check existence of passed content ids. Service is used by ComboBox.
- Made comboBox to generate event for removal of non-existing content references and render placeholder if content is not available (due to permissions. for example)
- Adjusted xXxSelectedOptionsView classes to generate empty view for missing content's placeholder
- Adjusted image selector toolbar to handle such placeholders

XP-3230 contentSelector / imageSelector - Bad handling of deleted items

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts

Replaced native focusin/focusout events with jQuery events.

XP-3627 [Firefox] Clicking outside expanded dropdown will not close it

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/form-item-set-occurrence-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/input/input-occurrence-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/button/dropdown-handle.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/security/acl/access-control-entry.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/security/acl/userstore-access-control-entry.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/security/principal-selected-option-view.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/combobox/selected-options.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/variables/mixins.less

Added `.focusable` mixin.
Added focusable styles to several buttons and icons.
Moved `.icon-close` button styles to mixin.

XP-3629 Selector inputs - Highlight focused icons in SelectedOptionsView

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetsSelectionRow.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/dropdown/Dropdown.ts

Fixed the `Dropdown.giveFocus()` event, when the input inside it is hidden.
Added `FocusInOut` handler into the `WidgetSelectorDropdown`.

XP-3617 Simplify collapse of the widget selector dropdown

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/error-highlight.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/input-common.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/modal-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/common.less

- Made controls inside invalid form item  use the same pink background as the parent div
- Animated appearance/disappearance of the pink background around invalid field
- Used font-size 14px for error message
- Moved common error input styling into separate less file
- Changed padding of input views that may display validation errors so that both valid and invalid inputs appear with same indent and so that validity change does not make input jump
- Added "expanded" class toggling for combobox so that its children aware of its state

XP-3696 Error handling - Highlighting of invalid fields

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/page/contextwindow/insert/InsertablesPanel.ts

- initializeDraggables() handler was called upon rendering InsertablesPanel. It resulted in trying to make children of insertables panel draggable, when they were not rendered yet, hence, set initializeDraggables() to be triggered on insertablesGrid render.

XP-3763 ContextWindow, Insertables panel, impossible drag and drop items

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/PrincipalWizardPanel.ts

- Delete handler function was passed to event .on() and .un() methods with 'bind(this)' call. 'bind(this)' returns a new function which results in two 'unequal' functions passed to event. hence it is  impossible to unbind such function
- Added check for existence of this.getPersistedItem() as in a wizard of new item it returns undefined

XP-3774 Exception appears during deleting of Roles or Group

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts

- onValidityChanged handler used to set 'isContentFormValid' field based on the Validity Event's field, whereas it usually reflects validity change only of a single wizard block (such like wizard step or header). Hence, whole wizard should be checked when setting this property.

XP-3771 Publish button enabled, when required field is empty

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardDataLoader.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/page/LiveFormPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/Element.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/mask/Mask.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/panel/SplitPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/responsive/ResponsiveManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- updated content wizard to fire 'rendered' event after live edit is fully rendered
- tuned ContentWizardDataLoader to do more parallel requests to boost loading time
- updated 'added' event firing in Element, so that it is fired only if (after) parent is added to DOM
- updated Mask to resize on masked element resize
- used styles to mask elements during loading
- addressed issue with multiple wizards opening at the same time by rendering them on show
- fired 'shown' event after element is added to dom and is visisble (instead of after rendered completes)
- returned false from hasUnsavedChanges prematurely if wizard is not rendered

XP-3861 Content Wizard - Masking of panels

---

modules/admin/admin-ui/src/main/resources/assets/js/home/launcher.js

-IOS only, android devices were ok. Issue occured because of using 'let' variable declaration

XP-3908 Dashboard icons - Tour and About do not work under mobile

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/PrincipalWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserItemWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/user-manager/js/app/wizard/UserStoreWizardPanel.ts

-Issue origin: Wizard panel's doRenderOnDataLoaded() method is called after wizard's show event have already triggered, thus when this method was called in PrincipalWizardPanel deleteHandler was not bind as it was assigned in onShown handler
-Optimizing common things in doRenderOnDataLoaded for user items

XP-3934 Impossible to close wizard for User, Role and Group

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetItemView.ts

- Adjusted link import handler to use body of imported html instead of div[0] which is error prone
- Added stripping of script and link tags off the imported html in order to avoid second evaluation of imported assets

XP-3928 Make external widgets to load assets only once

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetItemView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/BrowserHelper.ts

- Added check for FF and Safari so that imported stylesheets are nit stripped off as FF and Safari do not process css files from html import
- Added is Safari() test for BrowserHelper

XP-3985 Fix resource loading issue in FF

---

modules/admin/admin-ui/src/main/resources/assets/js/home/xptour.js
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/home/home.less

-If there's at least one uninstalled or out-of-date demo app, replacing Finish button with "Install Demo Apps" (green background color and the same height as "Previous"). It is disabled while apps and their statuses/versions are being fetched
-Once clicked, the button  becomes disabled and its caption  changes to "Installing..."
-After apps have been installed/updated, the button is replaced with "Finish"
-If all of the demo apps are already installed and up-to-date when the last step of the Welcome tour opens, the button "Finish" is displayed
-Last step updated to have the same height as previous steps.

XP-3961 Welcome Tour - Replace "Finish" button with "Install Demo Apps"

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/editor/HTMLAreaHelper.ts

Fixed the originalValue set in `HtmlArea`'s `TextArea` input, so that the check for isDirty will be valid for non-modified empty input.
Previously, the base value of originalValue was `null`, not the empty string.

XP-4023 HtmlArea not updated when saved in other browser window

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/ContentItemPreviewPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/NamePrettyfier.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/view/ItemPreviewPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Adjusted handling of grid events so that mobile panel does not get triggered too often. Also, adjusted content item preview panel to not trigger ContentPreviewPathChangedEvent too often.
- Removed normalize call for cases when its not supported in NamePrettyfier - Safari and IE do not support it
- Changed orientation of mobile statistics panel arrow

XP-4031 Don't open the Details panel after closing the wizard on mobile

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/DetailsPanel.ts

- Docked details panel is a child of split panel that does not use slideIn/slideOut methods so in order to detect that panel is displayed we need take in account that there maybe an animation delay in split panel, hence increased timeout time a bit so docked panel width detection may work
- Added check to figure which details panel we work with

XP-4065 Details Panel is empty, when XP opened with FF

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowseToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/browse/BrowsePanel.ts

Resolved the rendering problem with a timeout hack, since the errors occurs only in times, when program was trying to get the height of the toolbar, that was not yet visible.
Made sure, that append calls will be placed farther in the call stack.

XP-4041 Toolbar is not always visible on the BrowsePanel

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/MobileContentItemStatisticsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/ActiveDetailsPanelManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/DetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/DetailsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/DockedDetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/FloatingDetailsPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/MobileDetailsSlidablePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/NonMobileDetailsPanelsManager.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/SlidablePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetView.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/WidgetsSelectionRow.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/button/InfoWidgetToggleButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/button/MobileDetailsPanelToggleButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/detail/details-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Separated slidable panels implementation from details view that contains widget
- Refactored details panel to separate sliding panels functionality from widgets view functionality
- Renamed DetailsPanel into DetailsView- now details view is responsible only for rendering widgets, not hiding/showing itself

XP-3998 Replace three details panels with one

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/InstallAppDialog.ts

-Close() on InstallAppDialog was triggered twice when closing dialog before app upload finished, this extra close action breaks further close behaviour

XP-4241 Shadow mask does not disappear, when application was uninstalled

---

modules/admin/admin-ui/src/main/resources/assets/js/home/sessionExpiredDetector.js
modules/admin/admin-ui/src/main/resources/web/admin/common/js/main.ts

see https://discuss.enonic.com/t/internet-explorer-support-in-admin/693
-fixed error occuring in sessionExpiredDetector, setting XMLHttpRequest.timeout should be done after open() is called on it
-performance issue in IE occured due to q promises' stacktrace handling; when option Q.longStackSupport is true then stack property of Error rejection reasons is rewritten to be traced along asynchronous jumps instead of stopping at the most recent one. This is useful for debugging but lead to somewhat-serious performance and memory overhead. OK in other browsers

XP-4254 Content Studio - Slow rendering under Internet Explorer 11

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/NewContentDialog.ts

…any content type for opening a wizard page
-oninput event is triggered unexpectedly in IE on focus and blur; Replaced oninput event with onValueChanged

XP-4312 New Content Dialog - have to click content type twice to open the Wizard (only in IE)

---

modules/core/core-schema/src/main/java/com/enonic/xp/core/impl/schema/content/ContentTypeRegistry.java

- Added catch for get ContentTypeLoader.get() call that catches XMLException that is thrown when there is a content type in schema that is not described in schema.xsd

XP-4253 More robust handling of unknown item types

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/dom/ElementHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/LinkModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-configurator.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/modal-dialog.less

-Updated and refactored Combobox to correctly find first scrollable parent
-Updated ElementHelper.isScrollable() to check computedProperty rather than inline style
-Update LinkModalDialog and SiteConfiguratorDialog to not use redundant logic that was positioning dropdown as fixed and calculating it's position; Instead rely on Combobox to position dropdown below or above depending if it fits area

XP-4350 Dropdowns are misplaced in some of the modal dialogs

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/page/LiveEditPageProxy.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/page/LiveFormPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/FragmentComponentReloadRequiredEvent.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/fragment/FragmentComponentView.ts

- Added propagation of content update event to live edit.
- Added FragmentComponentReloadRequiredEvent that liveFormPanel subscribes on in order to reload fragment upon request
- Made fragment to fire FragmentComponentReloadRequiredEvent on appropriate content update request

XP-4359 Content Wizard - Status of published fragment won't change to modified after save

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorSelectedOptionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/ValidationRecordingViewer.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/support/BaseInputTypeNotManagingAdd.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/TextLine.ts
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ValidateContentDataCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/validate/InputValidator.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/validate/SiteConfigValidationError.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/ValidateContentDataCommandTest.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/validate/InputValidatorTest.java

- Made site form to display validation errors on show
- Adjusted validateOccurrences() of BaseInputTypeNotManagingAdd to check for input validity before incrementing valid inputs count
- Adjusted TextInput to notify about its change not only when input is valid - the same way other inputs do
- Fixed problem with uninitialized errors container of ValidationRecordingViewer
- Adjusted InputValidatorBuilder to accept Form instead of ContentType, so that SiteConfig and other forms may be passed for validation directly
- Added site form inputs validation in ValidateContentDataCommand
- Added test for broken input in SiteConfig

XP-4413 Site Config - Validation crashes on invalid value with regexp

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts

Fixed the order of calculations
Combobox should fist adjust dropdown grid height and then position the dropdown.

XP-4418 Dropdown is misplaced in site configurator- modal dialogs

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/WizardStepNavigatorAndToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-step-navigator-and-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/wizard-step-navigator.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

Fixed the help text button alignment.
Updated the `.minimize-edit` button to use classes for show / hide.
Added smooth slide effect for help button, when wizard-minimize button starts to overlap it.
Fixed the `WizardStepNavigatorAndToolbar` dropdown styles.
Fixed navigator steps check for `minimize` status.

XP-4482 Content Wizard toolbar - Fix menu overflow and alignment of the help-text icon

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentTreeGrid.ts

- Adjusted appendContentNodes() method of ContentTreeGrid so that it returns all appended nodes upon resolving parallel promises
- Refactored processContentCreated() method  - removed redundant checks and variables, added call to placeContentNodes so that  created or moved contents are inserted into right place in a grid

XP-4447 Manually uploaded content isn't sorted correctly

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/wizard/SaveBeforeCloseDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts

- also returned No button to SaveBeforeCloseDialog, that was replaced with Cancel for wizard in separate tab, but was not used

XP-4503 Image Editor - Add tooltips to the icons

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/dialog/DependantItemsDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/dialog/ProgressBarDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentUnpublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ContentDeleteDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/dialog/dependant-items-dialog.less

Fixed endless loading spinner in Delete button bug.
Fixed the instant delete behavior, when published content was not deleted, though it was marked.
Fixed the action button behavior, when it was not disabled when the content was processing.
Fixed styles, when the status of the item in the dependent items list overflows the container.
Disabled the dependent items fetching: items were fetching after there were set manually.
Renamed the show/hide Spinner to more relevant name.
Replaced action button manual enable/disable with more flexible lock/unlock methods.

XP-4535 Delete Content dialog - 'Instantly delete published items' is blinking for published content

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/view/mobile-content-item-statistics-panel.less

- Fixed right value. Replaced .split-panel class selector with .split-panel-with-details - so that it affects only single split panel instead of all the split-panels

XP-4524 Fix sliding effect when opening the preview panel on mobile

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/CompareContentResultJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/CompareContentResultsJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetPublishStatusResultJson.java
modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentRowFormatter.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardToolbarPublishControls.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/ContentSummaryAndCompareStatus.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/PublishStatus.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/GetPublishStatusResultJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/GetPublishStatusesResultJson.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/json/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/ContentSummaryAndCompareStatusFetcher.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/GetPublishStatusesRequest.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/result/CompareContentResult.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/result/GetPublishStatusResult.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/result/GetPublishStatusesResult.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/resource/result/_module.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-tree-grid.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less

- Adjusted ContentResource.compare method to return publish status as well - as this method is used by treegrid so that we don't need to do subsequent call to getPublishStatuses. Changed appropriate json classes on back-end and front-end
- Adjusted ContentSummaryAndCompareStatus.ts to store publishResult field
- Adjusted statusFormatter of ContentRowFormatter so that it displays 'pending' and 'expired' publish statuses along with compare status in TreeGird
- Adjusted ContentWizardToolbarPublishControls to manage publishStatus along with compareStatus. Adjusted WizardPanel to set publish status into it.
- Added GetPublishStatusesRequest.ts and appropriate json and wrapper classes
- Adjusted styles

XP-4571 Time-based publishing - Content Studio - Publish status

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/ContentItemPreviewPanel.ts

- Replaced ajax.get() with ajax.head request so that we know if content will render without rendering the page and passing back heavy content body

XP-4653 In Content Studio, Browse view triggers parts twice

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/page/LiveFormPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/SiteModel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfigurator.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorSelectedOptionView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorSelectedOptionsView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-configurator.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/form/live-form-panel.less

- Added 'no preview' message for non renderable content in live edit
- Adjusted siteconfigurator to manage app views that get stopped, started and uninstalled
- Adjusted ContentWizardPanel to not reject rendering promise for uninstalled or stopped app

XP-4660 Make not renderable content editable

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/SortContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/SortContentTabMenu.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/KeyHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabItem.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/tab/TabMenu.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/AppHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/sort-content-dialog.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/tab/tab-item.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/styles.less

Added basic support for keys in `SortContentTabMenu`
Moved onShown focus from Apply button to `SortContentTabMenu` dropdown.
Fixed focus change after sort order was selected.
Replaced old outer click with the new focusInOut event.
Fixed the dialog position after the grid is loaded.

XP-4501 Sort dialog - Fix focusing and keyboard navigation

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/publish/ContentPublishDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/dialog/dependant-items-dialog.less

Fixed the stash lock/unlock update.
Added `.no-publish` class to hide spinner, when dialog locked and publish is disabled.

XP-4740 Publish dialog - Endless spinner on the "Publish" button

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CheckContentsValidCommand.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/CheckContentValidCommandTest.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ContentServiceImplTest_isValidContent.java

- Adjusted CheckContentsValidCommand to return true right away for empty contentIds
- Added test for case above
- Removed redundant CheckContentValidCommandTest test file

XP-4766 Incorrect validation of content in the Publish Dialog

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/DisplayNameScriptExecutor.ts

- It seems that recent lint changes enforced strict mode that treats 'eval' as a keyword, does not allow assigning it to other variables and makes code evaluated via 'eval' to be always created in a new scope - hiding 'eval' is not needed anymore. Let's just ensure that we are in strict mode.

XP-4801 Content type's "Display name scripts" stopped working in 6.9 B3

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/LinkModalDialog.ts

Added `setFirstFocusField` call to the `LinkModal` dialog.

XP-4796 Insert Link Dialog: doesn't get focus when opened in 6.9 B3

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDependenciesResolver.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetPublishInfoCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/branch/storage/BranchServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/elasticsearch/query/translator/builder/FilterBuilderFactory.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/elasticsearch/storage/StorageDaoImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/FindNodeBranchEntriesByIdCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodesHasPermissionResolver.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/PushNodesCommandTest.java

The id filter usage is a bit scary, this should be fixed later, but for now just make sure that we wont end up getting all results instead of nothing when there is no id's to filter on.

XP-4885 Empty ids in copy executor copies everything

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/applications/js/app/installation/InstallAppDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/MoveContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/create/NewContentDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/remove/ConfirmContentDeleteDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/combobox/ComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ImageModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/LinkModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/MacroModalDialog.ts

-Making all modal dialogs behave same when 'Esc' was presses on keyboard - closing the dialog immediately; the only exception is combobox that has dropdown shown - it must just hide dropdown after first time 'Esc' pressed, and close dialog after the second time 'Esc' pressed.

XP-4949 HTML Area - Modal dialogs must handle close on Esc

---

modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/image-dialog.less

-FF issue with fieldset width that (minimum width of a fieldset is never less than the intrinsic width of its content. WebKit gives you a way to override this behaviour by specifying it in the default stylesheet, but Gecko goes a step further and enforces it in the rendering engine)

XP-4975 HTML Area/Insert Link dialog - Add ellipsis overflow for long paths

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentCommand.java

- Added site and mixin services to rename command as they are required for validation command when content is site or has mixins

Content Wizard - NullPointer exception when saving unnamed content

---

modules/admin/admin-ui/src/main/resources/assets/js/home/launcher.js
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentBrowsePanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/view/detail/button/NonMobileDetailsPanelToggleButton.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardToolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/app/bar/AppBar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/toolbar/Toolbar.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/appbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/app/wizard/content-wizard-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-browse-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-publish-menu-button.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/launcher/launcher.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/reset.less

Disabled HomeButton for all apps, except User Manager.
Added autofocus to launcher button on app rendered.
Updated launcher button padding.
Updated outline on focused elements if Firefox to look it same, as in Chrome.
Updated `NonMobileDetailsPanelToggleButton` to inherit from `button``, instead of `div`.
Updated `ContentBrowseToolbar` to use flexbox, instead of float to fix the focus order for `ContentPublishMenuButton`.
Updated `ContentWizardToolbar` to use flexbox, instead of float to fix the focus order.

Fix outline and tab order of items in the toolbar #4492

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentMoveComboBox.ts
modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/browse/ContentSummaryOptionDataHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/DropdownGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/DropdownTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/OptionDataHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/selector/OptionsTreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/selector/dropdown/dropdown.less

- Added dataToExpandOnReload field to OptionsTreeGrid which will be used as target when searching for node within grid
- Added method to OptionsTreeGrid that expands node till dataToExpandOnReload node
- Updated combobox classes to use new method that sets dataToExpandOnReload

Auto-expand move dialog's treegrid dropdown down to selected item

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/notify/MessageBus.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/notify/NotificationMessage.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/notify/NotifyManager.ts

* Added the notification limit to prevent from display too many of them at once.
* Removed return value (id) from notification functions (refactored).
Notifications will be shown until the limit is reached. Each next notification will be placed into the queue. After the notification active is removed, new notification from the queue will be rendered.

Adjust notifications bar to not span too high on many notifications (#4472)

---

modules/core/core-export/build.gradle
modules/core/core-export/src/main/java/com/enonic/xp/core/impl/export/NodeImporter.java
modules/core/core-export/src/test/java/com/enonic/xp/core/impl/export/NodeImporterTest.java
modules/core/core-export/src/test/resources/com/enonic/xp/core/impl/export/node_manual_ordered.xml
modules/core/core-export/src/test/resources/com/enonic/xp/core/impl/export/node_timestamp.xml
modules/core/core-export/src/test/resources/com/enonic/xp/core/impl/export/node_unordered.xml
modules/core/core-export/src/test/resources/com/enonic/xp/core/impl/export/node_with_appref.xml
modules/core/core-export/src/test/resources/com/enonic/xp/core/impl/export/node_with_binary.xml
modules/core/core-export/src/test/resources/com/enonic/xp/core/impl/export/node_with_id_1234.xml
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/ResolveInsertOrderValueCommand.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/node/AbstractNodeTest.java

Checking if initial folder contains a node definition or not, acts accordingly.
Refactored tests to integration tests since its so hard testing this properly without a real backend.
Fixed issue with NPE on insert in manual ordered parent.

NPE on import targeting a manually sorted node #4636

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/query/PathMatchExpression.ts

Fixed search expression so you dont get double // in beginning if starting search expression with /

Path-search in selectors doesnt work (4786)

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/security-wizard-step-form.less

Made SecurityWizardStepForm visible for users without write permissions.
Hide Edit button in SecurityWizardStepForm for users without write permissions.
Removed obsolete code.

Content Wizard - 'Security Step' is not shown for users with read-only permissions (#4755)

---

modules/admin/admin-ui/src/main/resources/web/admin/apps/content-studio/js/app/wizard/ContentWizardPanel.ts

Fixed the content id of the updated content.

Fragment Wizard - Wizard is not updated when related image was updated or changed (#4765)

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/application/inputtype/siteconfigurator/site-configurator.less

Fixed problem with `overflow: auto`, when it prevented dropdown to be rendered outside the parent element in small dialogs without scrolls.

Site.xml with only one input type with foldout doesn't show properly #4914

---

gradle/java.gradle
modules/core/core-api/build.gradle
modules/distro/src/home/config/logback.xml
modules/launcher/launcher-impl/build.gradle
modules/launcher/launcher-impl/src/main/resources/META-INF/config/system.properties
modules/launcher/launcher-impl/src/test/java/com/enonic/xp/launcher/impl/util/OsgiExportsBuilderTest.java
modules/tools/testing/build.gradle
modules/tools/toolbox/build.gradle

Hi Stenl
Just a proposition for Enonic XP 6.11. So that we can use rolling of log file by time and size.
But there may be an impact I do not think about

Logback - Size and time based (#4940)

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ValidateContentDataCommand.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/AbstractContentServiceTest.java

-Updated validation command to fetch form items for inline mixins so they could be validated, otherwise ContentType's form contains form item of type InlineMixin that can't be validated

Incorrect validation of OptionSet-content in the grid #4830

---

modules/app/app-contentstudio/src/main/js/app/dialog/StatusSelectionItem.ts
modules/app/app-contentstudio/src/main/js/app/publish/PublishDialogDependantList.ts

-Added tooltip for remove button
-Stopped propagating move event from remove button to it's parents, otherwise parents' tooltip is shown

Publish Wizard - incorrect tooltip for the Remove -button #4945

---

modules/app/app-contentstudio/src/main/js/app/wizard/ContentWizardToolbarPublishControls.ts
modules/app/app-users/src/main/resources/admin/i18n/phrases.properties
modules/app/app-users/src/main/resources/admin/i18n/phrases_no.properties

Update localized notifications for User Store and Principals.
Restored line, mistakenly removed in #5151

Fix messages in notifications about User Store actions #5170

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/FormView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/AppHelper.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/dialog/modal-dialog.less
modules/app/app-contentstudio/src/main/js/app/wizard/EditPermissionsDialog.ts

Added confirmation dialog to the `EditPermissionsDialog`.
Moved `isDirty` function to `AppHelper`.
Fixed focus blinking in dialogs with a confirmation dialog, when it was shown.

Don't close 'Edit Permissions' dialog without warning, if something is not saved #5120

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/remove/content-delete-dialog.less

* Made overflowed checkbox label crop and use the ellipsis. Take a note, that it only crop the text, instead of switching between _full_ and _short_ version, because in that case we would need to manage it with JS, wich would be a not a very good idea, in my opinion.
* Fixed the position of the checkbox in mobile mode.

Mobile resolution - "Instantly delete..." checkbox is too wide #5022

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/content/image/ImageUploaderEl.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/image/ImageEditor.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/image/image-editor.less

Fixed the width of the image editor, since it overflows the screen in mobile mode.
Fixed the resize of the image editor in edit mode.

Mobile resolution - ImageEditor dialog doesn't fit the viewport #5023

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/branch/storage/BranchServiceImpl.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImpl.java
modules/core/core-repo/src/test/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImplTest.java

Added invalidation of path-cache for repo-branches when deleting. Adding test, also added exception when path in cache but not in storage to avoid further issues with path-cache consistency.

Path-cache not invalidated when deleting repository (#5254)

---

modules/distro/src/home/config/logback.xml

Setting ISO date as STDOUT format

Use ISO datetime as standard logback config #5263

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/grid/GridColumn.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGridBuilder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid-toolbar.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/ui/treegrid/tree-grid.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/browse/content-tree-grid.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/module/browse/application-tree-grid.less
modules/app/app-applications/src/main/js/app/browse/ApplicationTreeGrid.ts
modules/app/app-contentstudio/src/main/js/app/browse/ContentTreeGrid.ts
modules/app/app-users/src/main/js/app/browse/UserItemsTreeGrid.ts

* Moved the checkbox in Users and Applications to the right on small resolutions.
__Refactored:__
* Fixed the columns width on different resolutions in `ApplicationTreeGrid`.
* Removed the hidden date column in `UserItemsTreeGrid`.
* Moved common handlers to TreeGrid from its children.

Mobile resolution - Checkboxes are not right-aligned in the Application app's grid #5235

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueMailMessageGenerator.java
modules/admin/admin-impl/src/main/resources/com/enonic/xp/admin/impl/rest/resource/issue/item.html

-When svg icon contains width and height attributes it overrides all container width and height values and takes space according to svg width and height; CSS can't help, thus replacing svg's attributes with required values that will restrict icon size to container's size

Problem with size of app icon in issue email #5293

---

modules/admin/admin-ui/package-lock.json
modules/admin/admin-ui/package.json
modules/app/app-applications/package-lock.json
modules/app/app-contentstudio/package-lock.json
modules/app/app-users/package-lock.json
package-lock.json

Upgrade d`require-dir` dependency to prevent errors, when using it on Node >= 8.
Generated npm lock files as part of the npm 5 new [functionality](https://docs.npmjs.com/files/package-locks).

Upgrade Node.js to v8.x.x

---

modules/distro/build.gradle

In the libs where it will be used we need to exclude the bountycastle artifact.
build.gradle
```
dependencies {
compile "org.bouncycastle:bcprov-jdk15on:1.54"
include( "nl.martijndwars:web-push:3.0.0" ) {
exclude group: 'com.google.guava', module: 'guava'
exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
}
}
```
In Java class where is used:
```
import java.security.Security;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
static
{
if ( Security.getProvider( BouncyCastleProvider.PROVIDER_NAME ) != null )
{
Security.removeProvider( BouncyCastleProvider.PROVIDER_NAME );
}
Security.addProvider( new BouncyCastleProvider() );
}
```

Implement the possibility to use bountycastle security #5072

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ImageModalDialog.ts

-Adjusted max height of image container with respect to recently added close button that located now outside of dialog

Limit height of the HTML Area's Image dialog #5498

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/form/inputtype/text/HtmlArea.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/PageView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/liveedit/text/TextComponentView.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/AnchorModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/CharMapDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/CodeDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/HTMLAreaDialogHandler.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/LinkModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/ModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/dialog/SearchReplaceModalDialog.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/editor/HTMLAreaBuilder.ts
modules/admin/admin-ui/src/main/resources/web/admin/common/js/util/htmlarea/plugins/code.js
modules/admin/admin-ui/src/main/resources/web/admin/common/lib/ckeditor/plugins/sharedspace/plugin.js
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/html-area.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/api/util/htmlarea/html-editor.less
modules/admin/admin-ui/src/main/resources/web/admin/common/styles/apps/content/wizard/content-wizard-panel.less
modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/text-view.less
modules/app/app-contentstudio/src/main/resources/com/enonic/xp/app/contentstudio/liveEditHeadEnd.html
modules/app/app-contentstudio/src/test/resources/com/enonic/xp/app/contentstudio/liveEditInjectionHeadEnd.html

Missing features for now:
-source dialog; will be added in other issue
for both inline and classic modes:
-blur/focus handlers commented now; cke wraps natural events with their own events, need to investiage more on this because some listeners expect natural FocusEvent that not present in cke event
-keyboard events handling

Configure CKEditor to work in inline mode #5129

---

modules/app/app-main/src/main/resources/assets/styles/launcher.less

-set height of tools area to be scrollable
-hiding scrollblar as it looks ugly

Broken layout in the Launcher panel when the list of tools is long #5514

---

modules/admin/admin-ui/src/main/resources/web/admin/live-edit/styles/less/partials/item-view.less

-ImageComponentView is wrapped on backend into Figure tag which has margins diffrent from div; setting margin to zero for empty ImageComponentView and letting it be as it is when image is selected

Page Editor - Image and Part components have unneeded margins #5432

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/ui/treegrid/TreeGrid.ts
modules/app/app-users/src/main/js/app/browse/ShowNewPrincipalDialogEvent.ts
modules/app/app-users/src/main/js/app/browse/UserBrowsePanel.ts
modules/app/app-users/src/main/js/app/browse/UserItemsTreeGrid.ts
modules/app/app-users/src/main/js/app/browse/action/NewPrincipalAction.ts
modules/app/app-users/src/main/js/app/create/NewPrincipalDialog.ts
modules/app/app-users/src/main/js/app/create/UserItemTypesTreeGrid.ts
modules/app/app-users/src/main/js/main.ts

Added `NewPrincipalDialog` with two options (User and User Group), when a user clicks on the `New...` button and User Store is selected.
Added manual canvas resize to shrink the dialog on open.

Hide options "User" and "User Group" in the dialog when a user storeis selected #5472

---

modules/admin/admin-ui/src/main/resources/web/admin/common/js/security/RoleKeys.ts

Added check for `truthy` principal key value to prevent error, when passing undefined key. This bug prevented some wizards to create steps properly.
_Related to issue #5466._

Fix undefined principal key in RoleKeys static functions

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/ChangePasswordHandler.java
modules/lib/lib-auth/src/test/java/com/enonic/xp/lib/auth/ChangePasswordHandlerTest.java
modules/lib/lib-auth/src/test/resources/site/test/changePassword-test.js

Added whitespaces removing from passwords in case client-side validation will fail.

UserWizard - trim spaces in a password field #5894

---

modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/PublishContentCommand.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetPublishInfoCommand.java

Added missing report for the pre-publish content processing.
_Since the publishing consist of two steps, it'll make the progress bar update more smoothly (it will no longer jump from 0% to 50% and then instantly to 100%). But the pre-publish updates are slower than publishing itself, so the progress bar will be filled faster after 50% because we depend on the amount of the processed content._

More dynamic update of progress bar in modal dialogs #6172

---

modules/core/core-ignite/src/main/java/com/enonic/xp/ignite/impl/config/ConfigurationFactory.java

This change removes the warning, by forcing to always use OptimizedMarshaller.
According to the javadocs there are some consequences: 
> Some Ignite features will not work if non-null marshaller is set (IgniteCache.withKeepBinary(), .NET, CPP, ODBC)
I think we do not currently use any of those features.

SessionData cannot be serialized (#6331)

---

modules/core/core-ignite/src/main/java/com/enonic/xp/ignite/impl/IgniteCluster.java

- Set IGNITE_NO_SHUTDOWN_HOOK to true to avoid Ignite JVM shutdown hook to happen before the controlled OSGi shutdown
- Removed some logging level switches that are available in Ignite 2.5.0 but not yet in [2.3.0](https://ignite.apache.org/releases/2.3.0/javadoc/org/apache/ignite/IgniteSystemProperties.html) that we currently use

Sessions in Ignite - Exception logged on shutdown of server (#6303)

---

modules/lib/lib-portal/src/main/java/com/enonic/xp/lib/portal/current/GetCurrentAbstractHandler.java
modules/lib/lib-portal/src/test/java/com/enonic/xp/lib/portal/current/GetCurrentContentScriptTest.java
modules/lib/lib-portal/src/test/java/com/enonic/xp/lib/portal/current/GetCurrentSiteConfigScriptTest.java
modules/lib/lib-portal/src/test/java/com/enonic/xp/lib/portal/current/GetCurrentSiteScriptTest.java
modules/portal/portal-api/src/main/java/com/enonic/xp/portal/handler/ControllerHandlerWorker.java

As you see I only fixed for the current content on controllers for now.
I will make an epic task if we judge necessary to fix it at content service level (as it has many impacts: content studio, toolbox CLI interface, ...)

Handle case of '/content' node and call to controllers with content path '/' (#6506)

---

modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityServiceImpl.java

* Replaced `HashSet` with the `LinkedHashSet` to prevent the change of the keys order.

Roles and Groups are incorrectly sorted on the UserItemStatisticsPanel #7021

---

modules/lib/lib-portal/src/main/resources/lib/xp/portal.js

The key `params.type` was used on both line 79 and 81. It appears that this is a typo, and the correct key on line 79 should be `param.label`.

Fix jsdoc for "attachmentUrl" in portal lib

---

modules/web/web-impl/src/main/java/com/enonic/xp/web/impl/handler/WebDispatcherImpl.java
modules/web/web-impl/src/test/java/com/enonic/xp/web/impl/handler/TestWebHandler.java
modules/web/web-impl/src/test/java/com/enonic/xp/web/impl/handler/WebDispatcherImplTest.java

- keep elements with same order. So we need a list, not a set with comparator (initially I tried SkipListSet and it didn't work well)
- avoid synchronized methods. AtomicReference with CAS works great for occasionally happening add/remove, so CopyOnWrite is not needed.
- avoid copying on every dispatch (this is why ImmutableList instead of copyOnwSrite)
- Don't expose mutable iterator. ImmutableList helps here as well.
- fix comparator so now it correctly sorts big integers like MAX_INT and MIN_INT
- also funny the implementation had race condition: add method for a short while was introducing handler at the end of chain regardless of its real order and this change was visible in dispatch. So Order was not always respected.

WebDispatcherImpl implementation issues #7523

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentMediaResource.java
modules/core/core-i18n/src/main/java/com/enonic/xp/core/impl/i18n/LocaleServiceImpl.java
modules/core/core-i18n/src/main/java/com/enonic/xp/core/impl/i18n/MessageBundleImpl.java

Starting from Java 9 .properties support UFT8 So conversion is not needed for "broken" files. They are not broken anymore
Also both places we use UnsupportedEncodingException we can simply provide StandardEncoding

Remove usage of UnsupportedEncodingException where possible #7533

---

modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationListener.java
modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationService.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationListenerHub.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationRegistry.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/config/ApplicationConfigInvalidator.java
modules/core/core-app/src/test/java/com/enonic/xp/core/impl/app/ApplicationServiceImplTest.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExecutorManager.java

`ApplicationListener` got deprecated as it was never used. `ApplicationListenerHub` responsible for `ApplicationListener`s notification is kept but no longer able to catch all application bundle events because it is now controlled by `ApplicationServiceImpl` which has no fully synchronous control over bundle/application binding . It was the main cause of issue: `ApplicationListenerHub` could invalidate Application instance too early (while it was still in STOPPING state), causing other threads to re-capture reference to a dying bundle.
`ApplicationService` invalidate method got deprecated. It is unreliable and can cause deadlocks.
Fallback to ConfigAdmin is kept is branch 7.2 to simplify PR readability, but will be removed in master.
`ScriptExecutorManager` now verifies `BundleContext` …

Application fails to update properly under load #7978

---

modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationListener.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationListenerHub.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/resource/ResourceServiceImpl.java
modules/core/core-i18n/src/main/java/com/enonic/xp/core/impl/i18n/LocaleServiceImpl.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/ScriptRuntimeFactoryDelegate.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/ScriptRuntimeInternal.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/ScriptRuntimeProvider.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/event/ScriptEventManagerImpl.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExecutorManager.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/purplejs/PurpleJsRuntimeProviderImpl.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/standard/ScriptRuntimeFactoryImpl.java
modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/standard/ScriptRuntimeImpl.java

`ApplicationListener` de-deprecated as it can be handy to run some tasks before application gets stopped. But now listeners executed synchronously. Moreover, `deactivated` now called before application gets deactivated (besides the name) - it used to be like this anyway before #7991
With a help of `ApplicationListener` implementation, it is now possible to run `__disposer` methods right before application is stopped.

Unable to load class because the bundle wiring is no longer valid #7132

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ComponentNameResolverImpl.java
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ComponentNameResolverImplTest.java

- Returning component type name when attached content removed
- Using try-catch clause to define if attached content is there or not (not using contentExists since it fetches node with try-catch itself)

Resolving component name fails when attached content is not found #8080

---

modules/web/web-api/src/main/java/com/enonic/xp/web/servlet/ServletRequestUrlHelper.java
modules/web/web-api/src/test/java/com/enonic/xp/web/servlet/ServletRequestUrlHelperTest.java

X-Forwarded-... headers now all assumed to contain comma separated values
Also added support for X-Forwarded-Port header.
And "fixed" one another related issue where port was assumed to server one if it was not specified in X-Forwarded-Host or X-Forwarded-Port. Now port in url will be not set.

XP does not handle X-Forwarded-Host correctly #7708

---

modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationService.java
modules/core/core-api/src/main/java/com/enonic/xp/event/Event.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/event/ApplicationClusterEventListener.java
modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/event/ApplicationClusterEvents.java
modules/core/core-app/src/test/java/com/enonic/xp/core/impl/app/ApplicationClusterEventListenerTest.java
modules/core/core-app/src/test/java/com/enonic/xp/core/impl/app/ApplicationServiceImplTest.java

Before start/stop/uninstall the initiator node sends a respective event to other nodes in the cluster. Other nodes try to start/stop/uninstall - it happens simultaneously on all nodes.
application install is more complex process, as it needs to persist app first into shared storage. So it still waits for install to finish on initiator node.

Simultaneous app start/stop on all nodes #8360

---

gradle/versions.gradle
modules/lib/lib-context/build.gradle
modules/lib/lib-event/build.gradle
modules/lib/lib-i18n/build.gradle
modules/lib/lib-i18n/src/main/java/com/enonic/xp/lib/i18n/LocaleScriptBean.java
modules/lib/lib-i18n/src/test/java/com/enonic/xp/lib/i18n/GetSupportedLocalesScriptTest.java
modules/lib/lib-i18n/src/test/java/com/enonic/xp/lib/i18n/I18NScriptTest.java
modules/lib/lib-i18n/src/test/java/com/enonic/xp/lib/i18n/LocalizeNoHttpTest.java
modules/lib/lib-i18n/src/test/resources/test/localize-nohttp-test.js
modules/lib/lib-io/build.gradle
modules/lib/lib-portal/src/main/java/com/enonic/xp/lib/portal/multipart/MultipartHandler.java
modules/lib/lib-portal/src/main/java/com/enonic/xp/lib/portal/url/AbstractUrlHandler.java
modules/lib/lib-task/src/main/java/com/enonic/xp/lib/task/SubmitNamedTaskHandler.java
modules/tools/testing/build.gradle
modules/tools/testing/src/main/java/com/enonic/xp/testing/ScriptTestSupport.java

- access PortalRequest from script bindings where possible. This is the main part.
- update Mockito to latest. Initially I blamed Mockito for a bug.
- specified version for `org.junit.vintage:junit-vintage-engine` dependency. Without it Gradle didn't want to build.
- re-enabled a few tests. They were disabled due to this issue, I guess.

Access PortalRequest via script context #8467

---

modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/SseEntryPoint.java
modules/server/server-rest/src/test/java/com/enonic/xp/impl/server/rest/SseEntryPointTest.java
modules/web/web-jetty/src/main/java/com/enonic/xp/web/jetty/impl/configurator/GZipConfigurator.java

Main fix: disabled gzip for SSE. At least for now. see https://github.com/enonic/xp/issues/8518#issuecomment-736538234
A few other polishes:
- For some reason Resteasy injects Context twice. 
https://github.com/resteasy/Resteasy/blob/master/resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java#L228
https://github.com/resteasy/Resteasy/blob/master/resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java#L246
~~TODO: Create an issue for Resteasy?~~ https://issues.redhat.com/browse/RESTEASY-2779
That causes race conditions for us, so sse Context variable is set, I ignore others
- In case of not yet set contextHolder we should throw an error (well, it never happens, but still...), otherwise, if no error is thrown, client just hangs and never …

Management SSE for apps fails when Accept-Encoding is sent #8518

---

modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/app/MainWebHandlerTest.java
modules/portal/portal-api/src/main/java/com/enonic/xp/portal/PortalResponse.java
modules/web/web-api/src/main/java/com/enonic/xp/web/WebResponse.java
modules/web/web-api/src/test/java/com/enonic/xp/web/WebResponseTest.java

There were a few iterations of HTTP header specs and how they should handled
Firstly they are case-insensitive preferably lowercased
https://tools.ietf.org/html/rfc7540#section-8.1.2
Secondly the order is not significant
https://tools.ietf.org/html/rfc7230#section-3.2.2
So, it is safe to lowercase them and when response is built, headers get populated into case-insensitive sorted map (for backwards compatibility, so `location = headers['Location']` works equally to `location = headers['location']`)
Instead of throwing an Exception, it is possible to replace previous header values with new ones.
This is the easiest fix for now. More info in https://github.com/enonic/xp/issues/8404#issuecomment-737301463

Duplicate headers in controller creates a crash. #8404

---

modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueMailMessageGenerator.java
modules/admin/admin-impl/src/main/resources/com/enonic/xp/admin/impl/rest/resource/issue/email.html
modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationsSenderImplTest.java

-Outlook ignores lots of HTML tags and attributes, using those that it supports
-Correctly resolving issue link for default layer

Issue mail generator: 'Show details' button is broken in Outlook #8627

---

modules/core/core-hazelcast/src/main/java/com/enonic/xp/core/impl/hazelcast/status/objects/HazelcastObjectsReport.java
modules/core/core-hazelcast/src/main/java/com/enonic/xp/core/impl/hazelcast/status/objects/HazelcastObjectsReporter.java
modules/core/core-hazelcast/src/main/java/com/enonic/xp/core/impl/hazelcast/status/objects/ScheduledExecutorServiceObjectReport.java
modules/core/core-hazelcast/src/main/java/com/enonic/xp/core/impl/hazelcast/status/objects/ScheduledTaskReport.java
modules/core/core-hazelcast/src/test/java/com/enonic/xp/core/impl/hazelcast/status/objects/HazelcastObjectsReporterTest.java
modules/core/core-hazelcast/src/test/resources/com/enonic/xp/core/impl/hazelcast/status/objects/hazelcast_objects.json
modules/core/core-scheduler/src/main/java/com/enonic/xp/impl/scheduler/SchedulerExecutorService.java
modules/core/core-scheduler/src/main/java/com/enonic/xp/impl/scheduler/SchedulerServiceActivator.java
modules/core/core-scheduler/src/main/java/com/enonic/xp/impl/scheduler/SystemScheduler.java
modules/core/core-scheduler/src/main/java/com/enonic/xp/impl/scheduler/distributed/RescheduleTask.java
modules/core/core-scheduler/src/test/java/com/enonic/xp/impl/scheduler/distributed/RescheduleTaskTest.java

catch all Throwables in RescheduleTask is the main fix.
Additional improvements:
- improved (currently undocumented) statistics endpoint, so it reports HZ ScheduledExecutorServices with some extra info needed for debug
- Added debug logging in a few important places
- Made RescheduleTask log counter thread safe

Scheduled tasks may not run on clustered environments

---

modules/web/web-vhost/src/main/java/com/enonic/xp/web/vhost/impl/VirtualHostResolverImpl.java

`serverName.toLowerCase().equals(host.toLowerCase())` can be changed (back) to `serverName.equalsIgnoreCase(host)` for simplicity

Host case sensitivity #9115

---

modules/core/core-api/src/main/java/com/enonic/xp/image/Cropping.java
modules/core/core-api/src/test/java/com/enonic/xp/image/ReadImageParamsTest.java
modules/core/core-image/src/main/java/com/enonic/xp/core/impl/image/NormalizedImageParams.java
modules/core/core-image/src/main/java/com/enonic/xp/core/impl/image/effect/ScaleCalculator.java
modules/core/core-image/src/main/java/com/enonic/xp/core/impl/image/effect/ScaledFunction.java
modules/core/core-image/src/test/java/com/enonic/xp/core/impl/image/NormalizedImageParamsTest.java
modules/core/core-image/src/test/java/com/enonic/xp/core/impl/image/effect/ScaleCalculatorTest.java
modules/core/core-image/src/test/java/com/enonic/xp/core/impl/image/effect/ScaledFunctionTest.java

`Math.max( Math.min( centered, 0 ), diff );` changed to `Math.min( Math.max( centered, 0 ), diff );`
Additional fixes:
- if cropping is specified but not essential, it won't affect file cache key
- estimated resolution for memory constraints did not take into account image height (it was WxW instead of WxH)

Focal point no longer works in image service #9244

---

modules/lib/lib-admin/README.md
modules/lib/lib-admin/build.gradle
modules/lib/lib-admin/src/main/resources/lib/xp/admin.ts
modules/lib/lib-i18n/src/main/resources/lib/xp/i18n.ts

Added lib-admin types.
Updated `getPhrases` return type to more specific object.
Fixed `generateHomeToolUri` helper's call, since it was renamed to `getHomeToolUri`.

Migrate Javascript API to Typescript for lib-admin #9537

---

modules/lib/lib-content/src/main/resources/lib/xp/content.ts
modules/lib/lib-portal/src/main/resources/lib/xp/portal.ts

This commit adds two type parameters to the `Content` interface to make it possible to configure the shape of `Content.data` and `Content.type`.
By having the `Content.data` field specified by the `<Data>` type parameter a JavaScript-/TypeScript-developer can now easily specify the correct shape of `Content` (without using hacks like `as`). The `Content.type` field can be narrowed by setting the `<Type>` type parameter to a string literal (e.g. `"com.mycompany:article"`). This makes a union of `Content` into a discriminated union, where we can use normal `if`-statements to split the union.
The fallback value for `Content.data` is `Record<string, unknown>` and `Content.type` is `string` so the default shape of `Content` is by default the exact same as it was before this commit.
The `x` …

Add type parameters to Content

---

modules/lib/lib-grid/src/main/resources/lib/xp/grid.ts
modules/lib/lib-scheduler/src/main/resources/lib/xp/scheduler.ts

Added generics for better and typesafe mappings.
Renamed `ISharedMap` to `JavaSharedMap`.
Renamed `SharedMap` to `SharedMapImpl`.
Added `SharedMap` interface and made it exportable instead of `SharedMapImpl` class. Removed default value in internal generics.

Grid Library types improvements #9730

---

modules/lib/lib-content/src/main/resources/lib/xp/content.ts

Added global `XpXData` interface to prevent reference injection into the DTS file on compile.
Removed unused imports.

Content library type definitions contain invalid core reference #9766

---

modules/lib/lib-content/src/main/resources/lib/xp/content.ts
modules/lib/lib-portal/src/main/resources/lib/xp/portal.ts

The return type of `contentLib.query()` (and similar functions) should have the shape `Content<A, 'a'> | Content<B, 'b'>` instead of the current implementation which is `Content<A | B, 'a' | 'b'>`.
This change allows TypeScript to infer the correct type of content by using a simple if-statement against `Content.type`, which is the natural way for an application programmer to do this.

TypeScript type for Union of Content #9808

---

modules/lib/core/index.d.ts

See explanation in [task](https://github.com/enonic/xp/issues/9840) description.

Login property in User type must not be optional #9840

---

modules/lib/lib-content/src/main/resources/lib/xp/content.ts
modules/lib/lib-node/src/main/resources/lib/xp/node.ts

`DslQueryType` must not be `LiteralUnion`, `boolean` or `number`. `'dateTime' | 'time'` is the only valid options.
See how the `type` property of type `DslQueryType` is [parsed](https://github.com/enonic/xp/blob/master/modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/elasticsearch/query/translator/factory/dsl/ExpressionQueryBuilder.java#L37) in Java.

DslQueryType has illegal type #9848

---

modules/lib/lib-node/src/main/resources/lib/xp/node.ts

Example [here](https://github.com/enonic/xp/blob/master/modules/lib/lib-node/src/main/resources/lib/xp/examples/node/create-2.js#L38).

Node library: CreateNodeParams accepts invalid index config #9844

---

modules/lib/lib-content/src/main/resources/lib/xp/content.ts
modules/lib/lib-node/src/main/resources/lib/xp/node.ts

Types for aggregations and suggestions in result and in params were incorrect. I tried to make them match the Java implementation and work with JS examples, but I'm not 100% everything is correct, so it's better to test them on some real data before actually releasing.
What were changed:
* `StatsAggregation` interface was declared twice and used both in result and in params types. The stats aggregation in result is now called `StatsAggregationResult`.
* `suggestions` in result type was invalid, according to the [examples](https://github.com/enonic/xp/blob/master/modules/lib/lib-node/src/main/resources/lib/xp/examples/node/query.js#L175).
* Same for the `aggregations`. See [examples](https://github.com/enonic/xp/blob/master/modules/lib/lib-node/src/main/resources/lib/xp/examples/node/query. …

Node and Content libs: wrong query results #9850

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/rendering/TextRenderer.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/rendering/TextRendererTest.java

- removed extra `div` in EDIT mode
In addition empty text component renders the same (empty string) in PREVIEW and INLINE

Text component should not be wrapped inside a div in edit mode #9453

---

modules/lib/core/index.d.ts
modules/lib/global.d.ts
modules/lib/lib-export/src/main/resources/lib/xp/export.ts
modules/lib/lib-io/src/main/resources/lib/xp/io.ts

Moved the `ResourceKey` to core package.
Made `resolve` function definition in `global.d.ts` to return the same object as `ResourceKey`. I don't want to make `global.d.ts` depend on `core` and be importable, neither define `ResourceKey` in global scope. I guess `ResourceKey` is not something that will change and we can keep compromise here using the identical "types" in different contexts.

TS Add return type of resolve function #9761

---

modules/lib/lib-node/src/main/resources/lib/xp/node.ts

Part of the functions were already improved, so `isObject` was the only one that left.

Improve TypeScript libs code #9793

---

modules/lib/lib-node/src/main/resources/lib/xp/node.ts

Adds the possibility to get a single node returned if you pass in an Array.
Also removes 3rd overload, because it has the same parameters as the 4th, but is missing the case for the single node return.

Improve types for `RepoConnection.get()` in nodeLib #10044

---

modules/lib/core/index.d.ts

Moved `GeoDistanceAggregation` type to separate check from `BucketsAggregationsUnion`, since it's the only bucket aggregation, that does not contain sub-aggregations, wich resulted in type errors in DTS files (not sure why TS does not show errors here).

Aggregations type cast error #10086

---

modules/lib/core/index.d.ts

A pull request with only the Content change
(this PR replaces https://github.com/enonic/xp/pull/10119)

Fix 10118 Typing for Content doesn't match fragment content

---

modules/lib/core/index.d.ts

Both fragment and page has to be optional, or we have to convert the interface to a type which has a conditional union or something similar:
https://github.com/sindresorhus/type-fest/blob/main/source/require-exactly-one.d.ts
https://stackoverflow.com/questions/49524414/typescript-interface-conditional-optional-parameters
This also support 'base:folder' by allowing page to be an empty object.
And fixes the fact that data is an empty object for portal:fragment, not undefined.

Fix #10176 Avoid having to set fragment: undefined everywhere

---

modules/lib/core/index.d.ts

Made the `modifiedTime` property optional so that the type matches some predefined users, such as ANONYMOUS.

User.modifiedTime should be optional #10221

---

modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/CreateRoleHandler.java
modules/lib/lib-auth/src/main/java/com/enonic/xp/lib/auth/CreateUserHandler.java

Made behaviour in `createUser` and `createRole` consistent with `createGroup`: use `name` when `displayName` is omitted

CreateRoleParams displayName is optional but throws NPE #10486

---

modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/vacuum/versiontable/VersionTableVacuumCommand.java
modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/vacuum/versiontable/VersionTableVacuumTask.java
modules/itest/itest-core/src/test/java/com/enonic/xp/core/repo/vacuum/versiontable/VersionTableVacuumTaskTest.java

(cherry picked from commit d7f125d6a1a28ededfd433c3b4d47653da9160b6)

Vacuum Task for Transient repositories #10690

---

modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/mapping/ComponentServiceMappingHandler.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/mapping/MappingHandler.java
modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/mapping/MappingHandlerHelper.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/handler/mapping/ComponentServiceMappingHandlerTest.java
modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/handler/mapping/MappingHandlerTest.java

- Added Page resolving for the mappers, thus request get content with injected page/regions etc.

lib-portal.getContent doesn't resolve page templates #10800

---

modules/core/core-api/src/main/java/com/enonic/xp/region/Component.java
modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ComponentDataSerializer.java
modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/serializer/PageDataSerializerTest.java
modules/lib/lib-content/src/test/resources/test/GetContentHandlerTest.js

- A component is supposed to always have some path, but in case of a fragment content it's root fragment component was having null returned as path. Fixing it by setting component's path to "/" in case it doesn't have a region (which means it is a fragment)

portal.getComponent is missing path in fragment preview #10116
